// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Zora = require("zora");
let Stdlib_Result = require("@rescript/runtime/lib/js/Stdlib_Result.js");
let Packet_NetModuleLoad$TerrariaPacket = require("../src/packet/Packet_NetModuleLoad.js");

Zora.test("should correctly parse and serialise FarPlacementRangePower", t => {
  let hex = "28005206000b0000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f";
  let buffer = Buffer.from(hex, "hex");
  let p = Packet_NetModuleLoad$TerrariaPacket.parse(buffer, true);
  if (p !== undefined) {
    if (p.TAG === "CreativePower") {
      let match = p._0;
      if (typeof match !== "object" || match.TAG !== "FarPlacementRangePower") {
        t.fail("Failed to parse packet");
      } else {
        let values = match._0;
        if (values.TAG === "Everyone") {
          t.ok(values._0.every(v => v));
        } else {
          t.fail("Failed to parse packet");
        }
      }
    } else {
      t.fail("Failed to parse packet");
    }
    let buffer$1 = Packet_NetModuleLoad$TerrariaPacket.toBuffer(p);
    let hexOutput = Stdlib_Result.map(buffer$1, v => v.toString("hex"));
    t.equal({
      TAG: "Ok",
      _0: hex
    }, hexOutput);
    return;
  }
  t.fail("Failed to parse packet");
});

Zora.test("should correctly parse and serialise GodmodePower", t => {
  let hex = "28005206000500000100000000000000000000000000000000000000000000000000000000000000";
  let buffer = Buffer.from(hex, "hex");
  let p = Packet_NetModuleLoad$TerrariaPacket.parse(buffer, true);
  if (p !== undefined) {
    if (p.TAG === "CreativePower") {
      let match = p._0;
      if (typeof match !== "object" || match.TAG !== "GodmodePower") {
        t.fail("Failed to parse packet");
      } else {
        let values = match._0;
        if (values.TAG === "Everyone") {
          let values$1 = values._0;
          t.ok(values$1.slice(1).every(v => !v));
          t.equal(values$1[0], true);
        } else {
          t.fail("Failed to parse packet");
        }
      }
    } else {
      t.fail("Failed to parse packet");
    }
    let buffer$1 = Packet_NetModuleLoad$TerrariaPacket.toBuffer(p);
    let hexOutput = Stdlib_Result.map(buffer$1, v => v.toString("hex"));
    t.equal({
      TAG: "Ok",
      _0: hex
    }, hexOutput);
    return;
  }
  t.fail("Failed to parse packet");
});

/*  Not a pure module */
