// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Parser$TerrariaPacket from "../src/Parser.js";

Zora.test("should correctly parse PlayerSpawn (2)", t => {
  let data = Buffer.from("12000c00ffffffff00000000000000000109", "hex");
  let result = Parser$TerrariaPacket.parse(data, false);
  if (result.TAG === "Ok") {
    t.ok(true);
    return;
  }
  console.log(result._0);
  t.fail();
});

/*  Not a pure module */
