// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketType$TerrariaPacket from "../PacketType.js";
import * as ErrorAwarePacketReader$TerrariaPacket from "../ErrorAwarePacketReader.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";
import Packetreader from "@popstarfreas/packetfactory/packetreader";

function parse(payload, fromServer) {
  let reader = new Packetreader(payload);
  if (fromServer) {
    let e = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "blockedChestCount");
    if (e.TAG !== "Ok") {
      return e;
    }
    let count = e._0;
    let chestIds = [];
    let readChests = _idx => {
      while (true) {
        let idx = _idx;
        if (idx >= count) {
          return {
            TAG: "Ok",
            _0: undefined
          };
        }
        let e = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, `blockedChest` + idx.toString());
        if (e.TAG !== "Ok") {
          return e;
        }
        chestIds.push(e._0);
        _idx = idx + 1 | 0;
        continue;
      };
    };
    let e$1 = readChests(0);
    if (e$1.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          TAG: "ServerBlockedChests",
          _0: {
            chestIds: chestIds
          }
        }
      };
    } else {
      return e$1;
    }
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "slotCount");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let count$1 = e$2._0;
  let slotIds = [];
  let readSlots = _idx => {
    while (true) {
      let idx = _idx;
      if (idx >= count$1) {
        return {
          TAG: "Ok",
          _0: undefined
        };
      }
      let e = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, `slot` + idx.toString());
      if (e.TAG !== "Ok") {
        return e;
      }
      slotIds.push(e._0);
      _idx = idx + 1 | 0;
      continue;
    };
  };
  let e$3 = readSlots(0);
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let e$4 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "smartStack");
  if (e$4.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        TAG: "ClientRequest",
        _0: {
          slotIds: slotIds,
          smartStack: e$4._0 !== 0
        }
      }
    };
  } else {
    return e$4;
  }
}

let Decode = {
  readInt16: ErrorAwarePacketReader$TerrariaPacket.readInt16,
  readUInt16: ErrorAwarePacketReader$TerrariaPacket.readUInt16,
  readInt32: ErrorAwarePacketReader$TerrariaPacket.readInt32,
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  parse: parse
};

function packSlotIds(writer, slotIds) {
  let writer$1 = ErrorAwarePacketWriter$TerrariaPacket.packInt32(writer, slotIds.length, "slotCount");
  slotIds.forEach((slotId, idx) => {
    ErrorAwarePacketWriter$TerrariaPacket.packInt16(writer$1, slotId, `slot` + idx.toString());
  });
  return writer$1;
}

function packChestIds(writer, chestIds) {
  let writer$1 = ErrorAwarePacketWriter$TerrariaPacket.packInt32(writer, chestIds.length, "blockedChestCount");
  chestIds.forEach((chestId, idx) => {
    ErrorAwarePacketWriter$TerrariaPacket.packUInt16(writer$1, chestId, `blockedChest` + idx.toString());
  });
  return writer$1;
}

function toBuffer(self) {
  let writer = ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("ItemForceIntoNearestChest"));
  if (self.TAG !== "ClientRequest") {
    return ErrorAwarePacketWriter$TerrariaPacket.data(packChestIds(writer, self._0.chestIds));
  }
  let match = self._0;
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packByte(packSlotIds(writer, match.slotIds), match.smartStack ? 1 : 0, "smartStack"));
}

let Encode = {
  Writer: undefined,
  packInt16: ErrorAwarePacketWriter$TerrariaPacket.packInt16,
  packUInt16: ErrorAwarePacketWriter$TerrariaPacket.packUInt16,
  packInt32: ErrorAwarePacketWriter$TerrariaPacket.packInt32,
  packByte: ErrorAwarePacketWriter$TerrariaPacket.packByte,
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  packSlotIds: packSlotIds,
  packChestIds: packChestIds,
  toBuffer: toBuffer
};

export {
  Decode,
  Encode,
  parse,
  toBuffer,
}
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
