// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ManagedPacketWriter$PacketFactory = require("@popstarfreas/packetfactory/src/ManagedPacketWriter.js");
let Packetwriter = require("@popstarfreas/packetfactory/packetwriter").default;

function parse(_payload) {
  return {
    TAG: "Ok",
    _0: undefined
  };
}

let Decode = {
  parse: parse
};

function data(prim) {
  return prim.data;
}

function toBuffer(_self) {
  return {
    TAG: "Ok",
    _0: ManagedPacketWriter$PacketFactory.setType(new Packetwriter(), PacketType$TerrariaPacket.toInt("WorldDataRequest")).data
  };
}

let Encode = {
  setType: ManagedPacketWriter$PacketFactory.setType,
  data: data,
  toBuffer: toBuffer
};

exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* @popstarfreas/packetfactory/packetwriter Not a pure module */
