// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ManagedPacketWriter$PacketFactory = require("@popstarfreas/packetfactory/src/ManagedPacketWriter.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;
let Packetwriter = require("@popstarfreas/packetfactory/packetwriter").default;

function unlockTypeToInt(self) {
  switch (self) {
    case "Chest" :
      return 1;
    case "TempleDoor" :
      return 2;
    case "ChestLock" :
      return 3;
  }
}

function unlockTypeFromInt(self) {
  switch (self) {
    case 1 :
      return "Chest";
    case 2 :
      return "TempleDoor";
    case 3 :
      return "ChestLock";
    default:
      return;
  }
}

function readByte(prim) {
  return prim.readByte();
}

function readInt16(prim) {
  return prim.readInt16();
}

function parse(payload) {
  let reader = new Packetreader(payload);
  let unlockType = unlockTypeFromInt(reader.readByte());
  let x = reader.readInt16();
  let y = reader.readInt16();
  if (unlockType !== undefined) {
    return {
      unlockType: unlockType,
      x: x,
      y: y
    };
  }
}

let Decode = {
  readByte: readByte,
  readInt16: readInt16,
  parse: parse
};

function packByte(prim0, prim1) {
  return prim0.packByte(prim1);
}

function packInt16(prim0, prim1) {
  return prim0.packInt16(prim1);
}

function data(prim) {
  return prim.data;
}

function toBuffer(self) {
  return ManagedPacketWriter$PacketFactory.setType(new Packetwriter(), PacketType$TerrariaPacket.toInt("ChestOrTempleUnlock")).packByte(unlockTypeToInt(self.unlockType)).packInt16(self.x).packInt16(self.y).data;
}

let Encode = {
  Writer: undefined,
  packByte: packByte,
  packInt16: packInt16,
  setType: ManagedPacketWriter$PacketFactory.setType,
  data: data,
  toBuffer: toBuffer
};

exports.unlockTypeToInt = unlockTypeToInt;
exports.unlockTypeFromInt = unlockTypeFromInt;
exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* @popstarfreas/packetfactory/packetreader Not a pure module */
