// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../ErrorAwarePacketReader.js");
let ErrorAwarePacketWriter$TerrariaPacket = require("../ErrorAwarePacketWriter.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;

function teleportTypeToInt(teleportType) {
  switch (teleportType) {
    case "TeleportationPotion" :
      return 0;
    case "MagicConch" :
      return 1;
    case "DemonConch" :
      return 2;
    case "ShellphoneSpawn" :
      return 3;
  }
}

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "teleportType");
  if (e.TAG !== "Ok") {
    return e;
  }
  switch (e._0) {
    case 0 :
      return {
        TAG: "Ok",
        _0: {
          teleportType: "TeleportationPotion"
        }
      };
    case 1 :
      return {
        TAG: "Ok",
        _0: {
          teleportType: "MagicConch"
        }
      };
    case 2 :
      return {
        TAG: "Ok",
        _0: {
          teleportType: "DemonConch"
        }
      };
    case 3 :
      return {
        TAG: "Ok",
        _0: {
          teleportType: "ShellphoneSpawn"
        }
      };
    default:
      return {
        TAG: "Error",
        _0: {
          context: "Packet_TeleportationPotion.parse",
          error: new Error("Unknown teleport type")
        }
      };
  }
}

let Decode = {
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  readInt16: ErrorAwarePacketReader$TerrariaPacket.readInt16,
  parse: parse
};

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("TeleportationPotion")), teleportTypeToInt(self.teleportType), "teleportType"));
}

let Encode = {
  Writer: undefined,
  packByte: ErrorAwarePacketWriter$TerrariaPacket.packByte,
  packInt16: ErrorAwarePacketWriter$TerrariaPacket.packInt16,
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  toBuffer: toBuffer
};

exports.teleportTypeToInt = teleportTypeToInt;
exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
