// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../ErrorAwarePacketReader.js");
let ErrorAwarePacketWriter$TerrariaPacket = require("../ErrorAwarePacketWriter.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readString(reader, "uuid");
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        uuid: e._0
      }
    };
  } else {
    return e;
  }
}

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packString(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("ClientUuid")), self.uuid, "uuid"));
}

exports.parse = parse;
exports.toBuffer = toBuffer;
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
