// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var BitFlags$TerrariaPacket = require("../BitFlags.js");
var PacketType$TerrariaPacket = require("../PacketType.js");
var ErrorAwarePacketReader$TerrariaPacket = require("../ErrorAwarePacketReader.js");
var ErrorAwarePacketWriter$TerrariaPacket = require("../ErrorAwarePacketWriter.js");
var Packetreader = require("@popstarfreas/packetfactory/packetreader").default;

function parse(payload) {
  var reader = new Packetreader(payload);
  var playerId = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "playerId");
  var controlFlags = BitFlags$TerrariaPacket.fromByte(ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "controlFlags"));
  var miscFlags1 = BitFlags$TerrariaPacket.fromByte(ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "miscFlags1"));
  var miscFlags2 = BitFlags$TerrariaPacket.fromByte(ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "miscFlags2"));
  var miscFlags3 = BitFlags$TerrariaPacket.fromByte(ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "miscFlags3"));
  var control_isHoldingUp = BitFlags$TerrariaPacket.flag1(controlFlags);
  var control_isHoldingDown = BitFlags$TerrariaPacket.flag2(controlFlags);
  var control_isHoldingLeft = BitFlags$TerrariaPacket.flag3(controlFlags);
  var control_isHoldingRight = BitFlags$TerrariaPacket.flag4(controlFlags);
  var control_isHoldingJump = BitFlags$TerrariaPacket.flag5(controlFlags);
  var control_isHoldingItemUse = BitFlags$TerrariaPacket.flag6(controlFlags);
  var control = {
    isHoldingUp: control_isHoldingUp,
    isHoldingDown: control_isHoldingDown,
    isHoldingLeft: control_isHoldingLeft,
    isHoldingRight: control_isHoldingRight,
    isHoldingJump: control_isHoldingJump,
    isHoldingItemUse: control_isHoldingItemUse
  };
  var direction = BitFlags$TerrariaPacket.flag7(controlFlags) ? "Right" : "Left";
  var pulleyDirection = BitFlags$TerrariaPacket.flag1(miscFlags1) ? (
      BitFlags$TerrariaPacket.flag2(miscFlags1) ? "Two" : "One"
    ) : undefined;
  var vortexStealthActive = BitFlags$TerrariaPacket.flag4(miscFlags1);
  var gravityDirection = BitFlags$TerrariaPacket.flag5(miscFlags1) ? "Normal" : "Inverted";
  var shouldGuard = BitFlags$TerrariaPacket.flag6(miscFlags1);
  var ghost = BitFlags$TerrariaPacket.flag7(miscFlags1);
  var selectedItem = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "selectedItem");
  var position_x = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "positionX");
  var position_y = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "positionY");
  var position = {
    x: position_x,
    y: position_y
  };
  var velocity = BitFlags$TerrariaPacket.flag3(miscFlags1) ? ({
        x: ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "velocityX"),
        y: ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "velocityY")
      }) : undefined;
  var potionOfReturn = BitFlags$TerrariaPacket.flag7(miscFlags2) ? ({
        originalUsePosition: {
          x: ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "potionOfReturnOrigX"),
          y: ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "potionOfReturnOrigY")
        },
        homePosition: {
          x: ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "potionOfReturnHomeX"),
          y: ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "potionOfReturnHomeY")
        }
      }) : undefined;
  var tryKeepingHoveringUp = BitFlags$TerrariaPacket.flag1(miscFlags2);
  var isVoidVaultEnabled = BitFlags$TerrariaPacket.flag2(miscFlags2);
  var isSitting = BitFlags$TerrariaPacket.flag3(miscFlags2);
  var hasFinishedAnyDd2Event = BitFlags$TerrariaPacket.flag4(miscFlags2);
  var isPettingAnimal = BitFlags$TerrariaPacket.flag5(miscFlags2);
  var isTheAnimalBeingPetSmall = BitFlags$TerrariaPacket.flag6(miscFlags2);
  var tryKeepingHoveringDown = BitFlags$TerrariaPacket.flag8(miscFlags2);
  var isSleeping = BitFlags$TerrariaPacket.flag1(miscFlags3);
  return {
          playerId: playerId,
          control: control,
          direction: direction,
          pulleyDirection: pulleyDirection,
          vortexStealthActive: vortexStealthActive,
          gravityDirection: gravityDirection,
          shouldGuard: shouldGuard,
          ghost: ghost,
          selectedItem: selectedItem,
          position: position,
          velocity: velocity,
          potionOfReturn: potionOfReturn,
          tryKeepingHoveringUp: tryKeepingHoveringUp,
          isVoidVaultEnabled: isVoidVaultEnabled,
          isSitting: isSitting,
          hasFinishedAnyDd2Event: hasFinishedAnyDd2Event,
          isPettingAnimal: isPettingAnimal,
          isTheAnimalBeingPetSmall: isTheAnimalBeingPetSmall,
          tryKeepingHoveringDown: tryKeepingHoveringDown,
          isSleeping: isSleeping
        };
}

function packControlFlags(writer, control, direction) {
  var tmp;
  tmp = direction === "Left" ? false : true;
  return ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, BitFlags$TerrariaPacket.toByte(BitFlags$TerrariaPacket.fromFlags(control.isHoldingUp, control.isHoldingDown, control.isHoldingLeft, control.isHoldingRight, control.isHoldingJump, control.isHoldingItemUse, tmp, false)), "controlFlags");
}

function packMiscFlags1(writer, pulleyDirection, velocity, vortexStealthActive, gravityDirection, shouldGuard, ghost) {
  var tmp;
  tmp = pulleyDirection !== undefined && pulleyDirection !== "One" ? true : false;
  var tmp$1;
  tmp$1 = gravityDirection === "Normal" ? true : false;
  return ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, BitFlags$TerrariaPacket.toByte(BitFlags$TerrariaPacket.fromFlags(pulleyDirection !== undefined, tmp, velocity !== undefined, vortexStealthActive, tmp$1, shouldGuard, ghost, false)), "miscFlags1");
}

function packMiscFlags2(writer, tryKeepingHoveringUp, isVoidVaultEnabled, isSitting, hasFinishedAnyDd2Event, isPettingAnimal, isTheAnimalBeingPetSmall, potionOfReturn, tryKeepingHoveringDown) {
  return ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, BitFlags$TerrariaPacket.toByte(BitFlags$TerrariaPacket.fromFlags(tryKeepingHoveringUp, isVoidVaultEnabled, isSitting, hasFinishedAnyDd2Event, isPettingAnimal, isTheAnimalBeingPetSmall, potionOfReturn !== undefined, tryKeepingHoveringDown)), "miscFlags2");
}

function packMiscFlags3(writer, isSleeping) {
  return ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, BitFlags$TerrariaPacket.toByte(BitFlags$TerrariaPacket.fromFlags(isSleeping, false, false, false, false, false, false, false)), "miscFlags3");
}

function packVelocity(writer, velocity) {
  if (velocity !== undefined) {
    return ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(writer, velocity.x, "velocityX"), velocity.y, "velocityY");
  } else {
    return writer;
  }
}

function packPotionOfReturn(writer, potionOfReturn) {
  if (potionOfReturn !== undefined) {
    return ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(writer, potionOfReturn.originalUsePosition.x, "potionOfReturnOrigX"), potionOfReturn.originalUsePosition.y, "potionOfReturnOrigY"), potionOfReturn.homePosition.x, "potionOfReturnHomeX"), potionOfReturn.homePosition.y, "potionOfReturnHomeY");
  } else {
    return writer;
  }
}

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(packPotionOfReturn(packVelocity(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packByte(packMiscFlags3(packMiscFlags2(packMiscFlags1(packControlFlags(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("PlayerUpdate")), self.playerId, "playerId"), self.control, self.direction), self.pulleyDirection, self.velocity, self.vortexStealthActive, self.gravityDirection, self.shouldGuard, self.ghost), self.tryKeepingHoveringUp, self.isVoidVaultEnabled, self.isSitting, self.hasFinishedAnyDd2Event, self.isPettingAnimal, self.isTheAnimalBeingPetSmall, self.potionOfReturn, self.tryKeepingHoveringDown), self.isSleeping), self.selectedItem, "selectedItem"), self.position.x, "positionX"), self.position.y, "positionY"), self.velocity), self.potionOfReturn));
}

exports.parse = parse;
exports.toBuffer = toBuffer;
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
