// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as BitFlags$TerrariaPacket from "../BitFlags.js";
import * as PacketType$TerrariaPacket from "../PacketType.js";
import * as ErrorAwarePacketReader$TerrariaPacket from "../ErrorAwarePacketReader.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";
import Packetreader from "@popstarfreas/packetfactory/packetreader";

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "flags");
  if (e.TAG !== "Ok") {
    return e;
  }
  let flags = BitFlags$TerrariaPacket.fromByte(e._0);
  let getPositionFromTarget = BitFlags$TerrariaPacket.flag3(flags);
  let match = BitFlags$TerrariaPacket.flag1(flags);
  let match$1 = BitFlags$TerrariaPacket.flag2(flags);
  let teleportType = match ? (
      match$1 ? "TeleportAck" : "Npc"
    ) : (
      match$1 ? "PlayerToPlayer" : "Player"
    );
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "targetId");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "x");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "y");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let e$4 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "style");
  if (e$4.TAG !== "Ok") {
    return e$4;
  }
  let e$5 = BitFlags$TerrariaPacket.flag4(flags) ? Stdlib_Result.map(ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "extraInfo"), v => v) : ({
      TAG: "Ok",
      _0: undefined
    });
  if (e$5.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        teleportType: teleportType,
        getPositionFromTarget: getPositionFromTarget,
        targetId: e$1._0,
        x: e$2._0,
        y: e$3._0,
        style: e$4._0,
        extraInfo: e$5._0
      }
    };
  } else {
    return e$5;
  }
}

let Decode = {
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  readInt16: ErrorAwarePacketReader$TerrariaPacket.readInt16,
  readSingle: ErrorAwarePacketReader$TerrariaPacket.readSingle,
  readInt32: ErrorAwarePacketReader$TerrariaPacket.readInt32,
  parse: parse
};

function getFlags(self) {
  return BitFlags$TerrariaPacket.toByte(BitFlags$TerrariaPacket.fromFlags(self.teleportType === "Npc" || self.teleportType === "TeleportAck", self.teleportType === "PlayerToPlayer" || self.teleportType === "TeleportAck", self.getPositionFromTarget, Stdlib_Option.isSome(self.extraInfo), false, false, false, false));
}

function toBuffer(self) {
  let writer = ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("Teleport")), getFlags(self), "flags"), self.targetId, "targetId"), self.x, "x"), self.y, "y"), self.style, "style");
  let extraInfo = self.extraInfo;
  return ErrorAwarePacketWriter$TerrariaPacket.data(extraInfo !== undefined ? ErrorAwarePacketWriter$TerrariaPacket.packInt32(writer, extraInfo, "extraInfo") : writer);
}

let Encode = {
  packByte: ErrorAwarePacketWriter$TerrariaPacket.packByte,
  packInt16: ErrorAwarePacketWriter$TerrariaPacket.packInt16,
  packSingle: ErrorAwarePacketWriter$TerrariaPacket.packSingle,
  packInt32: ErrorAwarePacketWriter$TerrariaPacket.packInt32,
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  getFlags: getFlags,
  toBuffer: toBuffer
};

export {
  Decode,
  Encode,
  parse,
  toBuffer,
}
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
