// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketType$TerrariaPacket from "../PacketType.js";
import * as PacketReader$PacketFactory from "@popstarfreas/packetfactory/src/PacketReader.js";
import * as ManagedPacketWriter$PacketFactory from "@popstarfreas/packetfactory/src/ManagedPacketWriter.js";
import * as ErrorAwarePacketReader$TerrariaPacket from "../ErrorAwarePacketReader.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";

function parse(payload) {
  let reader = PacketReader$PacketFactory.make(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "timeLeftBetweenWaves");
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        timeLeftBetweenWaves: e._0
      }
    };
  } else {
    return e;
  }
}

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packInt32(ErrorAwarePacketWriter$TerrariaPacket.setType(ManagedPacketWriter$PacketFactory.make(), PacketType$TerrariaPacket.toInt("CrystalInvasionSendWaitTime")), self.timeLeftBetweenWaves, "timeLeftBetweenWaves"));
}

export {
  parse,
  toBuffer,
}
/* PacketReader-PacketFactory Not a pure module */
