// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../ErrorAwarePacketReader.js");
let ErrorAwarePacketWriter$TerrariaPacket = require("../ErrorAwarePacketWriter.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;

function fromInt(action) {
  switch (action) {
    case 0 :
      return "KillTile";
    case 1 :
      return "PlaceTile";
    case 2 :
      return "KillWall";
    case 3 :
      return "PlaceWall";
    case 4 :
      return "KillTileNoItem";
    case 5 :
      return "PlaceWire";
    case 6 :
      return "KillWire";
    case 7 :
      return "PoundTile";
    case 8 :
      return "PlaceActuator";
    case 9 :
      return "KillActuator";
    case 10 :
      return "PlaceWire2";
    case 11 :
      return "KillWire2";
    case 12 :
      return "PlaceWire3";
    case 13 :
      return "KillWire3";
    case 14 :
      return "SlopeTile";
    case 15 :
      return "FrameTrack";
    case 16 :
      return "PlaceWire4";
    case 17 :
      return "KillWire4";
    case 18 :
      return "PokeLogicGate";
    case 19 :
      return "Actuate";
    case 20 :
      return "KillTile2";
    case 21 :
      return "ReplaceTile";
    case 22 :
      return "ReplaceWall";
    case 23 :
      return "SlopePoundTile";
    default:
      return;
  }
}

function toInt(action) {
  switch (action) {
    case "KillTile" :
      return 0;
    case "PlaceTile" :
      return 1;
    case "KillWall" :
      return 2;
    case "PlaceWall" :
      return 3;
    case "KillTileNoItem" :
      return 4;
    case "PlaceWire" :
      return 5;
    case "KillWire" :
      return 6;
    case "PoundTile" :
      return 7;
    case "PlaceActuator" :
      return 8;
    case "KillActuator" :
      return 9;
    case "PlaceWire2" :
      return 10;
    case "KillWire2" :
      return 11;
    case "PlaceWire3" :
      return 12;
    case "KillWire3" :
      return 13;
    case "SlopeTile" :
      return 14;
    case "FrameTrack" :
      return 15;
    case "PlaceWire4" :
      return 16;
    case "KillWire4" :
      return 17;
    case "PokeLogicGate" :
      return 18;
    case "Actuate" :
      return 19;
    case "KillTile2" :
      return 20;
    case "ReplaceTile" :
      return 21;
    case "ReplaceWall" :
      return 22;
    case "SlopePoundTile" :
      return 23;
  }
}

let Action = {
  fromInt: fromInt,
  toInt: toInt
};

function makeError(_message) {
  return (new Error(_message));
}

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "action");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "tileX");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "tileY");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "value1");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let e$4 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "value2");
  if (e$4.TAG !== "Ok") {
    return e$4;
  }
  let action = fromInt(e._0);
  let action$1 = action !== undefined ? ({
      TAG: "Ok",
      _0: action
    }) : ({
      TAG: "Error",
      _0: {
        context: "TileModify.parse.action",
        error: makeError("Unknown action")
      }
    });
  if (action$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        action: action$1._0,
        tileX: e$1._0,
        tileY: e$2._0,
        value1: e$3._0,
        value2: e$4._0
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: action$1._0
    };
  }
}

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("TileModify")), toInt(self.action), "action"), self.tileX, "tileX"), self.tileY, "tileY"), self.value1, "value1"), self.value2, "value2"));
}

exports.Action = Action;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
