// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketType$TerrariaPacket from "../PacketType.mjs";
import * as ManagedPacketWriter$PacketFactory from "@popstarfreas/packetfactory/src/ManagedPacketWriter.mjs";
import Packetreader from "@popstarfreas/packetfactory/packetreader";
import Packetwriter from "@popstarfreas/packetfactory/packetwriter";

function parse(payload) {
  var reader = new Packetreader(payload);
  var playerId = reader.readByte();
  var mana = reader.readInt16();
  var maxMana = reader.readInt16();
  return {
          playerId: playerId,
          mana: mana,
          maxMana: maxMana
        };
}

function toBuffer(self) {
  return ManagedPacketWriter$PacketFactory.setType(new Packetwriter(), PacketType$TerrariaPacket.toInt("PlayerMana")).packByte(self.playerId).packInt16(self.mana).packInt16(self.maxMana).data;
}

export {
  parse ,
  toBuffer ,
}
/* @popstarfreas/packetfactory/packetreader Not a pure module */
