// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Stdlib_Option = require("@rescript/runtime/lib/js/Stdlib_Option.js");
let PacketType$TerrariaPacket = require("../PacketType.js");
let ManagedPacketWriter$PacketFactory = require("@popstarfreas/packetfactory/src/ManagedPacketWriter.js");
let Packet_ItemDropUpdate$TerrariaPacket = require("./Packet_ItemDropUpdate.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;
let Packetwriter = require("@popstarfreas/packetfactory/packetwriter").default;

function readByte(prim) {
  return prim.readByte();
}

function readSingle(prim) {
  return prim.readSingle();
}

function readBytes(prim0, prim1) {
  return prim0.readBytes(prim1);
}

function parse(payload) {
  return Stdlib_Option.map(Packet_ItemDropUpdate$TerrariaPacket.parse(payload), itemDropUpdate => {
    let reader = new Packetreader(payload);
    reader.readBytes(24);
    let timeLeftInWhichTheItemCannotBeTakenByEnemies = reader.readByte();
    return {
      itemDropId: itemDropUpdate.itemDropId,
      x: itemDropUpdate.x,
      y: itemDropUpdate.y,
      vx: itemDropUpdate.vx,
      vy: itemDropUpdate.vy,
      stack: itemDropUpdate.stack,
      prefix: itemDropUpdate.prefix,
      noDelay: itemDropUpdate.noDelay,
      itemId: itemDropUpdate.itemId,
      timeLeftInWhichTheItemCannotBeTakenByEnemies: timeLeftInWhichTheItemCannotBeTakenByEnemies
    };
  });
}

let Decode = {
  readByte: readByte,
  readSingle: readSingle,
  readBytes: readBytes,
  parse: parse
};

function packByte(prim0, prim1) {
  return prim0.packByte(prim1);
}

function packInt16(prim0, prim1) {
  return prim0.packInt16(prim1);
}

function packInt32(prim0, prim1) {
  return prim0.packInt32(prim1);
}

function packSingle(prim0, prim1) {
  return prim0.packSingle(prim1);
}

function data(prim) {
  return prim.data;
}

function toBuffer(self) {
  return ManagedPacketWriter$PacketFactory.setType(new Packetwriter(), PacketType$TerrariaPacket.toInt("ItemDropProtectedUpdate")).packInt16(self.itemDropId).packSingle(self.x).packSingle(self.y).packSingle(self.vx).packSingle(self.vy).packInt16(self.stack).packByte(self.prefix).packByte(self.noDelay).packInt16(self.itemId).packByte(self.timeLeftInWhichTheItemCannotBeTakenByEnemies).data;
}

let Encode = {
  Writer: undefined,
  packByte: packByte,
  packInt16: packInt16,
  packInt32: packInt32,
  packSingle: packSingle,
  setType: ManagedPacketWriter$PacketFactory.setType,
  data: data,
  toBuffer: toBuffer
};

exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* Packet_ItemDropUpdate-TerrariaPacket Not a pure module */
