// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var PacketType$TerrariaPacket = require("../PacketType.js");
var ManagedPacketWriter$PacketFactory = require("@popstarfreas/packetfactory/src/ManagedPacketWriter.js");
var Packetreader = require("@popstarfreas/packetfactory/packetreader").default;
var Packetwriter = require("@popstarfreas/packetfactory/packetwriter").default;

function toInt(action) {
  switch (action) {
    case "PlaceChest" :
        return 0;
    case "KillChest" :
        return 1;
    case "PlaceDresser" :
        return 2;
    case "KillDresser" :
        return 3;
    case "PlaceContainer" :
        return 4;
    case "KillContainer" :
        return 5;
    
  }
}

function fromInt(action) {
  switch (action) {
    case 0 :
        return "PlaceChest";
    case 1 :
        return "KillChest";
    case 2 :
        return "PlaceDresser";
    case 3 :
        return "KillDresser";
    case 4 :
        return "PlaceContainer";
    case 5 :
        return "KillContainer";
    default:
      return ;
  }
}

function toString(action) {
  switch (action) {
    case "PlaceChest" :
        return "PlaceChest";
    case "KillChest" :
        return "KillChest";
    case "PlaceDresser" :
        return "PlaceDresser";
    case "KillDresser" :
        return "KillDresser";
    case "PlaceContainer" :
        return "PlaceContainer";
    case "KillContainer" :
        return "KillContainer";
    
  }
}

var Action = {
  toInt: toInt,
  fromInt: fromInt,
  toString: toString
};

function parse(payload) {
  var reader = new Packetreader(payload);
  var action = fromInt(reader.readByte());
  var x = reader.readInt16();
  var y = reader.readInt16();
  var style = reader.readInt16();
  var id = reader.readInt16();
  if (action !== undefined) {
    return {
            action: action,
            x: x,
            y: y,
            style: style,
            id: id
          };
  }
  
}

function packAction(writer, action) {
  var $$byte;
  switch (action) {
    case "PlaceChest" :
        $$byte = 0;
        break;
    case "KillChest" :
        $$byte = 1;
        break;
    case "PlaceDresser" :
        $$byte = 2;
        break;
    case "KillDresser" :
        $$byte = 3;
        break;
    case "PlaceContainer" :
        $$byte = 4;
        break;
    case "KillContainer" :
        $$byte = 5;
        break;
    
  }
  return writer.packByte($$byte);
}

function toBuffer(self) {
  return packAction(ManagedPacketWriter$PacketFactory.setType(new Packetwriter(), PacketType$TerrariaPacket.toInt("ChestPlace")), self.action).packInt16(self.x).packInt16(self.y).packInt16(self.style).packInt16(self.id).data;
}

exports.Action = Action;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* @popstarfreas/packetfactory/packetreader Not a pure module */
