// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodezlib from "node:zlib";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";
import * as BitFlags$TerrariaPacket from "../BitFlags.js";
import * as TileSolid$TerrariaPacket from "../TileSolid.js";
import * as PacketType$TerrariaPacket from "../PacketType.js";
import * as TileFrameImportant$TerrariaPacket from "../TileFrameImportant.js";
import * as ErrorAwareBufferReader$TerrariaPacket from "../ErrorAwareBufferReader.js";
import * as ErrorAwareBufferWriter$TerrariaPacket from "../ErrorAwareBufferWriter.js";
import * as ErrorAwarePacketReader$TerrariaPacket from "../ErrorAwarePacketReader.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";
import Bufferreader from "@popstarfreas/packetfactory/bufferreader";
import Packetreader from "@popstarfreas/packetfactory/packetreader";
import * as PacketV1449_TileSectionSend$TerrariaPacket from "../packetv1449/PacketV1449_TileSectionSend.js";

function parseTrainingDummyKind(reader) {
  let e = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "npcSlotId");
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        npcSlotId: e._0
      }
    };
  } else {
    return e;
  }
}

function parseDisplayItem(reader) {
  let e = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "netId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "prefix");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "stack");
  if (e$2.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        netId: e._0,
        prefix: e$1._0,
        stack: e$2._0
      }
    };
  } else {
    return e$2;
  }
}

function parseLogicSensorKind(reader) {
  let e = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "checkType");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "on");
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        checkType: e._0,
        on: e$1._0 === 1
      }
    };
  } else {
    return e$1;
  }
}

function parseDisplayDollKind(reader) {
  let e = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "itemsFlags");
  if (e.TAG !== "Ok") {
    return e;
  }
  let itemsFlags = BitFlags$TerrariaPacket.fromByte(e._0);
  let e$1 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "dyeFlags");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let dyeFlags = BitFlags$TerrariaPacket.fromByte(e$1._0);
  let e$2 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "pose");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "extraFlags");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let extraFlags = BitFlags$TerrariaPacket.fromByte(e$3._0);
  let items = [];
  let dyes = [];
  let misc = [];
  let parseResult = {
    TAG: "Ok",
    _0: undefined
  };
  for (let i = 0; i <= 7; ++i) {
    let match = parseResult;
    if (match.TAG === "Ok") {
      if (BitFlags$TerrariaPacket.flagN(itemsFlags, (1 << i))) {
        let item = parseDisplayItem(reader);
        if (item.TAG === "Ok") {
          items.push(item._0);
        } else {
          parseResult = {
            TAG: "Error",
            _0: item._0
          };
        }
      } else {
        items.push(undefined);
      }
    }
  }
  let match$1 = parseResult;
  if (match$1.TAG === "Ok") {
    if (BitFlags$TerrariaPacket.flag2(extraFlags)) {
      let item$1 = parseDisplayItem(reader);
      if (item$1.TAG === "Ok") {
        items.push(item$1._0);
      } else {
        parseResult = {
          TAG: "Error",
          _0: item$1._0
        };
      }
    } else {
      items.push(undefined);
    }
  }
  for (let i$1 = 0; i$1 <= 7; ++i$1) {
    let match$2 = parseResult;
    if (match$2.TAG === "Ok") {
      if (BitFlags$TerrariaPacket.flagN(dyeFlags, (1 << i$1))) {
        let item$2 = parseDisplayItem(reader);
        if (item$2.TAG === "Ok") {
          dyes.push(item$2._0);
        } else {
          parseResult = {
            TAG: "Error",
            _0: item$2._0
          };
        }
      } else {
        dyes.push(undefined);
      }
    }
  }
  let match$3 = parseResult;
  if (match$3.TAG === "Ok") {
    if (BitFlags$TerrariaPacket.flag3(extraFlags)) {
      let item$3 = parseDisplayItem(reader);
      if (item$3.TAG === "Ok") {
        dyes.push(item$3._0);
      } else {
        parseResult = {
          TAG: "Error",
          _0: item$3._0
        };
      }
    } else {
      dyes.push(undefined);
    }
  }
  let match$4 = parseResult;
  if (match$4.TAG === "Ok") {
    if (BitFlags$TerrariaPacket.flag1(extraFlags)) {
      let item$4 = parseDisplayItem(reader);
      if (item$4.TAG === "Ok") {
        misc.push(item$4._0);
      } else {
        parseResult = {
          TAG: "Error",
          _0: item$4._0
        };
      }
    } else {
      misc.push(undefined);
    }
  }
  let err = parseResult;
  if (err.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        items: items,
        dyes: dyes,
        misc: misc,
        pose: e$2._0
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: err._0
    };
  }
}

function parseHatRackKind(reader) {
  let e = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "flags");
  if (e.TAG !== "Ok") {
    return e;
  }
  let flags = BitFlags$TerrariaPacket.fromByte(e._0);
  let items = [];
  let dyes = [];
  let parseResult = {
    TAG: "Ok",
    _0: undefined
  };
  for (let i = 0; i <= 1; ++i) {
    let match = parseResult;
    if (match.TAG === "Ok") {
      if (BitFlags$TerrariaPacket.flagN(flags, (1 << i))) {
        let item = parseDisplayItem(reader);
        if (item.TAG === "Ok") {
          items.push(item._0);
        } else {
          parseResult = {
            TAG: "Error",
            _0: item._0
          };
        }
      } else {
        items.push(undefined);
      }
    }
  }
  for (let i$1 = 0; i$1 <= 1; ++i$1) {
    let match$1 = parseResult;
    if (match$1.TAG === "Ok") {
      if (BitFlags$TerrariaPacket.flagN(flags, (1 << (i$1 + 2 | 0)))) {
        let item$1 = parseDisplayItem(reader);
        if (item$1.TAG === "Ok") {
          dyes.push(item$1._0);
        } else {
          parseResult = {
            TAG: "Error",
            _0: item$1._0
          };
        }
      } else {
        dyes.push(undefined);
      }
    }
  }
  let err = parseResult;
  if (err.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        items: items,
        dyes: dyes
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: err._0
    };
  }
}

function parseLeashedEntityAnchorKind(reader) {
  let e = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "itemType");
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        itemType: e._0
      }
    };
  } else {
    return e;
  }
}

function parseEntityKind(entityType, reader) {
  switch (entityType) {
    case 0 :
      return Stdlib_Result.map(parseTrainingDummyKind(reader), v => ({
        TAG: "TrainingDummy",
        _0: v
      }));
    case 1 :
      return Stdlib_Result.map(parseDisplayItem(reader), v => ({
        TAG: "ItemFrame",
        _0: v
      }));
    case 2 :
      return Stdlib_Result.map(parseLogicSensorKind(reader), v => ({
        TAG: "LogicSensor",
        _0: v
      }));
    case 3 :
      return Stdlib_Result.map(parseDisplayDollKind(reader), v => ({
        TAG: "DisplayDoll",
        _0: v
      }));
    case 4 :
      return Stdlib_Result.map(parseDisplayItem(reader), v => ({
        TAG: "WeaponsRack",
        _0: v
      }));
    case 5 :
      return Stdlib_Result.map(parseHatRackKind(reader), v => ({
        TAG: "HatRack",
        _0: v
      }));
    case 6 :
      return Stdlib_Result.map(parseDisplayItem(reader), v => ({
        TAG: "FoodPlatter",
        _0: v
      }));
    case 7 :
      return {
        TAG: "Ok",
        _0: {
          TAG: "TeleportationPylon",
          _0: undefined
        }
      };
    case 8 :
      return Stdlib_Result.map(parseDisplayItem(reader), v => ({
        TAG: "DeadCellsDisplayJar",
        _0: v
      }));
    case 9 :
      return Stdlib_Result.map(parseLeashedEntityAnchorKind(reader), v => ({
        TAG: "KiteAnchor",
        _0: v
      }));
    case 10 :
      return Stdlib_Result.map(parseLeashedEntityAnchorKind(reader), v => ({
        TAG: "CritterAnchor",
        _0: v
      }));
    default:
      return {
        TAG: "Error",
        _0: {
          context: "Entity.parse",
          error: new Error("Unknown entity kind: " + entityType.toString())
        }
      };
  }
}

function parse(reader) {
  let e = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "entityType");
  if (e.TAG !== "Ok") {
    return e;
  }
  let entityType = e._0;
  let e$1 = ErrorAwareBufferReader$TerrariaPacket.readInt32(reader, "id");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "x");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "y");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let e$4 = parseEntityKind(entityType, reader);
  if (e$4.TAG !== "Ok") {
    return e$4;
  }
  let entity_id = e$1._0;
  let entity_x = e$2._0;
  let entity_y = e$3._0;
  let entity_entityKind = e$4._0;
  let entity = {
    entityType: entityType,
    id: entity_id,
    x: entity_x,
    y: entity_y,
    entityKind: entity_entityKind
  };
  return {
    TAG: "Ok",
    _0: entity
  };
}

function packDisplayItem(writer, displayItem) {
  return ErrorAwareBufferWriter$TerrariaPacket.packInt16(ErrorAwareBufferWriter$TerrariaPacket.packByte(ErrorAwareBufferWriter$TerrariaPacket.packInt16(writer, displayItem.netId, "netId"), displayItem.prefix, "prefix"), displayItem.stack, "stack");
}

function hasItem(arr, n) {
  return Stdlib_Option.isSome(Stdlib_Option.flatMap(arr[n], a => a));
}

function pack(writer, entity) {
  let writer$1 = ErrorAwareBufferWriter$TerrariaPacket.packInt16(ErrorAwareBufferWriter$TerrariaPacket.packInt16(ErrorAwareBufferWriter$TerrariaPacket.packInt32(ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, entity.entityType, "entityType"), entity.id, "id"), entity.x, "x"), entity.y, "y");
  let entityKind = entity.entityKind;
  switch (entityKind.TAG) {
    case "DisplayDoll" :
      let displayDollKind = entityKind._0;
      let itemFlags = BitFlags$TerrariaPacket.fromFlags(hasItem(displayDollKind.items, 0), hasItem(displayDollKind.items, 1), hasItem(displayDollKind.items, 2), hasItem(displayDollKind.items, 3), hasItem(displayDollKind.items, 4), hasItem(displayDollKind.items, 5), hasItem(displayDollKind.items, 6), hasItem(displayDollKind.items, 7));
      let dyeFlags = BitFlags$TerrariaPacket.fromFlags(hasItem(displayDollKind.dyes, 0), hasItem(displayDollKind.dyes, 1), hasItem(displayDollKind.dyes, 2), hasItem(displayDollKind.dyes, 3), hasItem(displayDollKind.dyes, 4), hasItem(displayDollKind.dyes, 5), hasItem(displayDollKind.dyes, 6), hasItem(displayDollKind.dyes, 7));
      let extraFlags = BitFlags$TerrariaPacket.fromFlags(hasItem(displayDollKind.misc, 0), hasItem(displayDollKind.items, 8), hasItem(displayDollKind.dyes, 8), false, false, false, false, false);
      ErrorAwareBufferWriter$TerrariaPacket.packByte(ErrorAwareBufferWriter$TerrariaPacket.packByte(ErrorAwareBufferWriter$TerrariaPacket.packByte(ErrorAwareBufferWriter$TerrariaPacket.packByte(writer$1, BitFlags$TerrariaPacket.toByte(itemFlags), "itemFlags"), BitFlags$TerrariaPacket.toByte(dyeFlags), "dyeFlags"), displayDollKind.pose, "pose"), BitFlags$TerrariaPacket.toByte(extraFlags), "extraFlags");
      for (let i = 0; i <= 7; ++i) {
        let item = Stdlib_Option.flatMap(displayDollKind.items[i], a => a);
        if (item !== undefined) {
          packDisplayItem(writer$1, item);
        }
      }
      let item$1 = Stdlib_Option.flatMap(displayDollKind.items[8], a => a);
      if (item$1 !== undefined) {
        packDisplayItem(writer$1, item$1);
      }
      for (let i$1 = 0; i$1 <= 7; ++i$1) {
        let item$2 = Stdlib_Option.flatMap(displayDollKind.dyes[i$1], a => a);
        if (item$2 !== undefined) {
          packDisplayItem(writer$1, item$2);
        }
      }
      let item$3 = Stdlib_Option.flatMap(displayDollKind.dyes[8], a => a);
      if (item$3 !== undefined) {
        packDisplayItem(writer$1, item$3);
      }
      let item$4 = Stdlib_Option.flatMap(displayDollKind.misc[0], a => a);
      if (item$4 !== undefined) {
        packDisplayItem(writer$1, item$4);
      }
      return writer$1;
    case "HatRack" :
      let hatRackKind = entityKind._0;
      let flags = BitFlags$TerrariaPacket.fromFlags(hasItem(hatRackKind.items, 0), hasItem(hatRackKind.items, 1), hasItem(hatRackKind.dyes, 0), hasItem(hatRackKind.dyes, 1), false, false, false, false);
      ErrorAwareBufferWriter$TerrariaPacket.packByte(writer$1, BitFlags$TerrariaPacket.toByte(flags), "flags");
      for (let i$2 = 0; i$2 <= 1; ++i$2) {
        let item$5 = Stdlib_Option.flatMap(hatRackKind.items[i$2], a => a);
        if (item$5 !== undefined) {
          packDisplayItem(writer$1, item$5);
        }
      }
      for (let i$3 = 0; i$3 <= 1; ++i$3) {
        let item$6 = Stdlib_Option.flatMap(hatRackKind.dyes[i$3], a => a);
        if (item$6 !== undefined) {
          packDisplayItem(writer$1, item$6);
        }
      }
      return writer$1;
    case "LogicSensor" :
      let logicSensorKind = entityKind._0;
      return ErrorAwareBufferWriter$TerrariaPacket.packByte(ErrorAwareBufferWriter$TerrariaPacket.packByte(writer$1, logicSensorKind.checkType, "checkType"), logicSensorKind.on ? 1 : 0, "on");
    case "TeleportationPylon" :
      return writer$1;
    case "TrainingDummy" :
      let trainingDummy = entityKind._0;
      return ErrorAwareBufferWriter$TerrariaPacket.packInt16(writer$1, trainingDummy.npcSlotId, "npcSlotId");
    case "FoodPlatter" :
    case "ItemFrame" :
    case "WeaponsRack" :
    case "DeadCellsDisplayJar" :
      return packDisplayItem(writer$1, entityKind._0);
    case "KiteAnchor" :
    case "CritterAnchor" :
      let leashedEntityAnchor = entityKind._0;
      return ErrorAwareBufferWriter$TerrariaPacket.packInt16(writer$1, leashedEntityAnchor.itemType, "itemType");
  }
}

function isTheSameAs(self, compTile) {
  let sameHeaders = Stdlib_Option.isSome(self.activeTile) === Stdlib_Option.isSome(compTile.activeTile) && self.inActive === compTile.inActive && self.wire === compTile.wire && self.wire2 === compTile.wire2 && self.wire3 === compTile.wire3 && self.halfBrick === compTile.halfBrick && Primitive_object.equal(self.slope, compTile.slope) && self.actuator === compTile.actuator && Primitive_object.equal(self.color, compTile.color);
  if (!sameHeaders) {
    return false;
  }
  let match = self.activeTile;
  let match$1 = compTile.activeTile;
  let activeMatches = match !== undefined ? (
      match$1 !== undefined && match.tileType === match$1.tileType ? (
          TileFrameImportant$TerrariaPacket.isImportant(match.tileType) ? Primitive_object.equal(match.frame, match$1.frame) : true
        ) : false
    ) : match$1 === undefined;
  if (!activeMatches) {
    return false;
  }
  if (Primitive_object.notequal(self.wall, compTile.wall) || Primitive_object.notequal(self.liquid, compTile.liquid)) {
    return false;
  }
  let sameWallColor = Primitive_object.equal(self.wallColor, compTile.wallColor);
  let sameWire4 = self.wire4 === compTile.wire4;
  let match$2 = compTile.liquid;
  let liquidMatches = match$2 !== undefined ? sameWallColor && sameWire4 && self.lava === compTile.lava && self.honey === compTile.honey && self.shimmer === compTile.shimmer : sameWallColor && sameWire4;
  if (!liquidMatches || self.invisibleBlock !== compTile.invisibleBlock || self.invisibleWall !== compTile.invisibleWall || self.fullbrightBlock !== compTile.fullbrightBlock) {
    return false;
  } else {
    return self.fullbrightWall === compTile.fullbrightWall;
  }
}

function clearTileCache(tile) {
  tile.activeTile = undefined;
  tile.color = undefined;
  tile.wallColor = undefined;
  tile.wall = undefined;
  tile.liquid = undefined;
  tile.lava = false;
  tile.honey = false;
  tile.shimmer = false;
  tile.wire = false;
  tile.wire2 = false;
  tile.wire3 = false;
  tile.wire4 = false;
  tile.halfBrick = false;
  tile.slope = undefined;
  tile.actuator = false;
  tile.inActive = false;
  tile.invisibleBlock = false;
  tile.invisibleWall = false;
  tile.fullbrightBlock = false;
  tile.fullbrightWall = false;
  tile.coatHeader = 0;
}

function readRepeated(count, parseItem) {
  let items = [];
  let parseResult = {
    TAG: "Ok",
    _0: undefined
  };
  for (let _i = 0; _i < count; ++_i) {
    let match = parseResult;
    if (match.TAG === "Ok") {
      let item = parseItem();
      if (item.TAG === "Ok") {
        items.push(item._0);
      } else {
        parseResult = {
          TAG: "Error",
          _0: item._0
        };
      }
    }
  }
  let err = parseResult;
  if (err.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: items
    };
  } else {
    return {
      TAG: "Error",
      _0: err._0
    };
  }
}

function parse$1(payload) {
  let packetReader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.getBytesLeft(packetReader);
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readBuffer(packetReader, e._0, "deflatedPayload");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let inflated;
  try {
    inflated = {
      TAG: "Ok",
      _0: Nodezlib.inflateRawSync(e$1._0)
    };
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      inflated = {
        TAG: "Error",
        _0: {
          context: "inflateRawSync",
          error: obj._1
        }
      };
    } else {
      throw obj;
    }
  }
  if (inflated.TAG !== "Ok") {
    return inflated;
  }
  let reader = new Bufferreader(inflated._0);
  let e$2 = ErrorAwareBufferReader$TerrariaPacket.readInt32(reader, "tileX");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwareBufferReader$TerrariaPacket.readInt32(reader, "tileY");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let e$4 = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "width");
  if (e$4.TAG !== "Ok") {
    return e$4;
  }
  let width = e$4._0;
  let e$5 = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "height");
  if (e$5.TAG !== "Ok") {
    return e$5;
  }
  let height = e$5._0;
  let tiles = [];
  let tileCache = PacketV1449_TileSectionSend$TerrariaPacket.defaultTileCache();
  let rleCount = {
    contents: 0
  };
  if (height < 0 || width < 0) {
    return {
      TAG: "Error",
      _0: {
        context: "Packet_TileSectionSend.parse",
        error: new Error("Tile section dimensions must be non-negative")
      }
    };
  }
  let parseResult = {
    TAG: "Ok",
    _0: undefined
  };
  let readTile = () => {
    clearTileCache(tileCache);
    let e = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "header5");
    if (e.TAG !== "Ok") {
      return e;
    }
    let header5 = BitFlags$TerrariaPacket.fromByte(e._0);
    let e$1;
    if (BitFlags$TerrariaPacket.flag1(header5)) {
      let e$2 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "header4_conditional");
      if (e$2.TAG === "Ok") {
        let header4 = BitFlags$TerrariaPacket.fromByte(e$2._0);
        let e$3;
        if (BitFlags$TerrariaPacket.flag1(header4)) {
          let e$4 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "header3_conditional");
          if (e$4.TAG === "Ok") {
            let header3 = BitFlags$TerrariaPacket.fromByte(e$4._0);
            let e$5 = BitFlags$TerrariaPacket.flag1(header3) ? ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "header2_conditional") : ({
                TAG: "Ok",
                _0: 0
              });
            e$3 = e$5.TAG === "Ok" ? ({
                TAG: "Ok",
                _0: [
                  header3,
                  e$5._0
                ]
              }) : e$5;
          } else {
            e$3 = e$4;
          }
        } else {
          e$3 = {
            TAG: "Ok",
            _0: [
              BitFlags$TerrariaPacket.fromByte(0),
              0
            ]
          };
        }
        if (e$3.TAG === "Ok") {
          let match = e$3._0;
          e$1 = {
            TAG: "Ok",
            _0: [
              header4,
              match[0],
              match[1]
            ]
          };
        } else {
          e$1 = e$3;
        }
      } else {
        e$1 = e$2;
      }
    } else {
      e$1 = {
        TAG: "Ok",
        _0: [
          BitFlags$TerrariaPacket.fromByte(0),
          BitFlags$TerrariaPacket.fromByte(0),
          0
        ]
      };
    }
    if (e$1.TAG !== "Ok") {
      return e$1;
    }
    let match$1 = e$1._0;
    let header2 = match$1[2];
    let header3$1 = match$1[1];
    let header4$1 = match$1[0];
    tileCache.coatHeader = header2;
    tileCache.invisibleBlock = (header2 & 2) !== 0;
    tileCache.invisibleWall = (header2 & 4) !== 0;
    tileCache.fullbrightBlock = (header2 & 8) !== 0;
    tileCache.fullbrightWall = (header2 & 16) !== 0;
    let oldActive = tileCache.activeTile;
    let e$6;
    if (BitFlags$TerrariaPacket.flag2(header5)) {
      let oldType = Stdlib_Option.mapOr(tileCache.activeTile, 0, active => active.tileType);
      let e$7;
      if (BitFlags$TerrariaPacket.flag6(header5)) {
        let e$8 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "tileType_byte1");
        if (e$8.TAG === "Ok") {
          let e$9 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "tileType_byte2");
          e$7 = e$9.TAG === "Ok" ? ({
              TAG: "Ok",
              _0: (e$9._0 << 8) | e$8._0
            }) : e$9;
        } else {
          e$7 = e$8;
        }
      } else {
        e$7 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "tileType");
      }
      if (e$7.TAG === "Ok") {
        let tileType = e$7._0;
        let e$10;
        if (TileFrameImportant$TerrariaPacket.isImportant(tileType)) {
          let e$11 = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "frameX");
          if (e$11.TAG === "Ok") {
            let e$12 = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "frameY");
            e$10 = e$12.TAG === "Ok" ? ({
                TAG: "Ok",
                _0: {
                  x: e$11._0,
                  y: e$12._0
                }
              }) : e$12;
          } else {
            e$10 = e$11;
          }
        } else {
          e$10 = Stdlib_Option.isSome(oldActive) && tileType === oldType ? ({
              TAG: "Ok",
              _0: oldActive.frame
            }) : ({
              TAG: "Ok",
              _0: undefined
            });
        }
        if (e$10.TAG === "Ok") {
          let e$13;
          if (BitFlags$TerrariaPacket.flag4(header3$1)) {
            let e$14 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "color");
            if (e$14.TAG === "Ok") {
              tileCache.color = e$14._0;
              e$13 = {
                TAG: "Ok",
                _0: undefined
              };
            } else {
              e$13 = e$14;
            }
          } else {
            e$13 = {
              TAG: "Ok",
              _0: undefined
            };
          }
          if (e$13.TAG === "Ok") {
            tileCache.activeTile = {
              tileType: tileType,
              frame: e$10._0
            };
            e$6 = {
              TAG: "Ok",
              _0: undefined
            };
          } else {
            e$6 = e$13;
          }
        } else {
          e$6 = e$10;
        }
      } else {
        e$6 = e$7;
      }
    } else {
      e$6 = {
        TAG: "Ok",
        _0: undefined
      };
    }
    if (e$6.TAG !== "Ok") {
      return e$6;
    }
    let e$15;
    if (BitFlags$TerrariaPacket.flag3(header5)) {
      let e$16 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "wall");
      if (e$16.TAG === "Ok") {
        tileCache.wall = e$16._0;
        if (BitFlags$TerrariaPacket.flag5(header3$1)) {
          let e$17 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "wallColor");
          if (e$17.TAG === "Ok") {
            tileCache.wallColor = e$17._0;
            e$15 = {
              TAG: "Ok",
              _0: undefined
            };
          } else {
            e$15 = e$17;
          }
        } else {
          e$15 = {
            TAG: "Ok",
            _0: undefined
          };
        }
      } else {
        e$15 = e$16;
      }
    } else {
      e$15 = {
        TAG: "Ok",
        _0: undefined
      };
    }
    if (e$15.TAG !== "Ok") {
      return e$15;
    }
    let liquidBits = ((BitFlags$TerrariaPacket.toByte(header5) & 24) >> 3);
    let e$18;
    if (liquidBits !== 0) {
      let e$19 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "liquidValue");
      if (e$19.TAG === "Ok") {
        tileCache.liquid = e$19._0;
        if (BitFlags$TerrariaPacket.flag8(header3$1)) {
          tileCache.shimmer = true;
        } else if (liquidBits > 1) {
          if (liquidBits === 2) {
            tileCache.lava = true;
          } else {
            tileCache.honey = true;
          }
        }
        e$18 = {
          TAG: "Ok",
          _0: undefined
        };
      } else {
        e$18 = e$19;
      }
    } else {
      e$18 = {
        TAG: "Ok",
        _0: undefined
      };
    }
    if (e$18.TAG !== "Ok") {
      return e$18;
    }
    if (BitFlags$TerrariaPacket.toByte(header4$1) > 1) {
      if (BitFlags$TerrariaPacket.flag2(header4$1)) {
        tileCache.wire = true;
      }
      if (BitFlags$TerrariaPacket.flag3(header4$1)) {
        tileCache.wire2 = true;
      }
      if (BitFlags$TerrariaPacket.flag4(header4$1)) {
        tileCache.wire3 = true;
      }
      let slopeBits = ((BitFlags$TerrariaPacket.toByte(header4$1) & 112) >> 4);
      if (slopeBits !== 0 && TileSolid$TerrariaPacket.isSolid(Stdlib_Option.mapOr(tileCache.activeTile, 0, tile => tile.tileType))) {
        if (slopeBits === 1) {
          tileCache.halfBrick = true;
        } else {
          tileCache.slope = slopeBits - 1 | 0;
        }
      }
    }
    let e$20;
    if (BitFlags$TerrariaPacket.toByte(header3$1) > 0) {
      if (BitFlags$TerrariaPacket.flag2(header3$1)) {
        tileCache.actuator = true;
      }
      if (BitFlags$TerrariaPacket.flag3(header3$1)) {
        tileCache.inActive = true;
      }
      if (BitFlags$TerrariaPacket.flag6(header3$1)) {
        tileCache.wire4 = true;
      }
      let e$21;
      if (BitFlags$TerrariaPacket.flag7(header3$1)) {
        let e$22 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "wall_highByte");
        if (e$22.TAG === "Ok") {
          tileCache.wall = (e$22._0 << 8) | tileCache.wall;
          e$21 = {
            TAG: "Ok",
            _0: undefined
          };
        } else {
          e$21 = e$22;
        }
      } else {
        e$21 = {
          TAG: "Ok",
          _0: undefined
        };
      }
      e$20 = e$21.TAG === "Ok" ? ({
          TAG: "Ok",
          _0: undefined
        }) : e$21;
    } else {
      e$20 = {
        TAG: "Ok",
        _0: undefined
      };
    }
    if (e$20.TAG !== "Ok") {
      return e$20;
    }
    let repeatCountBytes = ((BitFlags$TerrariaPacket.toByte(header5) & 192) >> 6);
    let e$23;
    if (repeatCountBytes !== 0) {
      if (repeatCountBytes !== 1) {
        let e$24 = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "rle_int16");
        if (e$24.TAG === "Ok") {
          rleCount.contents = e$24._0;
          e$23 = {
            TAG: "Ok",
            _0: undefined
          };
        } else {
          e$23 = e$24;
        }
      } else {
        let e$25 = ErrorAwareBufferReader$TerrariaPacket.readByte(reader, "rle_byte");
        if (e$25.TAG === "Ok") {
          rleCount.contents = e$25._0;
          e$23 = {
            TAG: "Ok",
            _0: undefined
          };
        } else {
          e$23 = e$25;
        }
      }
    } else {
      rleCount.contents = 0;
      e$23 = {
        TAG: "Ok",
        _0: undefined
      };
    }
    if (e$23.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: PacketV1449_TileSectionSend$TerrariaPacket.cacheToTile(tileCache)
      };
    } else {
      return e$23;
    }
  };
  for (let _y = 0; _y < height; ++_y) {
    let match = parseResult;
    if (match.TAG === "Ok") {
      let row = [];
      for (let _x = 0; _x < width; ++_x) {
        let match$1 = parseResult;
        if (match$1.TAG === "Ok") {
          if (rleCount.contents !== 0) {
            rleCount.contents = rleCount.contents - 1 | 0;
            row.push(PacketV1449_TileSectionSend$TerrariaPacket.cacheToTile(tileCache));
          } else {
            let tile = readTile();
            if (tile.TAG === "Ok") {
              row.push(tile._0);
            } else {
              parseResult = {
                TAG: "Error",
                _0: tile._0
              };
            }
          }
        }
      }
      let match$2 = parseResult;
      if (match$2.TAG === "Ok") {
        tiles.push(row);
      }
    }
  }
  let err = parseResult;
  if (err.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: err._0
    };
  }
  let e$6 = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "chestCount");
  if (e$6.TAG !== "Ok") {
    return e$6;
  }
  let e$7 = readRepeated(e$6._0, () => PacketV1449_TileSectionSend$TerrariaPacket.Chest.parse(reader));
  if (e$7.TAG !== "Ok") {
    return e$7;
  }
  let e$8 = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "signCount");
  if (e$8.TAG !== "Ok") {
    return e$8;
  }
  let e$9 = readRepeated(e$8._0, () => PacketV1449_TileSectionSend$TerrariaPacket.Sign.parse(reader));
  if (e$9.TAG !== "Ok") {
    return e$9;
  }
  let e$10 = ErrorAwareBufferReader$TerrariaPacket.readInt16(reader, "entityCount");
  if (e$10.TAG !== "Ok") {
    return e$10;
  }
  let e$11 = ErrorAwareBufferReader$TerrariaPacket.getBytesLeft(reader);
  if (e$11.TAG !== "Ok") {
    return e$11;
  }
  let e$12 = ErrorAwareBufferReader$TerrariaPacket.readBuffer(reader, e$11._0, "entitiesBuffer");
  if (e$12.TAG !== "Ok") {
    return e$12;
  }
  let entityReader = new Bufferreader(e$12._0);
  let e$13 = readRepeated(e$10._0, () => parse(entityReader));
  if (e$13.TAG !== "Ok") {
    return e$13;
  }
  let e$14 = ErrorAwareBufferReader$TerrariaPacket.getBytesLeft(entityReader);
  if (e$14.TAG !== "Ok") {
    return e$14;
  }
  let e$15 = e$14._0 === 0 ? ({
      TAG: "Ok",
      _0: undefined
    }) : ({
      TAG: "Error",
      _0: {
        context: "Packet_TileSectionSend.entities",
        error: new Error("Unexpected trailing entity bytes")
      }
    });
  if (e$15.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        height: height,
        width: width,
        tileX: e$2._0,
        tileY: e$3._0,
        tiles: tiles,
        chests: e$7._0,
        signs: e$9._0,
        entities: e$13._0
      }
    };
  } else {
    return e$15;
  }
}

function getLiquidBitFlags(tile) {
  let hasLiquid = Stdlib_Option.isSome(tile.liquid);
  let liquidBits = hasLiquid ? (
      tile.shimmer ? "One" : (
          tile.honey ? "Three" : (
              tile.lava ? "Two" : "One"
            )
        )
    ) : "Zero";
  switch (liquidBits) {
    case "Zero" :
      return [
        false,
        false
      ];
    case "One" :
      return [
        false,
        true
      ];
    case "Two" :
      return [
        true,
        false
      ];
    case "Three" :
      return [
        true,
        true
      ];
  }
}

function getSlopeBitFlags(tile) {
  if (tile.halfBrick) {
    return [
      false,
      false,
      true
    ];
  }
  let match = tile.slope;
  if (match === undefined) {
    return [
      false,
      false,
      false
    ];
  }
  switch (match) {
    case 0 :
      return [
        false,
        false,
        true
      ];
    case 1 :
      return [
        false,
        true,
        false
      ];
    case 2 :
      return [
        false,
        true,
        true
      ];
    case 3 :
      return [
        true,
        false,
        false
      ];
    case 4 :
      return [
        true,
        false,
        true
      ];
    case 5 :
      return [
        true,
        true,
        false
      ];
    default:
      return [
        true,
        true,
        true
      ];
  }
}

function getRepeatCountByteLength(repeatCount) {
  if (repeatCount > 255) {
    return 2;
  } else if (repeatCount > 0) {
    return 1;
  } else {
    return 0;
  }
}

function getRepeatCountBitFlags(repeatCount) {
  let repeatCountBytes = getRepeatCountByteLength(repeatCount);
  switch (repeatCountBytes) {
    case 0 :
      return [
        false,
        false
      ];
    case 1 :
      return [
        false,
        true
      ];
    default:
      return [
        true,
        false
      ];
  }
}

function allowsSaveCompressionBatching(tile) {
  let activeTile = tile.activeTile;
  if (activeTile !== undefined) {
    if (activeTile.tileType !== 520) {
      return activeTile.tileType !== 423;
    } else {
      return false;
    }
  } else {
    return true;
  }
}

function packTile(writer, tile, repeatCount) {
  let coatFlags = (((
    tile.invisibleBlock ? 2 : 0
  ) + (
    tile.invisibleWall ? 4 : 0
  ) | 0) + (
    tile.fullbrightBlock ? 8 : 0
  ) | 0) + (
    tile.fullbrightWall ? 16 : 0
  ) | 0;
  let header2 = tile.coatHeader | coatFlags;
  let hasLiquid = Stdlib_Option.isSome(tile.liquid);
  let wall = tile.wall;
  let header3 = BitFlags$TerrariaPacket.fromFlags(header2 > 0, tile.actuator, tile.inActive, Stdlib_Option.isSome(tile.color), Stdlib_Option.isSome(tile.wall) && Stdlib_Option.isSome(tile.wallColor), tile.wire4, wall !== undefined ? wall > 255 : false, tile.shimmer && hasLiquid);
  let match = getSlopeBitFlags(tile);
  let header4 = BitFlags$TerrariaPacket.fromFlags(BitFlags$TerrariaPacket.toByte(header3) > 0, tile.wire, tile.wire2, tile.wire3, match[2], match[1], match[0], false);
  let match$1 = getLiquidBitFlags(tile);
  let match$2 = getRepeatCountBitFlags(repeatCount);
  let activeTile = tile.activeTile;
  let tileFlags = BitFlags$TerrariaPacket.fromFlags(BitFlags$TerrariaPacket.toByte(header4) > 0, Stdlib_Option.isSome(tile.activeTile), Stdlib_Option.isSome(tile.wall), match$1[1], match$1[0], activeTile !== undefined ? activeTile.tileType > 255 : false, match$2[1], match$2[0]);
  ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, BitFlags$TerrariaPacket.toByte(tileFlags), "tileFlags");
  if (BitFlags$TerrariaPacket.flag1(tileFlags)) {
    ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, BitFlags$TerrariaPacket.toByte(header4), "header4");
    if (BitFlags$TerrariaPacket.flag1(header4)) {
      ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, BitFlags$TerrariaPacket.toByte(header3), "header3");
      if (BitFlags$TerrariaPacket.flag1(header3)) {
        ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, header2, "header2");
      }
    }
  }
  let activeTile$1 = tile.activeTile;
  if (activeTile$1 !== undefined) {
    if (BitFlags$TerrariaPacket.flag6(tileFlags)) {
      ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, activeTile$1.tileType & 255, "tileType_lowByte");
      ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, ((activeTile$1.tileType & 65280) >> 8), "tileType_highByte");
    } else {
      ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, activeTile$1.tileType, "tileType");
    }
    let match$3 = activeTile$1.frame;
    if (match$3 !== undefined) {
      ErrorAwareBufferWriter$TerrariaPacket.packInt16(writer, match$3.x, "frameX");
      ErrorAwareBufferWriter$TerrariaPacket.packInt16(writer, match$3.y, "frameY");
    }
    let color = tile.color;
    if (color !== undefined) {
      ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, color, "color");
    }
  }
  let wall$1 = tile.wall;
  if (wall$1 !== undefined) {
    ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, wall$1 & 255, "wall_lowByte");
    let wallColor = tile.wallColor;
    if (wallColor !== undefined) {
      ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, wallColor, "wallColor");
    }
  }
  let liquid = tile.liquid;
  if (liquid !== undefined) {
    ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, liquid, "liquidValue");
  }
  let wall$2 = tile.wall;
  if (wall$2 !== undefined && wall$2 > 255) {
    ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, (wall$2 >> 8), "wall_highByte");
  }
  let match$4 = getRepeatCountByteLength(repeatCount);
  if (match$4 !== 0) {
    if (match$4 !== 1) {
      ErrorAwareBufferWriter$TerrariaPacket.packInt16(writer, repeatCount, "rle_int16");
    } else {
      ErrorAwareBufferWriter$TerrariaPacket.packByte(writer, repeatCount, "rle_byte");
    }
  }
  return writer;
}

function decidePackTile(writer, lastTile, tile) {
  let last = lastTile.contents;
  if (last !== undefined) {
    if (isTheSameAs(tile, last.tile) && allowsSaveCompressionBatching(tile)) {
      last.count = last.count + 1 | 0;
    } else {
      packTile(writer, last.tile, last.count);
      lastTile.contents = {
        tile: tile,
        count: 0
      };
    }
  } else {
    lastTile.contents = {
      tile: tile,
      count: 0
    };
  }
}

function toBuffer(self) {
  let outerPacketWriter = ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("TileSectionSend"));
  let innerWriter = ErrorAwareBufferWriter$TerrariaPacket.make(Buffer.allocUnsafe(64000));
  ErrorAwareBufferWriter$TerrariaPacket.packInt16(ErrorAwareBufferWriter$TerrariaPacket.packInt16(ErrorAwareBufferWriter$TerrariaPacket.packInt32(ErrorAwareBufferWriter$TerrariaPacket.packInt32(innerWriter, self.tileX, "tileX"), self.tileY, "tileY"), self.width, "width"), self.height, "height");
  let lastTile = {
    contents: undefined
  };
  for (let y = 0, y_finish = self.height; y < y_finish; ++y) {
    for (let x = 0, x_finish = self.width; x < x_finish; ++x) {
      let tile = self.tiles[y][x];
      decidePackTile(innerWriter, lastTile, tile);
    }
  }
  let lastTileValue = lastTile.contents;
  if (lastTileValue !== undefined) {
    packTile(innerWriter, lastTileValue.tile, lastTileValue.count);
  }
  ErrorAwareBufferWriter$TerrariaPacket.packInt16(innerWriter, self.chests.length, "chestCount");
  self.chests.forEach(chest => {
    PacketV1449_TileSectionSend$TerrariaPacket.Chest.pack(innerWriter, chest);
  });
  ErrorAwareBufferWriter$TerrariaPacket.packInt16(innerWriter, self.signs.length, "signCount");
  self.signs.forEach(sign => {
    PacketV1449_TileSectionSend$TerrariaPacket.Sign.pack(innerWriter, sign);
  });
  ErrorAwareBufferWriter$TerrariaPacket.packInt16(innerWriter, self.entities.length, "entityCount");
  self.entities.forEach(entity => {
    pack(innerWriter, entity);
  });
  let innerBuffer = ErrorAwareBufferWriter$TerrariaPacket.slicedData(innerWriter);
  if (innerBuffer.TAG === "Ok") {
    let deflatedPayload = Nodezlib.deflateRawSync(innerBuffer._0);
    return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packBuffer(outerPacketWriter, deflatedPayload, "deflatedPayload"));
  }
  let e = innerBuffer._0;
  return {
    TAG: "Error",
    _0: {
      context: "innerWriter; " + e.context,
      error: e.error
    }
  };
}

let Chest;

let Sign;

let Entity = {
  parse: parse,
  pack: pack
};

export {
  Chest,
  Sign,
  Entity,
  parse$1 as parse,
  toBuffer,
}
/* node:zlib Not a pure module */
