// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketType$TerrariaPacket from "../PacketType.js";
import * as ManagedPacketWriter$PacketFactory from "@popstarfreas/packetfactory/src/ManagedPacketWriter.js";
import PacketwriterJs from "@popstarfreas/packetfactory/packetwriter.js";

function parse(_payload) {
  return {
    TAG: "Ok",
    _0: undefined
  };
}

function toBuffer(_self) {
  return {
    TAG: "Ok",
    _0: ManagedPacketWriter$PacketFactory.setType(new PacketwriterJs(), PacketType$TerrariaPacket.toInt("WorldDataRequest")).data
  };
}

export {
  parse,
  toBuffer,
}
/* @popstarfreas/packetfactory/packetwriter.js Not a pure module */
