// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketType$TerrariaPacket from "../PacketType.js";
import * as ErrorAwarePacketReader$TerrariaPacket from "../ErrorAwarePacketReader.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";
import PacketreaderJs from "@popstarfreas/packetfactory/packetreader.js";

function parse(payload) {
  let reader = new PacketreaderJs(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "playerId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "npcId");
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        playerId: e._0,
        npcId: e$1._0
      }
    };
  } else {
    return e$1;
  }
}

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NpcTalk")), self.playerId, "playerId"), self.npcId, "npcId"));
}

export {
  parse,
  toBuffer,
}
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
