// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../ErrorAwarePacketReader.js");
let ErrorAwarePacketWriter$TerrariaPacket = require("../ErrorAwarePacketWriter.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "npcId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readString(reader, "name");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "townNpcVariationIndex");
  if (e$2.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        npcId: e._0,
        name: e$1._0,
        townNpcVariationIndex: e$2._0
      }
    };
  } else {
    return e$2;
  }
}

let Decode = {
  readInt16: ErrorAwarePacketReader$TerrariaPacket.readInt16,
  readString: ErrorAwarePacketReader$TerrariaPacket.readString,
  readInt32: ErrorAwarePacketReader$TerrariaPacket.readInt32,
  parse: parse
};

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packInt32(ErrorAwarePacketWriter$TerrariaPacket.packString(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NpcNameUpdate")), self.npcId, "npcId"), self.name, "name"), self.townNpcVariationIndex, "townNpcVariationIndex"));
}

let Encode = {
  packInt16: ErrorAwarePacketWriter$TerrariaPacket.packInt16,
  packString: ErrorAwarePacketWriter$TerrariaPacket.packString,
  packInt32: ErrorAwarePacketWriter$TerrariaPacket.packInt32,
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  toBuffer: toBuffer
};

exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
