// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Array16$TerrariaPacket = require("../Array16.js");
let BitFlags$TerrariaPacket = require("../BitFlags.js");
let PacketType$TerrariaPacket = require("../PacketType.js");
let ManagedPacketWriter$PacketFactory = require("@popstarfreas/packetfactory/src/ManagedPacketWriter.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../ErrorAwarePacketReader.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;
let Packetwriter = require("@popstarfreas/packetfactory/packetwriter").default;

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "playerId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "loadout");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "hideVisibleAccessory");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let hideVisibleAccessory = e$2._0;
  let flags0 = BitFlags$TerrariaPacket.fromByte(hideVisibleAccessory & 255);
  let flags1 = BitFlags$TerrariaPacket.fromByte((hideVisibleAccessory >> 8) & 255);
  let hideVisibleAccessory$1 = Array16$TerrariaPacket.fromBitFlagsPair(flags0, flags1);
  return {
    TAG: "Ok",
    _0: {
      playerId: e._0,
      loadout: e$1._0,
      hideVisibleAccessory: hideVisibleAccessory$1
    }
  };
}

let Decode = {
  readUInt16: ErrorAwarePacketReader$TerrariaPacket.readUInt16,
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  parse: parse
};

function packUInt16(prim0, prim1) {
  return prim0.packUInt16(prim1);
}

function packByte(prim0, prim1) {
  return prim0.packByte(prim1);
}

function packInt32(prim0, prim1) {
  return prim0.packInt32(prim1);
}

function packSingle(prim0, prim1) {
  return prim0.packSingle(prim1);
}

function data(prim) {
  return prim.data;
}

function toBuffer(self) {
  let match = Array16$TerrariaPacket.toBitFlagsPair(self.hideVisibleAccessory);
  let hideVisibleAccessory = BitFlags$TerrariaPacket.toByte(match[0]) | (BitFlags$TerrariaPacket.toByte(match[1]) << 8);
  return ManagedPacketWriter$PacketFactory.setType(new Packetwriter(), PacketType$TerrariaPacket.toInt("LoadoutSwitch")).packByte(self.playerId).packByte(self.loadout).packUInt16(hideVisibleAccessory).data;
}

let Encode = {
  Writer: undefined,
  packUInt16: packUInt16,
  packByte: packByte,
  packInt32: packInt32,
  packSingle: packSingle,
  setType: ManagedPacketWriter$PacketFactory.setType,
  data: data,
  toBuffer: toBuffer
};

exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* @popstarfreas/packetfactory/packetreader Not a pure module */
