// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../ErrorAwarePacketReader.js");
let ErrorAwarePacketWriter$TerrariaPacket = require("../ErrorAwarePacketWriter.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;

function actionToInt(self) {
  switch (self) {
    case "OpenDoor" :
      return 0;
    case "CloseDoor" :
      return 1;
    case "ShiftTrapdoorOpen" :
      return 2;
    case "ShiftTrapdoorClose" :
      return 3;
    case "ShiftTallGateOpen" :
      return 4;
    case "ShiftTallGateClose" :
      return 5;
  }
}

function actionFromInt(self) {
  switch (self) {
    case 0 :
      return "OpenDoor";
    case 1 :
      return "CloseDoor";
    case 2 :
      return "ShiftTrapdoorOpen";
    case 3 :
      return "ShiftTrapdoorClose";
    case 4 :
      return "ShiftTallGateOpen";
    case 5 :
      return "ShiftTallGateClose";
    default:
      return;
  }
}

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "action");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "x");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "y");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "direction");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let action = actionFromInt(e._0);
  let action$1 = action !== undefined ? ({
      TAG: "Ok",
      _0: action
    }) : ({
      TAG: "Error",
      _0: {
        context: "Packet_DoorUse.parse.action",
        error: new Error("Unknown door action")
      }
    });
  if (action$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        action: action$1._0,
        x: e$1._0,
        y: e$2._0,
        direction: e$3._0 === 0 ? -1 : 1
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: action$1._0
    };
  }
}

let Decode = {
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  readInt16: ErrorAwarePacketReader$TerrariaPacket.readInt16,
  parse: parse
};

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("DoorUse")), actionToInt(self.action), "action"), self.x, "x"), self.y, "y"), self.direction >= 0 ? 1 : 0, "direction"));
}

let Encode = {
  packByte: ErrorAwarePacketWriter$TerrariaPacket.packByte,
  packInt16: ErrorAwarePacketWriter$TerrariaPacket.packInt16,
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  toBuffer: toBuffer
};

exports.actionToInt = actionToInt;
exports.actionFromInt = actionFromInt;
exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
