// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketType$TerrariaPacket from "../PacketType.js";
import * as PacketReader$PacketFactory from "@popstarfreas/packetfactory/src/PacketReader.js";
import * as ErrorAwarePacketReader$TerrariaPacket from "../ErrorAwarePacketReader.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";

function parse(payload) {
  let reader = PacketReader$PacketFactory.make(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readNetworkText(reader, "reason");
  if (e.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        reason: e._0
      }
    };
  } else {
    return e;
  }
}

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packNetworkText(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("Disconnect")), self.reason, "reason"));
}

export {
  parse,
  toBuffer,
}
/* PacketReader-PacketFactory Not a pure module */
