// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var PacketType$negTerrariaPacket = require("../PacketType.js");
var ManagedPacketWriter$negPacketFactory = require("@popstarfreas/packetfactory/src/ManagedPacketWriter.js");
var Packetreader = require("@popstarfreas/packetfactory/packetreader").default;
var Packetwriter = require("@popstarfreas/packetfactory/packetwriter").default;

function parse(payload) {
  var reader = new Packetreader(payload);
  var playerId = reader.readByte();
  var slot = reader.readInt16();
  var stack = reader.readInt16();
  var prefix = reader.readByte();
  var itemId = reader.readInt16();
  return {
          playerId: playerId,
          slot: slot,
          stack: stack,
          prefix: prefix,
          itemId: itemId
        };
}

var Decode = {
  parse: parse
};

function packInt16(prim0, prim1) {
  return prim0.packInt16(prim1);
}

function packByte(prim0, prim1) {
  return prim0.packByte(prim1);
}

function data(prim) {
  return prim.data;
}

function toBuffer(self) {
  return ManagedPacketWriter$negPacketFactory.setType(new Packetwriter(), PacketType$negTerrariaPacket.toInt(/* PlayerInventorySlot */4)).packByte(self.playerId).packInt16(self.slot).packInt16(self.stack).packByte(self.prefix).packInt16(self.itemId).data;
}

var Encode = {
  packInt16: packInt16,
  packByte: packByte,
  setType: ManagedPacketWriter$negPacketFactory.setType,
  data: data,
  toBuffer: toBuffer
};

exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* @popstarfreas/packetfactory/packetreader Not a pure module */
