// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");
var BitFlags$TerrariaPacket = require("../BitFlags.js");
var PacketType$TerrariaPacket = require("../PacketType.js");
var ManagedPacketWriter$PacketFactory = require("@popstarfreas/packetfactory/src/ManagedPacketWriter.js");
var Packetreader = require("@popstarfreas/packetfactory/packetreader").default;
var Packetwriter = require("@popstarfreas/packetfactory/packetwriter").default;

function readInt32(prim) {
  return prim.readInt32();
}

function readInt16(prim) {
  return prim.readInt16();
}

function readSingle(prim) {
  return prim.readSingle();
}

function readUInt16(prim) {
  return prim.readUInt16();
}

function readByte(prim) {
  return prim.readByte();
}

function readNpcFlags1(reader) {
  var flags = BitFlags$TerrariaPacket.fromByte(reader.readByte());
  return {
          directionX: BitFlags$TerrariaPacket.flag1(flags),
          directionY: BitFlags$TerrariaPacket.flag2(flags),
          ai0: BitFlags$TerrariaPacket.flag3(flags),
          ai1: BitFlags$TerrariaPacket.flag4(flags),
          ai2: BitFlags$TerrariaPacket.flag5(flags),
          ai3: BitFlags$TerrariaPacket.flag6(flags),
          spriteDirection: BitFlags$TerrariaPacket.flag7(flags),
          lifeMax: BitFlags$TerrariaPacket.flag8(flags)
        };
}

function readNpcFlags2(reader) {
  var flags = BitFlags$TerrariaPacket.fromByte(reader.readByte());
  return {
          statsScaled: BitFlags$TerrariaPacket.flag1(flags),
          spawnedFromStatue: BitFlags$TerrariaPacket.flag2(flags),
          strengthMultiplier: BitFlags$TerrariaPacket.flag3(flags)
        };
}

function parse(payload) {
  var reader = new Packetreader(payload);
  var npcSlotId = reader.readInt16();
  var x = reader.readSingle();
  var y = reader.readSingle();
  var vx = reader.readSingle();
  var vy = reader.readSingle();
  var target = reader.readUInt16();
  var npcFlags1 = readNpcFlags1(reader);
  var npcFlags2 = readNpcFlags2(reader);
  var ai_0 = npcFlags1.ai0 ? reader.readSingle() : undefined;
  var ai_1 = npcFlags1.ai1 ? reader.readSingle() : undefined;
  var ai_2 = npcFlags1.ai2 ? reader.readSingle() : undefined;
  var ai_3 = npcFlags1.ai3 ? reader.readSingle() : undefined;
  var ai = [
    ai_0,
    ai_1,
    ai_2,
    ai_3
  ];
  var npcTypeId = reader.readInt16();
  var playerCountScale = npcFlags2.statsScaled ? reader.readByte() : undefined;
  var strengthMultiplier = npcFlags2.strengthMultiplier ? reader.readSingle() : undefined;
  var life;
  if (npcFlags1.lifeMax) {
    life = /* Max */0;
  } else {
    var lifeBytes = reader.readByte();
    switch (lifeBytes) {
      case 0 :
          life = undefined;
          break;
      case 1 :
          life = {
            TAG: /* Byte */0,
            _0: reader.readByte()
          };
          break;
      case 2 :
          life = {
            TAG: /* Int16 */1,
            _0: reader.readInt16()
          };
          break;
      case 3 :
          life = {
            TAG: /* Int32 */2,
            _0: reader.readInt32()
          };
          break;
      default:
        life = undefined;
    }
  }
  var releaseOwner;
  try {
    releaseOwner = reader.readByte();
  }
  catch (exn){
    releaseOwner = undefined;
  }
  if (life !== undefined) {
    return {
            npcSlotId: npcSlotId,
            npcTypeId: npcTypeId,
            x: x,
            y: y,
            vx: vx,
            vy: vy,
            target: target,
            directionX: npcFlags1.directionX,
            directionY: npcFlags1.directionY,
            ai: ai,
            spriteDirection: npcFlags1.spriteDirection,
            life: life,
            releaseOwner: releaseOwner,
            playerCountScale: playerCountScale,
            strengthMultiplier: strengthMultiplier,
            spawnedFromStatue: npcFlags2.spawnedFromStatue
          };
  }
  
}

var Decode = {
  readInt32: readInt32,
  readInt16: readInt16,
  readSingle: readSingle,
  readUInt16: readUInt16,
  readByte: readByte,
  readNpcFlags1: readNpcFlags1,
  readNpcFlags2: readNpcFlags2,
  parse: parse
};

function packInt32(prim0, prim1) {
  return prim0.packInt32(prim1);
}

function packInt16(prim0, prim1) {
  return prim0.packInt16(prim1);
}

function packSingle(prim0, prim1) {
  return prim0.packSingle(prim1);
}

function packUInt16(prim0, prim1) {
  return prim0.packUInt16(prim1);
}

function packByte(prim0, prim1) {
  return prim0.packByte(prim1);
}

function data(prim) {
  return prim.data;
}

function npcFlags1(self) {
  var $$byte = 0;
  var match = self.ai;
  $$byte = $$byte | (
    self.directionX ? 1 : 0
  );
  $$byte = $$byte | (
    self.directionY ? 1 : 0
  );
  $$byte = $$byte | (
    Belt_Option.isSome(match[0]) ? 1 : 0
  );
  $$byte = $$byte | (
    Belt_Option.isSome(match[1]) ? 1 : 0
  );
  $$byte = $$byte | (
    Belt_Option.isSome(match[2]) ? 1 : 0
  );
  $$byte = $$byte | (
    Belt_Option.isSome(match[3]) ? 1 : 0
  );
  $$byte = $$byte | (
    self.spriteDirection ? 1 : 0
  );
  $$byte = $$byte | (
    self.life === /* Max */0 ? 1 : 0
  );
  return $$byte;
}

function npcFlags2(self) {
  var $$byte = 0;
  $$byte = $$byte | (
    Belt_Option.isSome(self.playerCountScale) ? 1 : 0
  );
  $$byte = $$byte | (
    self.spawnedFromStatue ? 1 : 0
  );
  $$byte = $$byte | (
    Belt_Option.isSome(self.strengthMultiplier) ? 1 : 0
  );
  return $$byte;
}

function packAi(writer, param) {
  var ai3 = param[3];
  var ai2 = param[2];
  var ai1 = param[1];
  var ai0 = param[0];
  if (ai0 !== undefined) {
    writer.packSingle(ai0);
  }
  if (ai1 !== undefined) {
    writer.packSingle(ai1);
  }
  if (ai2 !== undefined) {
    writer.packSingle(ai2);
  }
  if (ai3 !== undefined) {
    writer.packSingle(ai3);
  }
  return writer;
}

function packPlayerCountScale(writer, playerCountScale) {
  if (playerCountScale !== undefined) {
    return writer.packByte(playerCountScale);
  } else {
    return writer;
  }
}

function packStrengthMultiplier(writer, strengthMultiplier) {
  if (strengthMultiplier !== undefined) {
    return writer.packSingle(strengthMultiplier);
  } else {
    return writer;
  }
}

function packLife(writer, life) {
  if (typeof life === "number") {
    return writer;
  }
  switch (life.TAG | 0) {
    case /* Byte */0 :
        return writer.packByte(life._0);
    case /* Int16 */1 :
        return writer.packInt16(life._0);
    case /* Int32 */2 :
        return writer.packInt32(life._0);
    
  }
}

function packReleaseOwner(writer, releaseOwner) {
  if (releaseOwner !== undefined) {
    return writer.packByte(releaseOwner);
  } else {
    return writer;
  }
}

function toBuffer(self) {
  return packReleaseOwner(packLife(packStrengthMultiplier(packPlayerCountScale(packAi(ManagedPacketWriter$PacketFactory.setType(new Packetwriter(), PacketType$TerrariaPacket.toInt(/* NpcUpdate */21)).packInt16(self.npcSlotId).packSingle(self.x).packSingle(self.y).packSingle(self.vx).packSingle(self.vy).packUInt16(self.target).packByte(npcFlags1(self)).packByte(npcFlags2(self)), self.ai).packInt16(self.npcTypeId), self.playerCountScale), self.strengthMultiplier), self.life), self.releaseOwner).data;
}

var Encode = {
  packInt32: packInt32,
  packInt16: packInt16,
  packSingle: packSingle,
  packUInt16: packUInt16,
  packByte: packByte,
  setType: ManagedPacketWriter$PacketFactory.setType,
  data: data,
  npcFlags1: npcFlags1,
  npcFlags2: npcFlags2,
  packAi: packAi,
  packPlayerCountScale: packPlayerCountScale,
  packStrengthMultiplier: packStrengthMultiplier,
  packLife: packLife,
  packReleaseOwner: packReleaseOwner,
  toBuffer: toBuffer
};

exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* @popstarfreas/packetfactory/packetreader Not a pure module */
