// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ManagedPacketWriter$PacketFactory = require("@popstarfreas/packetfactory/src/ManagedPacketWriter.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../ErrorAwarePacketReader.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;
let Packetwriter = require("@popstarfreas/packetfactory/packetwriter").default;

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "playerId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "anglerQuestsFinished");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "golferScoreAccumulated");
  if (e$2.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        playerId: e._0,
        anglerQuestsFinished: e$1._0,
        golferScoreAccumulated: e$2._0
      }
    };
  } else {
    return e$2;
  }
}

let Decode = {
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  readInt32: ErrorAwarePacketReader$TerrariaPacket.readInt32,
  parse: parse
};

function packByte(prim0, prim1) {
  return prim0.packByte(prim1);
}

function packInt32(prim0, prim1) {
  return prim0.packInt32(prim1);
}

function data(prim) {
  return prim.data;
}

function toBuffer(self) {
  return ManagedPacketWriter$PacketFactory.setType(new Packetwriter(), PacketType$TerrariaPacket.toInt("AnglerQuestsCompletedAmount")).packByte(self.playerId).packInt32(self.anglerQuestsFinished).packInt32(self.golferScoreAccumulated).data;
}

let Encode = {
  packByte: packByte,
  packInt32: packInt32,
  setType: ManagedPacketWriter$PacketFactory.setType,
  data: data,
  toBuffer: toBuffer
};

exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* @popstarfreas/packetfactory/packetreader Not a pure module */
