// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../ErrorAwarePacketReader.js");
let ErrorAwarePacketWriter$TerrariaPacket = require("../ErrorAwarePacketWriter.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "x");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "y");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "npcNetId");
  if (e$2.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        x: e._0,
        y: e$1._0,
        npcNetId: e$2._0
      }
    };
  } else {
    return e$2;
  }
}

let Decode = {
  readUInt16: ErrorAwarePacketReader$TerrariaPacket.readUInt16,
  readInt16: ErrorAwarePacketReader$TerrariaPacket.readInt16,
  parse: parse
};

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NpcFishOut")), self.x, "x"), self.y, "y"), self.npcNetId, "npcNetId"));
}

let Encode = {
  packUInt16: ErrorAwarePacketWriter$TerrariaPacket.packUInt16,
  packInt16: ErrorAwarePacketWriter$TerrariaPacket.packInt16,
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  toBuffer: toBuffer
};

exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
