// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as PacketType$TerrariaPacket from "../PacketType.js";
import * as CreativePowers$TerrariaPacket from "../CreativePowers.js";
import * as ErrorAwarePacketReader$TerrariaPacket from "../ErrorAwarePacketReader.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";
import Packetreader from "@popstarfreas/packetfactory/packetreader";

function pylonActionToInt(pylonAction) {
  switch (pylonAction) {
    case "Added" :
      return 0;
    case "Removed" :
      return 1;
    case "RequestTeleport" :
      return 2;
  }
}

function powerLevelToInt(powerLevel) {
  switch (powerLevel) {
    case "LockedForEveryone" :
      return 0;
    case "CanBeChangedByHostAlone" :
      return 1;
    case "CanBeChangedByEveryone" :
      return 2;
  }
}

function fromInt(n) {
  switch (n) {
    case 0 :
      return "Liquid";
    case 1 :
      return "Text";
    case 2 :
      return "Ping";
    case 3 :
      return "Ambience";
    case 4 :
      return "Bestiary";
    case 5 :
      return "CreativeUnlocks";
    case 6 :
      return "CreativePower";
    case 7 :
      return "CreativeUnlocksPlayerReport";
    case 8 :
      return "TeleportPylon";
    case 9 :
      return "Particles";
    case 10 :
      return "CreativePowerPermissions";
    case 11 :
      return "Banners";
    case 12 :
      return "CraftingRequests";
    case 13 :
      return "LeashedEntity";
    case 14 :
      return "UnbreakableWallScan";
    default:
      return;
  }
}

function toInt(self) {
  switch (self) {
    case "Liquid" :
      return 0;
    case "Text" :
      return 1;
    case "Ping" :
      return 2;
    case "Ambience" :
      return 3;
    case "Bestiary" :
      return 4;
    case "CreativeUnlocks" :
      return 5;
    case "CreativePower" :
      return 6;
    case "CreativeUnlocksPlayerReport" :
      return 7;
    case "TeleportPylon" :
      return 8;
    case "Particles" :
      return 9;
    case "CreativePowerPermissions" :
      return 10;
    case "Banners" :
      return 11;
    case "CraftingRequests" :
      return 12;
    case "LeashedEntity" :
      return 13;
    case "UnbreakableWallScan" :
      return 14;
  }
}

let NetModuleType = {
  fromInt: fromInt,
  toInt: toInt
};

function pack7BitEncodedInt(writer, value, context) {
  let writer$1 = writer;
  let remaining = value;
  let $$continue = true;
  while ($$continue) {
    let byte = remaining & 127;
    remaining = (remaining >>> 7);
    if (remaining !== 0) {
      byte = byte | 128;
    }
    writer$1 = ErrorAwarePacketWriter$TerrariaPacket.packByte(writer$1, byte, context);
    if (remaining === 0) {
      $$continue = false;
    }
  };
  return writer$1;
}

function liquidToBuffer(liquid) {
  let writer = ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 0, "moduleType"), liquid.changes.length, "changesCount");
  liquid.changes.forEach(change => {
    ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(writer, change.y, "y"), change.x, "x"), change.amount, "amount"), change.liquidType, "liquidType");
  });
  return ErrorAwarePacketWriter$TerrariaPacket.data(writer);
}

function clientTextToBuffer(commandId, message) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packString(ErrorAwarePacketWriter$TerrariaPacket.packString(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 1, "moduleType"), commandId, "commandId"), message, "message"));
}

function serverTextToBuffer(playerId, networkText, color) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packColor(ErrorAwarePacketWriter$TerrariaPacket.packNetworkText(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 1, "moduleType"), playerId, "playerId"), networkText, "networkText"), color, "color"));
}

function pingToBuffer(ping) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 2, "moduleType"), ping.x, "x"), ping.y, "y"));
}

function ambienceToBuffer(ambience) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packInt32(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 3, "moduleType"), ambience.playerId, "playerId"), ambience.seed, "seed"), ambience.skyEntityType, "skyEntityType"));
}

function bestiaryToBuffer(bestiary) {
  let writer = ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 4, "moduleType");
  let _count = bestiary.unlockType;
  let tmp;
  tmp = typeof _count !== "object" ? (
      _count === "Sight" ? ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 1, "unlockTypeByte") : ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 2, "unlockTypeByte")
    ) : ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 0, "unlockTypeByte");
  ErrorAwarePacketWriter$TerrariaPacket.packInt16(tmp, bestiary.npcId, "npcId");
  let count = bestiary.unlockType;
  let tmp$1;
  tmp$1 = typeof count !== "object" ? writer : pack7BitEncodedInt(writer, count._0, "killCount");
  return ErrorAwarePacketWriter$TerrariaPacket.data(tmp$1);
}

function creativePowerToBuffer(creativePower) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(CreativePowers$TerrariaPacket.pack(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 6, "moduleType"), creativePower));
}

function creativeUnlocksToBuffer(creativeUnlock) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 5, "moduleType"), creativeUnlock.itemId, "itemId"), creativeUnlock.sacrificeCount, "sacrificeCount"));
}

function creativeUnlocksPlayerReportToBuffer(unlockReport) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 7, "moduleType"), unlockReport.userId, "userId"), unlockReport.itemId, "itemId"), unlockReport.researchedCount, "researchedCount"));
}

function teleportPylonToBuffer(teleportPylon) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 8, "moduleType"), pylonActionToInt(teleportPylon.pylonAction), "pylonAction"), teleportPylon.x, "x"), teleportPylon.y, "y"), teleportPylon.pylonType, "pylonType"));
}

function particlesToBuffer(particle) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packInt32(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 9, "moduleType"), particle.particleType, "particleType"), particle.x, "x"), particle.y, "y"), particle.vx, "vx"), particle.vy, "vy"), particle.shaderIndex, "shaderIndex"), particle.invokedByPlayer, "invokedByPlayer"));
}

function creativePowerPermissionsToBuffer(creativePowerPermission) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 10, "moduleType"), 0, "messageType"), creativePowerPermission.powerType, "powerType"), powerLevelToInt(creativePowerPermission.powerLevel), "powerLevel"));
}

function bannersToBuffer(message) {
  let writer = ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 11, "moduleType");
  switch (message.TAG) {
    case "BannerFullState" :
      let state = message._0;
      let writer$1 = ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 0, "messageType"), state.killCounts.length, "killCountLength");
      state.killCounts.forEach(count => {
        ErrorAwarePacketWriter$TerrariaPacket.packInt32(writer$1, count, "killCount");
      });
      let writer$2 = ErrorAwarePacketWriter$TerrariaPacket.packInt16(writer$1, state.claimableCounts.length, "claimableCountLength");
      state.claimableCounts.forEach(count => {
        ErrorAwarePacketWriter$TerrariaPacket.packUInt16(writer$2, count, "claimableCount");
      });
      return ErrorAwarePacketWriter$TerrariaPacket.data(writer$2);
    case "BannerKillCountUpdate" :
      let match = message._0;
      return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packInt32(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 1, "messageType"), match.bannerId, "bannerId"), match.killCount, "killCount"));
    case "BannerClaimCountUpdate" :
      let match$1 = message._0;
      return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 2, "messageType"), match$1.bannerId, "bannerId"), match$1.claimCount, "claimCount"));
    case "BannerClaimRequest" :
      let match$2 = message._0;
      return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 3, "messageType"), match$2.bannerId, "bannerId"), match$2.amount, "amount"));
    case "BannerClaimResponse" :
      let match$3 = message._0;
      return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packBool(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 4, "messageType"), match$3.bannerId, "bannerId"), match$3.amount, "amount"), match$3.granted, "granted"));
  }
}

function craftingRequestsToBuffer(message) {
  let writer = ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 12, "moduleType");
  if (message.TAG !== "CraftingRequest") {
    return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packBool(writer, message._0.approved, "approved"));
  }
  let request = message._0;
  let writer$1 = pack7BitEncodedInt(writer, request.items.length, "itemsCount");
  request.items.forEach(item => {
    pack7BitEncodedInt(ErrorAwarePacketWriter$TerrariaPacket.packInt32(writer$1, item.itemIdOrRecipeGroup, "itemIdOrRecipeGroup"), item.stack, "stack");
  });
  let writer$2 = pack7BitEncodedInt(writer$1, request.chestIndexes.length, "chestCount");
  request.chestIndexes.forEach(chestIndex => {
    pack7BitEncodedInt(writer$2, chestIndex, "chestIndex");
  });
  return ErrorAwarePacketWriter$TerrariaPacket.data(writer$2);
}

function packSparseNpcTimes(writer, entries) {
  let writer$1 = {
    contents: writer
  };
  entries.forEach(entry => {
    writer$1.contents = ErrorAwarePacketWriter$TerrariaPacket.packInt32(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer$1.contents, entry.npcIndex, "npcIndex"), entry.time, "npcTime");
  });
  return ErrorAwarePacketWriter$TerrariaPacket.packByte(writer$1.contents, 200, "npcIndexSentinel");
}

function leashedEntityToBuffer(message) {
  let writer = ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 13, "moduleType");
  switch (message.TAG) {
    case "LeashedRemove" :
      return ErrorAwarePacketWriter$TerrariaPacket.data(pack7BitEncodedInt(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 0, "messageType"), message._0.slot, "slot"));
    case "LeashedFullSync" :
      let match = message._0;
      return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packBuffer(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(pack7BitEncodedInt(pack7BitEncodedInt(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 1, "messageType"), match.slot, "slot"), match.entityType, "entityType"), match.anchorX, "anchorX"), match.anchorY, "anchorY"), match.payload, "payload"));
    case "LeashedPartialSync" :
      let match$1 = message._0;
      return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packBuffer(pack7BitEncodedInt(pack7BitEncodedInt(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 2, "messageType"), match$1.slot, "slot"), match$1.entityType, "entityType"), match$1.payload, "payload"));
  }
}

function unbreakableWallScanToBuffer(payload) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packBool(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("NetModuleLoad")), 14, "moduleType"), payload.playerId, "playerId"), payload.insideUnbreakableWalls, "insideUnbreakableWalls"));
}

function toBuffer(self) {
  switch (self.TAG) {
    case "Liquid" :
      return liquidToBuffer(self._0);
    case "ClientText" :
      return clientTextToBuffer(self._0, self._1);
    case "ServerText" :
      return serverTextToBuffer(self._0, self._1, self._2);
    case "Ping" :
      return pingToBuffer(self._0);
    case "Ambience" :
      return ambienceToBuffer(self._0);
    case "Bestiary" :
      return bestiaryToBuffer(self._0);
    case "CreativeUnlocks" :
      return creativeUnlocksToBuffer(self._0);
    case "CreativePower" :
      return creativePowerToBuffer(self._0);
    case "CreativeUnlocksPlayerReport" :
      return creativeUnlocksPlayerReportToBuffer(self._0);
    case "TeleportPylon" :
      return teleportPylonToBuffer(self._0);
    case "Particles" :
      return particlesToBuffer(self._0);
    case "CreativePowerPermissions" :
      return creativePowerPermissionsToBuffer(self._0);
    case "Banners" :
      return bannersToBuffer(self._0);
    case "CraftingRequests" :
      return craftingRequestsToBuffer(self._0);
    case "LeashedEntity" :
      return leashedEntityToBuffer(self._0);
    case "UnbreakableWallScan" :
      return unbreakableWallScanToBuffer(self._0);
  }
}

let Encode = {
  packInt32: ErrorAwarePacketWriter$TerrariaPacket.packInt32,
  packInt16: ErrorAwarePacketWriter$TerrariaPacket.packInt16,
  packNetworkText: ErrorAwarePacketWriter$TerrariaPacket.packNetworkText,
  packColor: ErrorAwarePacketWriter$TerrariaPacket.packColor,
  packString: ErrorAwarePacketWriter$TerrariaPacket.packString,
  packUInt16: ErrorAwarePacketWriter$TerrariaPacket.packUInt16,
  packByte: ErrorAwarePacketWriter$TerrariaPacket.packByte,
  packSingle: ErrorAwarePacketWriter$TerrariaPacket.packSingle,
  packBool: ErrorAwarePacketWriter$TerrariaPacket.packBool,
  packBuffer: ErrorAwarePacketWriter$TerrariaPacket.packBuffer,
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  pack7BitEncodedInt: pack7BitEncodedInt,
  liquidToBuffer: liquidToBuffer,
  clientTextToBuffer: clientTextToBuffer,
  serverTextToBuffer: serverTextToBuffer,
  pingToBuffer: pingToBuffer,
  ambienceToBuffer: ambienceToBuffer,
  bestiaryToBuffer: bestiaryToBuffer,
  creativePowerToBuffer: creativePowerToBuffer,
  creativeUnlocksToBuffer: creativeUnlocksToBuffer,
  creativeUnlocksPlayerReportToBuffer: creativeUnlocksPlayerReportToBuffer,
  teleportPylonToBuffer: teleportPylonToBuffer,
  particlesToBuffer: particlesToBuffer,
  creativePowerPermissionsToBuffer: creativePowerPermissionsToBuffer,
  bannersToBuffer: bannersToBuffer,
  craftingRequestsToBuffer: craftingRequestsToBuffer,
  packSparseNpcTimes: packSparseNpcTimes,
  leashedEntityToBuffer: leashedEntityToBuffer,
  unbreakableWallScanToBuffer: unbreakableWallScanToBuffer,
  toBuffer: toBuffer
};

function parseLiquid(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "changesCount");
  if (e.TAG !== "Ok") {
    return e;
  }
  let changesCount = e._0;
  let readChanges = (_idx, _acc) => {
    while (true) {
      let acc = _acc;
      let idx = _idx;
      if (idx >= changesCount) {
        return {
          TAG: "Ok",
          _0: acc.toReversed()
        };
      }
      let e = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "y");
      if (e.TAG !== "Ok") {
        return e;
      }
      let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "x");
      if (e$1.TAG !== "Ok") {
        return e$1;
      }
      let e$2 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "amount");
      if (e$2.TAG !== "Ok") {
        return e$2;
      }
      let e$3 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "liquidType");
      if (e$3.TAG !== "Ok") {
        return e$3;
      }
      _acc = Belt_Array.concatMany([
        [{
            x: e$1._0,
            y: e._0,
            amount: e$2._0,
            liquidType: e$3._0
          }],
        acc
      ]);
      _idx = idx + 1 | 0;
      continue;
    };
  };
  let e$1 = readChanges(0, []);
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        TAG: "Liquid",
        _0: {
          changes: e$1._0
        }
      }
    };
  } else {
    return e$1;
  }
}

function parseText(reader, fromServer) {
  if (fromServer) {
    let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "playerId");
    if (e.TAG !== "Ok") {
      return e;
    }
    let e$1 = ErrorAwarePacketReader$TerrariaPacket.readNetworkText(reader, "message");
    if (e$1.TAG !== "Ok") {
      return e$1;
    }
    let e$2 = ErrorAwarePacketReader$TerrariaPacket.readColor(reader, "color");
    if (e$2.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          TAG: "ServerText",
          _0: e._0,
          _1: e$1._0,
          _2: e$2._0
        }
      };
    } else {
      return e$2;
    }
  }
  let e$3 = ErrorAwarePacketReader$TerrariaPacket.readString(reader, "commandId");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let e$4 = ErrorAwarePacketReader$TerrariaPacket.readString(reader, "message");
  if (e$4.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        TAG: "ClientText",
        _0: e$3._0,
        _1: e$4._0
      }
    };
  } else {
    return e$4;
  }
}

function parsePing(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "x");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "y");
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        TAG: "Ping",
        _0: {
          x: e._0,
          y: e$1._0
        }
      }
    };
  } else {
    return e$1;
  }
}

function parseAmbience(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "playerId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "seed");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "skyEntityType");
  if (e$2.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        TAG: "Ambience",
        _0: {
          playerId: e._0,
          seed: e$1._0,
          skyEntityType: e$2._0
        }
      }
    };
  } else {
    return e$2;
  }
}

function parseBestiary(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "rawBestiaryUnlockType");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "npcId");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2;
  switch (e._0) {
    case 0 :
      let e$3 = ErrorAwarePacketReader$TerrariaPacket.read7BitEncodedInt(reader, "killCount");
      e$2 = e$3.TAG === "Ok" ? ({
          TAG: "Ok",
          _0: {
            TAG: "Kill",
            _0: e$3._0
          }
        }) : e$3;
      break;
    case 1 :
      e$2 = {
        TAG: "Ok",
        _0: "Sight"
      };
      break;
    case 2 :
      e$2 = {
        TAG: "Ok",
        _0: "Chat"
      };
      break;
    default:
      e$2 = {
        TAG: "Error",
        _0: {
          context: "Packet_NetModuleLoad.parseBestiary",
          error: new Error("Unknown bestiary unlock type")
        }
      };
  }
  if (e$2.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        TAG: "Bestiary",
        _0: {
          unlockType: e$2._0,
          npcId: e$1._0
        }
      }
    };
  } else {
    return e$2;
  }
}

function parseCreativePower(reader) {
  let p = CreativePowers$TerrariaPacket.parse(reader);
  if (p !== undefined) {
    return {
      TAG: "Ok",
      _0: {
        TAG: "CreativePower",
        _0: p
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        context: "Packet_NetModuleLoad.parseCreativePower",
        error: new Error("Failed to parse creative power")
      }
    };
  }
}

function parseCreativeUnlocks(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "itemId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "sacrificeCount");
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        TAG: "CreativeUnlocks",
        _0: {
          itemId: e._0,
          sacrificeCount: e$1._0
        }
      }
    };
  } else {
    return e$1;
  }
}

function parseCreativeUnlocksPlayerReport(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "userId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "itemId");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "researchedCount");
  if (e$2.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        TAG: "CreativeUnlocksPlayerReport",
        _0: {
          userId: e._0,
          itemId: e$1._0,
          researchedCount: e$2._0
        }
      }
    };
  } else {
    return e$2;
  }
}

function parseTeleportPylon(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "rawPylonAction");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "x");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "y");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "pylonType");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let pylonAction;
  switch (e._0) {
    case 0 :
      pylonAction = "Added";
      break;
    case 1 :
      pylonAction = "Removed";
      break;
    case 2 :
      pylonAction = "RequestTeleport";
      break;
    default:
      pylonAction = undefined;
  }
  if (pylonAction !== undefined) {
    return {
      TAG: "Ok",
      _0: {
        TAG: "TeleportPylon",
        _0: {
          pylonAction: pylonAction,
          x: e$1._0,
          y: e$2._0,
          pylonType: e$3._0
        }
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        context: "Packet_NetModuleLoad.parseTeleportPylon",
        error: new Error("Unknown pylon action")
      }
    };
  }
}

function parseParticle(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "particleType");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "x");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "y");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "vx");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let e$4 = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "vy");
  if (e$4.TAG !== "Ok") {
    return e$4;
  }
  let e$5 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "shaderIndex");
  if (e$5.TAG !== "Ok") {
    return e$5;
  }
  let e$6 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "invokedByPlayer");
  if (e$6.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        TAG: "Particles",
        _0: {
          particleType: e._0,
          x: e$1._0,
          y: e$2._0,
          vx: e$3._0,
          vy: e$4._0,
          shaderIndex: e$5._0,
          invokedByPlayer: e$6._0
        }
      }
    };
  } else {
    return e$6;
  }
}

function parseCreativePowerPermission(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "messageType");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "powerType");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "rawPowerLevel");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let powerLevel;
  switch (e$2._0) {
    case 0 :
      powerLevel = "LockedForEveryone";
      break;
    case 1 :
      powerLevel = "CanBeChangedByHostAlone";
      break;
    case 2 :
      powerLevel = "CanBeChangedByEveryone";
      break;
    default:
      powerLevel = undefined;
  }
  if (powerLevel !== undefined) {
    return {
      TAG: "Ok",
      _0: {
        TAG: "CreativePowerPermissions",
        _0: {
          powerType: e$1._0,
          powerLevel: powerLevel
        }
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        context: "Packet_NetModuleLoad.parseCreativePowerPermission",
        error: new Error("Unknown creative power permission level")
      }
    };
  }
}

function parseBanners(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "messageType");
  if (e.TAG !== "Ok") {
    return e;
  }
  switch (e._0) {
    case 0 :
      let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "killCountLength");
      if (e$1.TAG !== "Ok") {
        return e$1;
      }
      let killCountLength = e$1._0;
      let readKillCounts = (_idx, _acc) => {
        while (true) {
          let acc = _acc;
          let idx = _idx;
          if (idx >= killCountLength) {
            return {
              TAG: "Ok",
              _0: acc.toReversed()
            };
          }
          let e = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "killCount");
          if (e.TAG !== "Ok") {
            return e;
          }
          _acc = Belt_Array.concatMany([
            [e._0],
            acc
          ]);
          _idx = idx + 1 | 0;
          continue;
        };
      };
      let e$2 = readKillCounts(0, []);
      if (e$2.TAG !== "Ok") {
        return e$2;
      }
      let e$3 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "claimableCountLength");
      if (e$3.TAG !== "Ok") {
        return e$3;
      }
      let claimableCountLength = e$3._0;
      let readClaimableCounts = (_idx, _acc) => {
        while (true) {
          let acc = _acc;
          let idx = _idx;
          if (idx >= claimableCountLength) {
            return {
              TAG: "Ok",
              _0: acc.toReversed()
            };
          }
          let e = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "claimableCount");
          if (e.TAG !== "Ok") {
            return e;
          }
          _acc = Belt_Array.concatMany([
            [e._0],
            acc
          ]);
          _idx = idx + 1 | 0;
          continue;
        };
      };
      let e$4 = readClaimableCounts(0, []);
      if (e$4.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "Banners",
            _0: {
              TAG: "BannerFullState",
              _0: {
                killCounts: e$2._0,
                claimableCounts: e$4._0
              }
            }
          }
        };
      } else {
        return e$4;
      }
    case 1 :
      let e$5 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "bannerId");
      if (e$5.TAG !== "Ok") {
        return e$5;
      }
      let e$6 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "killCount");
      if (e$6.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "Banners",
            _0: {
              TAG: "BannerKillCountUpdate",
              _0: {
                bannerId: e$5._0,
                killCount: e$6._0
              }
            }
          }
        };
      } else {
        return e$6;
      }
    case 2 :
      let e$7 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "bannerId");
      if (e$7.TAG !== "Ok") {
        return e$7;
      }
      let e$8 = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "claimCount");
      if (e$8.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "Banners",
            _0: {
              TAG: "BannerClaimCountUpdate",
              _0: {
                bannerId: e$7._0,
                claimCount: e$8._0
              }
            }
          }
        };
      } else {
        return e$8;
      }
    case 3 :
      let e$9 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "bannerId");
      if (e$9.TAG !== "Ok") {
        return e$9;
      }
      let e$10 = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "amount");
      if (e$10.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "Banners",
            _0: {
              TAG: "BannerClaimRequest",
              _0: {
                bannerId: e$9._0,
                amount: e$10._0
              }
            }
          }
        };
      } else {
        return e$10;
      }
    case 4 :
      let e$11 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "bannerId");
      if (e$11.TAG !== "Ok") {
        return e$11;
      }
      let e$12 = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "amount");
      if (e$12.TAG !== "Ok") {
        return e$12;
      }
      let e$13 = ErrorAwarePacketReader$TerrariaPacket.readBool(reader, "granted");
      if (e$13.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "Banners",
            _0: {
              TAG: "BannerClaimResponse",
              _0: {
                bannerId: e$11._0,
                amount: e$12._0,
                granted: e$13._0
              }
            }
          }
        };
      } else {
        return e$13;
      }
    default:
      return {
        TAG: "Error",
        _0: {
          context: "Packet_NetModuleLoad.parseBanners",
          error: new Error("Unknown banner message type")
        }
      };
  }
}

function parseCraftingRequests(reader, fromServer) {
  if (fromServer) {
    let e = ErrorAwarePacketReader$TerrariaPacket.readBool(reader, "approved");
    if (e.TAG === "Ok") {
      return {
        TAG: "Ok",
        _0: {
          TAG: "CraftingRequests",
          _0: {
            TAG: "CraftingResponse",
            _0: {
              approved: e._0
            }
          }
        }
      };
    } else {
      return e;
    }
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.read7BitEncodedInt(reader, "itemsCount");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let itemsCount = e$1._0;
  let readItems = (_idx, _acc) => {
    while (true) {
      let acc = _acc;
      let idx = _idx;
      if (idx >= itemsCount) {
        return {
          TAG: "Ok",
          _0: acc.toReversed()
        };
      }
      let e = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "itemIdOrRecipeGroup");
      if (e.TAG !== "Ok") {
        return e;
      }
      let e$1 = ErrorAwarePacketReader$TerrariaPacket.read7BitEncodedInt(reader, "stack");
      if (e$1.TAG !== "Ok") {
        return e$1;
      }
      _acc = Belt_Array.concatMany([
        [{
            itemIdOrRecipeGroup: e._0,
            stack: e$1._0
          }],
        acc
      ]);
      _idx = idx + 1 | 0;
      continue;
    };
  };
  let e$2 = readItems(0, []);
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwarePacketReader$TerrariaPacket.read7BitEncodedInt(reader, "chestCount");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let chestCount = e$3._0;
  let readChests = (_idx, _acc) => {
    while (true) {
      let acc = _acc;
      let idx = _idx;
      if (idx >= chestCount) {
        return {
          TAG: "Ok",
          _0: acc.toReversed()
        };
      }
      let e = ErrorAwarePacketReader$TerrariaPacket.read7BitEncodedInt(reader, "chestIndex");
      if (e.TAG !== "Ok") {
        return e;
      }
      _acc = Belt_Array.concatMany([
        [e._0],
        acc
      ]);
      _idx = idx + 1 | 0;
      continue;
    };
  };
  let e$4 = readChests(0, []);
  if (e$4.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        TAG: "CraftingRequests",
        _0: {
          TAG: "CraftingRequest",
          _0: {
            items: e$2._0,
            chestIndexes: e$4._0
          }
        }
      }
    };
  } else {
    return e$4;
  }
}

function readSparseNpcTimes(reader) {
  let _acc = [];
  while (true) {
    let acc = _acc;
    let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "npcIndex");
    if (e.TAG !== "Ok") {
      return e;
    }
    let npcIndex = e._0;
    if (npcIndex >= 200) {
      return {
        TAG: "Ok",
        _0: acc.toReversed()
      };
    }
    let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "npcTime");
    if (e$1.TAG !== "Ok") {
      return e$1;
    }
    _acc = Belt_Array.concatMany([
      [{
          npcIndex: npcIndex,
          time: e$1._0
        }],
      acc
    ]);
    continue;
  };
}

function parseLeashedEntity(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "messageType");
  if (e.TAG !== "Ok") {
    return e;
  }
  switch (e._0) {
    case 0 :
      let e$1 = ErrorAwarePacketReader$TerrariaPacket.read7BitEncodedInt(reader, "slot");
      if (e$1.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "LeashedEntity",
            _0: {
              TAG: "LeashedRemove",
              _0: {
                slot: e$1._0
              }
            }
          }
        };
      } else {
        return e$1;
      }
    case 1 :
      let e$2 = ErrorAwarePacketReader$TerrariaPacket.read7BitEncodedInt(reader, "slot");
      if (e$2.TAG !== "Ok") {
        return e$2;
      }
      let e$3 = ErrorAwarePacketReader$TerrariaPacket.read7BitEncodedInt(reader, "entityType");
      if (e$3.TAG !== "Ok") {
        return e$3;
      }
      let e$4 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "anchorX");
      if (e$4.TAG !== "Ok") {
        return e$4;
      }
      let e$5 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "anchorY");
      if (e$5.TAG !== "Ok") {
        return e$5;
      }
      let e$6 = ErrorAwarePacketReader$TerrariaPacket.getBytesLeft(reader);
      if (e$6.TAG !== "Ok") {
        return e$6;
      }
      let e$7 = ErrorAwarePacketReader$TerrariaPacket.readBuffer(reader, e$6._0, "payload");
      if (e$7.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "LeashedEntity",
            _0: {
              TAG: "LeashedFullSync",
              _0: {
                slot: e$2._0,
                entityType: e$3._0,
                anchorX: e$4._0,
                anchorY: e$5._0,
                payload: e$7._0
              }
            }
          }
        };
      } else {
        return e$7;
      }
    case 2 :
      let e$8 = ErrorAwarePacketReader$TerrariaPacket.read7BitEncodedInt(reader, "slot");
      if (e$8.TAG !== "Ok") {
        return e$8;
      }
      let e$9 = ErrorAwarePacketReader$TerrariaPacket.read7BitEncodedInt(reader, "entityType");
      if (e$9.TAG !== "Ok") {
        return e$9;
      }
      let e$10 = ErrorAwarePacketReader$TerrariaPacket.getBytesLeft(reader);
      if (e$10.TAG !== "Ok") {
        return e$10;
      }
      let e$11 = ErrorAwarePacketReader$TerrariaPacket.readBuffer(reader, e$10._0, "payload");
      if (e$11.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "LeashedEntity",
            _0: {
              TAG: "LeashedPartialSync",
              _0: {
                slot: e$8._0,
                entityType: e$9._0,
                payload: e$11._0
              }
            }
          }
        };
      } else {
        return e$11;
      }
    default:
      return {
        TAG: "Error",
        _0: {
          context: "Packet_NetModuleLoad.parseLeashedEntity",
          error: new Error("Unknown leashed entity message type")
        }
      };
  }
}

function parseUnbreakableWallScan(reader) {
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "playerId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readBool(reader, "insideUnbreakableWalls");
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        TAG: "UnbreakableWallScan",
        _0: {
          playerId: e._0,
          insideUnbreakableWalls: e$1._0
        }
      }
    };
  } else {
    return e$1;
  }
}

function parse(payload, fromServer) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "moduleType");
  if (e.TAG !== "Ok") {
    return e;
  }
  let match = fromInt(e._0);
  if (match === undefined) {
    return {
      TAG: "Error",
      _0: {
        context: "Packet_NetModuleLoad.parse",
        error: new Error("Unknown net module type")
      }
    };
  }
  switch (match) {
    case "Liquid" :
      return parseLiquid(reader);
    case "Text" :
      return parseText(reader, fromServer);
    case "Ping" :
      return parsePing(reader);
    case "Ambience" :
      return parseAmbience(reader);
    case "Bestiary" :
      return parseBestiary(reader);
    case "CreativeUnlocks" :
      return parseCreativeUnlocks(reader);
    case "CreativePower" :
      return parseCreativePower(reader);
    case "CreativeUnlocksPlayerReport" :
      return parseCreativeUnlocksPlayerReport(reader);
    case "TeleportPylon" :
      return parseTeleportPylon(reader);
    case "Particles" :
      return parseParticle(reader);
    case "CreativePowerPermissions" :
      return parseCreativePowerPermission(reader);
    case "Banners" :
      return parseBanners(reader);
    case "CraftingRequests" :
      return parseCraftingRequests(reader, fromServer);
    case "LeashedEntity" :
      return parseLeashedEntity(reader);
    case "UnbreakableWallScan" :
      return parseUnbreakableWallScan(reader);
  }
}

let Decode = {
  readInt32: ErrorAwarePacketReader$TerrariaPacket.readInt32,
  readSingle: ErrorAwarePacketReader$TerrariaPacket.readSingle,
  readUInt16: ErrorAwarePacketReader$TerrariaPacket.readUInt16,
  readInt16: ErrorAwarePacketReader$TerrariaPacket.readInt16,
  readString: ErrorAwarePacketReader$TerrariaPacket.readString,
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  readBool: ErrorAwarePacketReader$TerrariaPacket.readBool,
  readColor: ErrorAwarePacketReader$TerrariaPacket.readColor,
  readNetworkText: ErrorAwarePacketReader$TerrariaPacket.readNetworkText,
  readBuffer: ErrorAwarePacketReader$TerrariaPacket.readBuffer,
  getBytesLeft: ErrorAwarePacketReader$TerrariaPacket.getBytesLeft,
  read7BitEncodedInt: ErrorAwarePacketReader$TerrariaPacket.read7BitEncodedInt,
  parseLiquid: parseLiquid,
  parseText: parseText,
  parsePing: parsePing,
  parseAmbience: parseAmbience,
  parseBestiary: parseBestiary,
  parseCreativePower: parseCreativePower,
  parseCreativeUnlocks: parseCreativeUnlocks,
  parseCreativeUnlocksPlayerReport: parseCreativeUnlocksPlayerReport,
  parseTeleportPylon: parseTeleportPylon,
  parseParticle: parseParticle,
  parseCreativePowerPermission: parseCreativePowerPermission,
  parseBanners: parseBanners,
  parseCraftingRequests: parseCraftingRequests,
  readSparseNpcTimes: readSparseNpcTimes,
  parseLeashedEntity: parseLeashedEntity,
  parseUnbreakableWallScan: parseUnbreakableWallScan,
  parse: parse
};

let Buffer;

let maxNpcIndexSentinel = 200;

export {
  Buffer,
  maxNpcIndexSentinel,
  pylonActionToInt,
  powerLevelToInt,
  NetModuleType,
  Encode,
  Decode,
  toBuffer,
  parse,
}
/* CreativePowers-TerrariaPacket Not a pure module */
