// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../ErrorAwarePacketReader.js");
let ErrorAwarePacketWriter$TerrariaPacket = require("../ErrorAwarePacketWriter.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "kind");
  if (e.TAG !== "Ok") {
    return e;
  }
  switch (e._0) {
    case 0 :
      let e$1 = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "shimmerX");
      if (e$1.TAG !== "Ok") {
        return e$1;
      }
      let e$2 = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "shimmerY");
      if (e$2.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "ShimmerEffect",
            _0: e$1._0,
            _1: e$2._0
          }
        };
      } else {
        return e$2;
      }
    case 1 :
      let e$3 = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "coinLuckX");
      if (e$3.TAG !== "Ok") {
        return e$3;
      }
      let e$4 = ErrorAwarePacketReader$TerrariaPacket.readSingle(reader, "coinLuckY");
      if (e$4.TAG !== "Ok") {
        return e$4;
      }
      let e$5 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "coinLuckAmount");
      if (e$5.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "CoinLuck",
            _0: {
              position: {
                x: e$3._0,
                y: e$4._0
              },
              amount: e$5._0
            }
          }
        };
      } else {
        return e$5;
      }
    case 2 :
      let e$6 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "newShimmerEffectId");
      if (e$6.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: {
            TAG: "NewShimmerEffect",
            _0: e$6._0
          }
        };
      } else {
        return e$6;
      }
    default:
      return {
        TAG: "Error",
        _0: {
          context: "Packet_ShimmerEffectOrCoinLuck.parse",
          error: new Error("Unknown shimmer effect kind")
        }
      };
  }
}

let Decode = {
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  readInt32: ErrorAwarePacketReader$TerrariaPacket.readInt32,
  readSingle: ErrorAwarePacketReader$TerrariaPacket.readSingle,
  parse: parse
};

function toBuffer(self) {
  let writer = ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("ShimmerEffectOrCoinLuck"));
  let tmp;
  switch (self.TAG) {
    case "ShimmerEffect" :
      tmp = ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 0, "kind"), self._0, "shimmerX"), self._1, "shimmerY");
      break;
    case "CoinLuck" :
      let match = self._0;
      let position = match.position;
      tmp = ErrorAwarePacketWriter$TerrariaPacket.packInt32(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packSingle(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 1, "kind"), position.x, "coinLuckX"), position.y, "coinLuckY"), match.amount, "coinLuckAmount");
      break;
    case "NewShimmerEffect" :
      tmp = ErrorAwarePacketWriter$TerrariaPacket.packInt32(ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, 2, "kind"), self._0, "newShimmerEffectId");
      break;
  }
  return ErrorAwarePacketWriter$TerrariaPacket.data(tmp);
}

let Encode = {
  Writer: undefined,
  packByte: ErrorAwarePacketWriter$TerrariaPacket.packByte,
  packInt32: ErrorAwarePacketWriter$TerrariaPacket.packInt32,
  packSingle: ErrorAwarePacketWriter$TerrariaPacket.packSingle,
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  toBuffer: toBuffer
};

exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
