// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ManagedPacketWriter$PacketFactory = require("@popstarfreas/packetfactory/src/ManagedPacketWriter.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;
let Packetwriter = require("@popstarfreas/packetfactory/packetwriter").default;

function fromInt(playerId) {
  if (playerId !== -1) {
    return {
      TAG: "PlayerId",
      _0: playerId
    };
  } else {
    return "All";
  }
}

function toInt(self) {
  if (typeof self !== "object") {
    return -1;
  } else {
    return self._0;
  }
}

let Immunity = {
  fromInt: fromInt,
  toInt: toInt
};

function readUInt16(prim) {
  return prim.readUInt16();
}

function readByte(prim) {
  return prim.readByte();
}

function readInt32(prim) {
  return prim.readInt32();
}

function readInt16(prim) {
  return prim.readInt16();
}

function parse(payload) {
  let reader = new Packetreader(payload);
  let npcId = reader.readUInt16();
  let setNpcImmunity = reader.readByte() === 1;
  let match = setNpcImmunity ? [
      reader.readInt32(),
      fromInt(reader.readInt16())
    ] : [
      undefined,
      undefined
    ];
  return {
    npcId: npcId,
    immunityTime: match[0],
    immunityFromPlayerId: match[1]
  };
}

let Decode = {
  readUInt16: readUInt16,
  readByte: readByte,
  readInt32: readInt32,
  readInt16: readInt16,
  parse: parse
};

function packUInt16(prim0, prim1) {
  return prim0.packUInt16(prim1);
}

function packByte(prim0, prim1) {
  return prim0.packByte(prim1);
}

function packInt32(prim0, prim1) {
  return prim0.packInt32(prim1);
}

function packInt16(prim0, prim1) {
  return prim0.packInt16(prim1);
}

function data(prim) {
  return prim.data;
}

function packImmunity(writer, immunityTime, immunityOrigin) {
  if (immunityTime !== undefined && immunityOrigin !== undefined) {
    return writer.packByte(1).packInt32(immunityTime).packInt16(toInt(immunityOrigin));
  } else {
    return writer.packByte(0);
  }
}

function toBuffer(self) {
  return packImmunity(ManagedPacketWriter$PacketFactory.setType(new Packetwriter(), PacketType$TerrariaPacket.toInt("NpcTamper")).packUInt16(self.npcId), self.immunityTime, self.immunityFromPlayerId).data;
}

let Encode = {
  packUInt16: packUInt16,
  packByte: packByte,
  packInt32: packInt32,
  packInt16: packInt16,
  setType: ManagedPacketWriter$PacketFactory.setType,
  data: data,
  packImmunity: packImmunity,
  toBuffer: toBuffer
};

let Option;

exports.Option = Option;
exports.Immunity = Immunity;
exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* @popstarfreas/packetfactory/packetreader Not a pure module */
