// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketType$TerrariaPacket from "../PacketType.js";
import * as ErrorAwarePacketReader$TerrariaPacket from "../ErrorAwarePacketReader.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";
import Packetreader from "@popstarfreas/packetfactory/packetreader";

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "projectileId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "owner");
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        projectileId: e._0,
        owner: e$1._0
      }
    };
  } else {
    return e$1;
  }
}

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("ProjectileDestroy")), self.projectileId, "projectileId"), self.owner, "owner"));
}

export {
  parse,
  toBuffer,
}
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
