// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../PacketType.js");
let ManagedPacketWriter$PacketFactory = require("@popstarfreas/packetfactory/src/ManagedPacketWriter.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../ErrorAwarePacketReader.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;
let Packetwriter = require("@popstarfreas/packetfactory/packetwriter").default;

function unlockTypeToInt(self) {
  switch (self) {
    case "Chest" :
      return 1;
    case "TempleDoor" :
      return 2;
    case "ChestLock" :
      return 3;
  }
}

function unlockTypeFromInt(self) {
  switch (self) {
    case 1 :
      return "Chest";
    case 2 :
      return "TempleDoor";
    case 3 :
      return "ChestLock";
    default:
      return;
  }
}

function makeError(_message) {
  return (new Error(_message));
}

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "unlockType");
  if (e.TAG !== "Ok") {
    return e;
  }
  let unlockType = unlockTypeFromInt(e._0);
  let e$1 = unlockType !== undefined ? ({
      TAG: "Ok",
      _0: unlockType
    }) : ({
      TAG: "Error",
      _0: {
        context: "Packet_ChestOrTempleUnlock.parse",
        error: makeError("Unknown unlock type")
      }
    });
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "x");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "y");
  if (e$3.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        unlockType: e$1._0,
        x: e$2._0,
        y: e$3._0
      }
    };
  } else {
    return e$3;
  }
}

let Decode = {
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  readInt16: ErrorAwarePacketReader$TerrariaPacket.readInt16,
  parse: parse
};

function packByte(prim0, prim1) {
  return prim0.packByte(prim1);
}

function packInt16(prim0, prim1) {
  return prim0.packInt16(prim1);
}

function data(prim) {
  return prim.data;
}

function toBuffer(self) {
  return ManagedPacketWriter$PacketFactory.setType(new Packetwriter(), PacketType$TerrariaPacket.toInt("ChestOrTempleUnlock")).packByte(unlockTypeToInt(self.unlockType)).packInt16(self.x).packInt16(self.y).data;
}

let Encode = {
  Writer: undefined,
  packByte: packByte,
  packInt16: packInt16,
  setType: ManagedPacketWriter$PacketFactory.setType,
  data: data,
  toBuffer: toBuffer
};

exports.unlockTypeToInt = unlockTypeToInt;
exports.unlockTypeFromInt = unlockTypeFromInt;
exports.makeError = makeError;
exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
/* @popstarfreas/packetfactory/packetreader Not a pure module */
