// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketType$TerrariaPacket from "../PacketType.js";
import * as ErrorAwarePacketReader$TerrariaPacket from "../ErrorAwarePacketReader.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";
import Packetreader from "@popstarfreas/packetfactory/packetreader";

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "playerId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "buff");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "time");
  if (e$2.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        playerId: e._0,
        buff: e$1._0,
        time: e$2._0
      }
    };
  } else {
    return e$2;
  }
}

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packInt32(ErrorAwarePacketWriter$TerrariaPacket.packUInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("PlayerBuffAdd")), self.playerId, "playerId"), self.buff, "buff"), self.time, "time"));
}

export {
  parse,
  toBuffer,
}
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
