// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let PacketType$TerrariaPacket = require("../../PacketType.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../../ErrorAwarePacketReader.js");
let ErrorAwarePacketWriter$TerrariaPacket = require("../../ErrorAwarePacketWriter.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "playerId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "x");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "y");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwarePacketReader$TerrariaPacket.readInt32(reader, "timeRemaining");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let e$4 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "context");
  if (e$4.TAG !== "Ok") {
    return e$4;
  }
  let e$5;
  switch (e$4._0) {
    case 0 :
      e$5 = {
        TAG: "Ok",
        _0: "ReviveFromDeath"
      };
      break;
    case 1 :
      e$5 = {
        TAG: "Ok",
        _0: "SpawningIntoWorld"
      };
      break;
    case 2 :
      e$5 = {
        TAG: "Ok",
        _0: "RecallFromItem"
      };
      break;
    default:
      e$5 = {
        TAG: "Error",
        _0: {
          context: "context",
          error: new Error("Unknown context")
        }
      };
  }
  if (e$5.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        playerId: e._0,
        x: e$1._0,
        y: e$2._0,
        timeRemaining: e$3._0,
        context: e$5._0
      }
    };
  } else {
    return e$5;
  }
}

let Decode = {
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  readInt16: ErrorAwarePacketReader$TerrariaPacket.readInt16,
  readInt32: ErrorAwarePacketReader$TerrariaPacket.readInt32,
  parse: parse
};

function toBuffer(self) {
  let match = self.context;
  let tmp;
  switch (match) {
    case "ReviveFromDeath" :
      tmp = 0;
      break;
    case "SpawningIntoWorld" :
      tmp = 1;
      break;
    case "RecallFromItem" :
      tmp = 2;
      break;
  }
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packInt32(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("PlayerSpawn")), self.playerId, "playerId"), self.x, "x"), self.y, "y"), self.timeRemaining, "timeRemaining"), tmp, "context"));
}

let Encode = {
  toBuffer: toBuffer
};

function toLatest(self) {
  return {
    playerId: self.playerId,
    x: self.x,
    y: self.y,
    timeRemaining: self.timeRemaining,
    numberOfDeathsPve: 0,
    numberOfDeathsPvp: 0,
    context: self.context
  };
}

function fromLatest(latest) {
  return {
    playerId: latest.playerId,
    x: latest.x,
    y: latest.y,
    timeRemaining: latest.timeRemaining,
    context: latest.context
  };
}

exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
exports.toLatest = toLatest;
exports.fromLatest = fromLatest;
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
