// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let BitFlags$TerrariaPacket = require("../../BitFlags.js");
let PacketType$TerrariaPacket = require("../../PacketType.js");
let ErrorAwarePacketReader$TerrariaPacket = require("../../ErrorAwarePacketReader.js");
let ErrorAwarePacketWriter$TerrariaPacket = require("../../ErrorAwarePacketWriter.js");
let Packetreader = require("@popstarfreas/packetfactory/packetreader").default;

function getDifficulty(difficultyFlags) {
  if (BitFlags$TerrariaPacket.flag2(difficultyFlags)) {
    return "Hardcore";
  } else if (BitFlags$TerrariaPacket.flag1(difficultyFlags)) {
    return "Mediumcore";
  } else {
    return "Softcore";
  }
}

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "playerId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "skinVariant");
  if (e$1.TAG !== "Ok") {
    return e$1;
  }
  let e$2 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "hair");
  if (e$2.TAG !== "Ok") {
    return e$2;
  }
  let e$3 = ErrorAwarePacketReader$TerrariaPacket.readString(reader, "name");
  if (e$3.TAG !== "Ok") {
    return e$3;
  }
  let e$4 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "hairDye");
  if (e$4.TAG !== "Ok") {
    return e$4;
  }
  let e$5 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "hideVisuals");
  if (e$5.TAG !== "Ok") {
    return e$5;
  }
  let e$6 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "hideVisuals2");
  if (e$6.TAG !== "Ok") {
    return e$6;
  }
  let e$7 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "hideMisc");
  if (e$7.TAG !== "Ok") {
    return e$7;
  }
  let e$8 = ErrorAwarePacketReader$TerrariaPacket.readColor(reader, "hairColor");
  if (e$8.TAG !== "Ok") {
    return e$8;
  }
  let e$9 = ErrorAwarePacketReader$TerrariaPacket.readColor(reader, "skinColor");
  if (e$9.TAG !== "Ok") {
    return e$9;
  }
  let e$10 = ErrorAwarePacketReader$TerrariaPacket.readColor(reader, "eyeColor");
  if (e$10.TAG !== "Ok") {
    return e$10;
  }
  let e$11 = ErrorAwarePacketReader$TerrariaPacket.readColor(reader, "shirtColor");
  if (e$11.TAG !== "Ok") {
    return e$11;
  }
  let e$12 = ErrorAwarePacketReader$TerrariaPacket.readColor(reader, "underShirtColor");
  if (e$12.TAG !== "Ok") {
    return e$12;
  }
  let e$13 = ErrorAwarePacketReader$TerrariaPacket.readColor(reader, "pantsColor");
  if (e$13.TAG !== "Ok") {
    return e$13;
  }
  let e$14 = ErrorAwarePacketReader$TerrariaPacket.readColor(reader, "shoeColor");
  if (e$14.TAG !== "Ok") {
    return e$14;
  }
  let e$15 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "difficultyFlags");
  if (e$15.TAG !== "Ok") {
    return e$15;
  }
  let difficultyFlags = BitFlags$TerrariaPacket.fromByte(e$15._0);
  let e$16 = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "torchFlags");
  if (e$16.TAG !== "Ok") {
    return e$16;
  }
  let torchFlags = BitFlags$TerrariaPacket.fromByte(e$16._0);
  let difficulty = getDifficulty(difficultyFlags);
  let extraAccessory = BitFlags$TerrariaPacket.flag3(difficultyFlags);
  let mode = BitFlags$TerrariaPacket.flag4(difficultyFlags) ? "Journey" : "Classic";
  let usingBiomeTorches = BitFlags$TerrariaPacket.flag1(torchFlags);
  let happyFunTorchTime = BitFlags$TerrariaPacket.flag2(torchFlags);
  let unlockedBiomeTorches = BitFlags$TerrariaPacket.flag3(torchFlags);
  return {
    TAG: "Ok",
    _0: {
      playerId: e._0,
      skinVariant: e$1._0,
      hair: e$2._0,
      name: e$3._0,
      hairDye: e$4._0,
      hideVisuals: e$5._0,
      hideVisuals2: e$6._0,
      hideMisc: e$7._0,
      hairColor: e$8._0,
      skinColor: e$9._0,
      eyeColor: e$10._0,
      shirtColor: e$11._0,
      underShirtColor: e$12._0,
      pantsColor: e$13._0,
      shoeColor: e$14._0,
      difficulty: difficulty,
      mode: mode,
      extraAccessory: extraAccessory,
      usingBiomeTorches: usingBiomeTorches,
      unlockedBiomeTorches: unlockedBiomeTorches,
      happyFunTorchTime: happyFunTorchTime
    }
  };
}

let Decode = {
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  readColor: ErrorAwarePacketReader$TerrariaPacket.readColor,
  readString: ErrorAwarePacketReader$TerrariaPacket.readString,
  getDifficulty: getDifficulty,
  parse: parse
};

function packDifficultyFlags(writer, difficulty, extraAccessory, mode) {
  let byte = 0;
  let tmp;
  switch (difficulty) {
    case "Softcore" :
      tmp = 0;
      break;
    case "Mediumcore" :
      tmp = 1;
      break;
    case "Hardcore" :
      tmp = 2;
      break;
  }
  byte = byte | tmp;
  byte = byte | (
    extraAccessory ? 4 : 0
  );
  byte = byte | (
    mode === "Journey" ? 8 : 0
  );
  return ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, byte, "difficultyFlags");
}

function packTorchFlags(writer, usingBiomeTorches, happyFunTorchTime, unlockedBiomeTorches) {
  let byte = 0;
  byte = byte | (
    usingBiomeTorches ? 1 : 0
  );
  byte = byte | (
    happyFunTorchTime ? 2 : 0
  );
  byte = byte | (
    unlockedBiomeTorches ? 4 : 0
  );
  return ErrorAwarePacketWriter$TerrariaPacket.packByte(writer, byte, "torchFlags");
}

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(packTorchFlags(packDifficultyFlags(ErrorAwarePacketWriter$TerrariaPacket.packColor(ErrorAwarePacketWriter$TerrariaPacket.packColor(ErrorAwarePacketWriter$TerrariaPacket.packColor(ErrorAwarePacketWriter$TerrariaPacket.packColor(ErrorAwarePacketWriter$TerrariaPacket.packColor(ErrorAwarePacketWriter$TerrariaPacket.packColor(ErrorAwarePacketWriter$TerrariaPacket.packColor(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packString(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketType$TerrariaPacket.toInt("PlayerInfo")), self.playerId, "playerId"), self.skinVariant, "skinVariant"), self.hair, "hair"), self.name, "name"), self.hairDye, "hairDye"), self.hideVisuals, "hideVisuals"), self.hideVisuals2, "hideVisuals2"), self.hideMisc, "hideMisc"), self.hairColor, "hairColor"), self.skinColor, "skinColor"), self.eyeColor, "eyeColor"), self.shirtColor, "shirtColor"), self.underShirtColor, "underShirtColor"), self.pantsColor, "pantsColor"), self.shoeColor, "shoeColor"), self.difficulty, self.extraAccessory, self.mode), self.usingBiomeTorches, self.happyFunTorchTime, self.unlockedBiomeTorches));
}

let Encode = {
  packByte: ErrorAwarePacketWriter$TerrariaPacket.packByte,
  packString: ErrorAwarePacketWriter$TerrariaPacket.packString,
  packColor: ErrorAwarePacketWriter$TerrariaPacket.packColor,
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  packDifficultyFlags: packDifficultyFlags,
  packTorchFlags: packTorchFlags,
  toBuffer: toBuffer
};

function toLatest(self) {
  return {
    playerId: self.playerId,
    skinVariant: self.skinVariant,
    hair: self.hair,
    name: self.name,
    hairDye: self.hairDye,
    hideVisuals: self.hideVisuals,
    hideVisuals2: self.hideVisuals2,
    hideMisc: self.hideMisc,
    hairColor: self.hairColor,
    skinColor: self.skinColor,
    eyeColor: self.eyeColor,
    shirtColor: self.shirtColor,
    underShirtColor: self.underShirtColor,
    pantsColor: self.pantsColor,
    shoeColor: self.shoeColor,
    difficulty: self.difficulty,
    mode: self.mode,
    extraAccessory: self.extraAccessory,
    usingBiomeTorches: self.usingBiomeTorches,
    unlockedBiomeTorches: self.unlockedBiomeTorches,
    happyFunTorchTime: self.happyFunTorchTime,
    unlockedSuperCart: false,
    enabledSuperCart: false,
    usedAegisCrystal: false,
    usedAegisFruit: false,
    usedArcaneCrystal: false,
    usedGalaxyPearl: false,
    usedGummyWorm: false,
    usedAmbrosia: false,
    ateArtisanBread: false
  };
}

function fromLatest(latest) {
  return {
    playerId: latest.playerId,
    skinVariant: latest.skinVariant,
    hair: latest.hair,
    name: latest.name,
    hairDye: latest.hairDye,
    hideVisuals: latest.hideVisuals,
    hideVisuals2: latest.hideVisuals2,
    hideMisc: latest.hideMisc,
    hairColor: latest.hairColor,
    skinColor: latest.skinColor,
    eyeColor: latest.eyeColor,
    shirtColor: latest.shirtColor,
    underShirtColor: latest.underShirtColor,
    pantsColor: latest.pantsColor,
    shoeColor: latest.shoeColor,
    difficulty: latest.difficulty,
    mode: latest.mode,
    extraAccessory: latest.extraAccessory,
    usingBiomeTorches: latest.usingBiomeTorches,
    unlockedBiomeTorches: latest.unlockedBiomeTorches,
    happyFunTorchTime: latest.happyFunTorchTime
  };
}

let Color;

exports.Color = Color;
exports.Decode = Decode;
exports.Encode = Encode;
exports.parse = parse;
exports.toBuffer = toBuffer;
exports.toLatest = toLatest;
exports.fromLatest = fromLatest;
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
