// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketTypeV1456$TerrariaPacket from "../PacketTypeV1456.js";
import * as ErrorAwarePacketReader$TerrariaPacket from "../ErrorAwarePacketReader.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";
import Packetreader from "@popstarfreas/packetfactory/packetreader";

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readByte(reader, "playerId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let buffs = [];
  let readBuffs = () => {
    while (true) {
      let e = ErrorAwarePacketReader$TerrariaPacket.readUInt16(reader, "buff");
      if (e.TAG !== "Ok") {
        return e;
      }
      let buff = e._0;
      if (buff === 0) {
        return {
          TAG: "Ok",
          _0: undefined
        };
      }
      buffs.push(buff);
      continue;
    };
  };
  let e$1 = readBuffs();
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        playerId: e._0,
        buffs: buffs
      }
    };
  } else {
    return e$1;
  }
}

let Decode = {
  readUInt16: ErrorAwarePacketReader$TerrariaPacket.readUInt16,
  readByte: ErrorAwarePacketReader$TerrariaPacket.readByte,
  parse: parse
};

function packBuffs(writer, buffs) {
  buffs.forEach((buff, idx) => {
    ErrorAwarePacketWriter$TerrariaPacket.packUInt16(writer, buff, `buff_` + idx.toString());
  });
  return ErrorAwarePacketWriter$TerrariaPacket.packUInt16(writer, 0, "buff_terminator");
}

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(packBuffs(ErrorAwarePacketWriter$TerrariaPacket.packByte(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketTypeV1456$TerrariaPacket.toInt("PlayerBuffsSet")), self.playerId, "playerId"), self.buffs));
}

let Encode = {
  packByte: ErrorAwarePacketWriter$TerrariaPacket.packByte,
  packUInt16: ErrorAwarePacketWriter$TerrariaPacket.packUInt16,
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  packBuffs: packBuffs,
  toBuffer: toBuffer
};

export {
  Decode,
  Encode,
  parse,
  toBuffer,
}
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
