// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketTypeV1456$TerrariaPacket from "../PacketTypeV1456.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";

function parse(_payload) {
  return {
    TAG: "Ok",
    _0: undefined
  };
}

let Decode = {
  parse: parse
};

function toBuffer(_self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketTypeV1456$TerrariaPacket.toInt("Ping")));
}

let Encode = {
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  toBuffer: toBuffer
};

export {
  Decode,
  Encode,
  parse,
  toBuffer,
}
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
