// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PacketTypeV1456$TerrariaPacket from "../PacketTypeV1456.js";
import * as ErrorAwarePacketReader$TerrariaPacket from "../ErrorAwarePacketReader.js";
import * as ErrorAwarePacketWriter$TerrariaPacket from "../ErrorAwarePacketWriter.js";
import Packetreader from "@popstarfreas/packetfactory/packetreader";

function parse(payload) {
  let reader = new Packetreader(payload);
  let e = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "chestId");
  if (e.TAG !== "Ok") {
    return e;
  }
  let e$1 = ErrorAwarePacketReader$TerrariaPacket.readInt16(reader, "newSize");
  if (e$1.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        chestId: e._0,
        newSize: e$1._0
      }
    };
  } else {
    return e$1;
  }
}

let Decode = {
  readInt16: ErrorAwarePacketReader$TerrariaPacket.readInt16,
  parse: parse
};

function toBuffer(self) {
  return ErrorAwarePacketWriter$TerrariaPacket.data(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.packInt16(ErrorAwarePacketWriter$TerrariaPacket.setType(ErrorAwarePacketWriter$TerrariaPacket.make(), PacketTypeV1456$TerrariaPacket.toInt("ChestResize")), self.chestId, "chestId"), self.newSize, "newSize"));
}

let Encode = {
  packInt16: ErrorAwarePacketWriter$TerrariaPacket.packInt16,
  setType: ErrorAwarePacketWriter$TerrariaPacket.setType,
  data: ErrorAwarePacketWriter$TerrariaPacket.data,
  toBuffer: toBuffer
};

export {
  Decode,
  Encode,
  parse,
  toBuffer,
}
/* ErrorAwarePacketWriter-TerrariaPacket Not a pure module */
