// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

let Stdlib_Array = require("@rescript/runtime/lib/js/Stdlib_Array.js");
let BitFlags$TerrariaPacket = require("./BitFlags.js");

function fromArray(a) {
  if (a.length === 16) {
    return a;
  }
}

function fromBitFlagsPair(a, b) {
  let array = Stdlib_Array.make(16, false);
  array[0] = BitFlags$TerrariaPacket.flag1(a);
  array[1] = BitFlags$TerrariaPacket.flag2(a);
  array[2] = BitFlags$TerrariaPacket.flag3(a);
  array[3] = BitFlags$TerrariaPacket.flag4(a);
  array[4] = BitFlags$TerrariaPacket.flag5(a);
  array[5] = BitFlags$TerrariaPacket.flag6(a);
  array[6] = BitFlags$TerrariaPacket.flag7(a);
  array[7] = BitFlags$TerrariaPacket.flag8(a);
  array[8] = BitFlags$TerrariaPacket.flag1(b);
  array[9] = BitFlags$TerrariaPacket.flag2(b);
  array[10] = BitFlags$TerrariaPacket.flag3(b);
  array[11] = BitFlags$TerrariaPacket.flag4(b);
  array[12] = BitFlags$TerrariaPacket.flag5(b);
  array[13] = BitFlags$TerrariaPacket.flag6(b);
  array[14] = BitFlags$TerrariaPacket.flag7(b);
  array[15] = BitFlags$TerrariaPacket.flag8(b);
  return array;
}

function toBitFlagsPair(self) {
  let a = BitFlags$TerrariaPacket.fromArray(self.slice(0, 8));
  let b = BitFlags$TerrariaPacket.fromArray(self.slice(8, 16));
  return [
    a,
    b
  ];
}

function asArray(self) {
  return self;
}

exports.fromArray = fromArray;
exports.asArray = asArray;
exports.fromBitFlagsPair = fromBitFlagsPair;
exports.toBitFlagsPair = toBitFlagsPair;
/* No side effect */
