// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function intoChunks(self, chunkSize) {
  let chunked = [];
  let len = self.length;
  let max = (Math.ceil(len / chunkSize) | 0) - 1 | 0;
  for (let i = 0; i <= max; ++i) {
    let __x = self.slice(i * chunkSize | 0, (i + 1 | 0) * chunkSize | 0);
    chunked.push(__x);
  }
  return chunked;
}

function getOr(self, index, or) {
  return Stdlib_Option.getOr(self[index], or);
}

export {
  intoChunks,
  getOr,
}
/* No side effect */
