// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toBufferResult(result) {
  if (result.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: result._0
    };
  } else {
    return {
      TAG: "Error",
      _0: result._0
    };
  }
}

exports.toBufferResult = toBufferResult;
/* No side effect */
