module ConnectRequest = PacketV1449_ConnectRequest
module Disconnect = PacketV1449_Disconnect
module PlayerSlotSet = PacketV1449_PlayerSlotSet
module PlayerInfo = PacketV1456_PlayerInfo
module PlayerInventorySlot = PacketV1456_PlayerInventorySlot
module WorldDataRequest = PacketV1449_WorldDataRequest
module WorldInfo = Packet_WorldInfo
module InitialTileSectionsRequest = PacketV1456_InitialTileSectionsRequest
module Status = PacketV1449_Status
module TileSectionSend = PacketV1456_TileSectionSend
module TileSectionFrame = PacketV1449_TileSectionFrame
module PlayerSpawn = PacketV1456_PlayerSpawn
module PlayerUpdate = Packet_PlayerUpdate
module PlayerActive = PacketV1449_PlayerActive
module PlayerHealth = PacketV1449_PlayerHealth
module TileModify = PacketV1449_TileModify
module TimeSet = PacketV1449_TimeSet
module DoorUse = PacketV1449_DoorUse
module TileSquareSend = PacketV1456_TileSquareSend
module ItemDropUpdate = Packet_ItemDropUpdate
module ItemOwner = Packet_ItemOwner
module NpcUpdate = Packet_NpcUpdate
module NpcItemStrike = PacketV1449_NpcItemStrike
module ProjectileSync = Packet_ProjectileSync
module NpcStrike = Packet_NpcStrike
module ProjectileDestroy = Packet_ProjectileDestroy
module PvpToggle = PacketV1449_PvpToggle
module ChestOpen = PacketV1449_ChestOpen
module ChestItem = PacketV1449_ChestItem
module ActiveContainerSync = PacketV1449_ActiveContainerSync
module ChestPlace = PacketV1449_ChestPlace
module HealEffect = PacketV1449_HealEffect
module Zones = PacketV1456_Zones
module PasswordRequired = PacketV1449_PasswordRequired
module PasswordSend = PacketV1449_PasswordSend
module ItemOwnerRemove = Packet_ItemOwnerRemove
module NpcTalk = PacketV1449_NpcTalk
module PlayerAnimation = PacketV1449_PlayerAnimation
module PlayerMana = PacketV1449_PlayerMana
module ManaEffect = PacketV1449_ManaEffect
module PlayerTeam = PacketV1449_PlayerTeam
module SignRead = PacketV1449_SignRead
module SignNew = PacketV1449_SignNew
module LiquidSet = PacketV1449_LiquidSet
module PlayerSpawnSelf = PacketV1449_PlayerSpawnSelf
module PlayerBuffsSet = PacketV1456_PlayerBuffsSet
module NpcSpecialEffect = PacketV1449_NpcSpecialEffect
module ChestOrTempleUnlock = PacketV1449_ChestOrTempleUnlock
module NpcBuffAdd = PacketV1449_NpcBuffAdd
module NpcBuffUpdate = PacketV1456_NpcBuffUpdate
module PlayerBuffAdd = PacketV1449_PlayerBuffAdd
module NpcNameUpdate = PacketV1449_NpcNameUpdate
module GoodEvilUpdate = PacketV1449_GoodEvilUpdate
module HarpPlay = PacketV1449_HarpPlay
module SwitchHit = PacketV1449_SwitchHit
module NpcHomeUpdate = PacketV1449_NpcHomeUpdate
module BossOrInvasionSpawn = PacketV1449_BossOrInvasionSpawn
module PlayerDodge = Packet_PlayerDodge
module TilePaint = PacketV1449_TilePaint
module WallPaint = PacketV1449_WallPaint
module Teleport = PacketV1456_Teleport
module PlayerHealOther = PacketV1449_PlayerHealOther
module DimensionsUpdate = PacketV1449_DimensionsUpdate
module ClientUuid = PacketV1449_ClientUuid
module ChestName = PacketV1449_ChestName
module NpcCatch = Packet_NpcCatch
module NpcRelease = PacketV1449_NpcRelease
module TravellingMerchantInventory = PacketV1456_TravellingMerchantInventory
module TeleportationPotion = PacketV1456_TeleportationPotion
module AnglerQuest = PacketV1449_AnglerQuest
module AnglerQuestComplete = PacketV1449_AnglerQuestComplete
module AnglerQuestsCompletedAmount = PacketV1449_AnglerQuestsCompletedAmount
module TemporaryAnimationCreate = PacketV1449_TemporaryAnimationCreate
module InvasionProgressReport = PacketV1449_InvasionProgressReport
module ObjectPlace = PacketV1449_ObjectPlace
module PlayerChestIndexSync = PacketV1449_PlayerChestIndexSync
module CombatNumberCreate = PacketV1449_CombatNumberCreate
module NetModuleLoad = Packet_NetModuleLoad
module NpcKillCount = PacketV1449_NpcKillCount
module PlayerStealth = PacketV1449_PlayerStealth
module ItemForceIntoNearestChest = PacketV1456_ItemForceIntoNearestChest
module TileEntityUpdate = PacketV1449_TileEntityUpdate
module TileEntityPlace = PacketV1449_TileEntityPlace
module ItemDropModify = PacketV1449_ItemDropModify
module ItemFramePlace = PacketV1449_ItemFramePlace
module ItemDropInstancedUpdate = Packet_ItemDropInstancedUpdate
module EmoteBubble = PacketV1449_EmoteBubble
module ExtraValueSync = PacketV1449_ExtraValueSync
module SocialHandshake = PacketV1449_SocialHandshake
module Unused = PacketV1456_DebugCommand
module PortalKill = PacketV1449_PortalKill
module PlayerTeleportPortal = PacketV1449_PlayerTeleportPortal
module NpcKilledNotification = PacketV1449_NpcKilledNotification
module EventNotification = PacketV1449_EventNotification
module MinionTargetUpdate = PacketV1449_MinionTargetUpdate
module NpcTeleportPortal = PacketV1449_NpcTeleportPortal
module ShieldStrengthsUpdate = PacketV1449_ShieldStrengthsUpdate
module NebulaLevelUp = PacketV1449_NebulaLevelUp
module MoonLordCountdown = PacketV1449_MoonLordCountdown
module NpcShopItem = PacketV1449_NpcShopItem
module GemLockToggle = PacketV1449_GemLockToggle
module SmokePoof = PacketV1449_SmokePoof
module ChatMessageSmart = PacketV1449_ChatMessageSmart
module WiredCannonShot = PacketV1449_WiredCannonShot
module MassWireOperation = PacketV1449_MassWireOperation
module MassWireOperationPay = PacketV1449_MassWireOperationPay
module PartyToggle = PacketV1449_PartyToggle
module TreeGrowFx = PacketV1449_TreeGrowFx
module CrystalInvasionStart = PacketV1449_CrystalInvasionStart
module CrystalInvasionWipeAll = PacketV1449_CrystalInvasionWipeAll
module MinionAttackTargetUpdate = PacketV1449_MinionAttackTargetUpdate
module CrystalInvasionSendWaitTime = PacketV1449_CrystalInvasionSendWaitTime
module PlayerDamage = PacketV1449_PlayerDamage
module PlayerDeath = PacketV1449_PlayerDeath
module CombatTextCreate = PacketV1449_CombatTextCreate
module Emoji = PacketV1449_Emoji
module TileEntityDisplayDollItemSync = PacketV1456_TileEntityDisplayDollItemSync
module TileEntityInteractionRequest = PacketV1449_TileEntityInteractionRequest
module WeaponsRackTryPlacing = PacketV1449_WeaponsRackTryPlacing
module TileEntityHatRackItemSync = PacketV1449_TileEntityHatRackItemSync
module TilePickingSync = PacketV1449_TilePickingSync
module RevengeMarkerSync = PacketV1449_RevengeMarkerSync
module RevengeMarkerRemove = PacketV1449_RevengeMarkerRemove
module GolfBallLandInCup = PacketV1449_GolfBallLandInCup
module ClientFinishConnectingToServer = PacketV1449_ClientFinishConnectingToServer
module NpcFishOut = PacketV1449_NpcFishOut
module NpcTamper = PacketV1449_NpcTamper
module LegacySoundPlay = PacketV1449_LegacySoundPlay
module FoodPlatterTryPlacing = PacketV1449_FoodPlatterTryPlacing
module PlayerLuckFactorsUpdate = PacketV1456_PlayerLuckFactorsUpdate
module PlayerDead = PacketV1449_PlayerDead
module CavernMonsterTypeSync = PacketV1449_CavernMonsterTypeSync
module NpcBuffRemovalRequest = PacketV1449_NpcBuffRemovalRequest
module ClientSyncedInventory = PacketV1449_ClientSyncedInventory
module CountsAsHostForGameplaySet = PacketV1449_CountsAsHostForGameplaySet
module CreditsOrSlimeTransform = PacketV1449_CreditsOrSlimeTransform
module LucyAxeMessage = PacketV1449_LucyAxeMessage
module PiggyBankVoidLensUpdate = PacketV1449_PiggyBankVoidLensUpdate
module DungeonDefendersEventAttemptSkipWait = PacketV1449_DungeonDefendersEventAttemptSkipWait
module HaveDryadDoStardewAnimation = PacketV1449_HaveDryadDoStardewAnimation
module ItemDropShimmeredUpdate = PacketV1449_ItemDropShimmeredUpdate
module ShimmerEffectOrCoinLuck = PacketV1456_ShimmerEffectOrCoinLuck
module LoadoutSwitch = PacketV1449_LoadoutSwitch
module ItemDropProtectedUpdate = PacketV1449_ItemDropProtectedUpdate
module DeadCellsDisplayJarTryPlacing = PacketV1456_DeadCellsDisplayJarTryPlacing
module PlayerSpectate = PacketV1456_PlayerSpectate
module ItemDropClear = PacketV1456_ItemDropClear
module PlayerItemUseSound = PacketV1456_PlayerItemUseSound
module NpcHurtByDebuff = PacketV1456_NpcHurtByDebuff
module Ping = PacketV1456_Ping
module ChestResize = PacketV1456_ChestResize
module LeashedEntityAnchorInsertItem = PacketV1456_LeashedEntityAnchorInsertItem
module PlayerTeamUpdate = PacketV1456_PlayerTeamUpdate
module PlayerTeamSwapSpawn = PacketV1456_PlayerTeamSwapSpawn
module SectionRequest = PacketV1456_SectionRequest
module ItemDropPosition = PacketV1456_ItemDropPosition
module HostToken = PacketV1456_HostToken
module DamageNPCAck = Packet_DamageNPCAck
module ServerInfo = Packet_ServerInfo
module PlayerPlatformInfo = Packet_PlayerPlatformInfo

type t =
  | ConnectRequest(ConnectRequest.t)
  | Disconnect(Disconnect.t)
  | PlayerSlotSet(PlayerSlotSet.t)
  | PlayerInfo(PlayerInfo.t)
  | PlayerInventorySlot(PlayerInventorySlot.t)
  | WorldDataRequest(WorldDataRequest.t)
  | WorldInfo(WorldInfo.t)
  | InitialTileSectionsRequest(InitialTileSectionsRequest.t)
  | Status(Status.t)
  | TileSectionSend(TileSectionSend.t)
  | TileSectionFrame(TileSectionFrame.t)
  | PlayerSpawn(PlayerSpawn.t)
  | PlayerUpdate(PlayerUpdate.t)
  | PlayerActive(PlayerActive.t)
  | PlayerHealth(PlayerHealth.t)
  | TileModify(TileModify.t)
  | TimeSet(TimeSet.t)
  | DoorUse(DoorUse.t)
  | TileSquareSend(TileSquareSend.t)
  | ItemDropUpdate(ItemDropUpdate.t)
  | ItemOwner(ItemOwner.t)
  | NpcUpdate(NpcUpdate.t)
  | NpcItemStrike(NpcItemStrike.t)
  | ProjectileSync(ProjectileSync.t)
  | NpcStrike(NpcStrike.t)
  | ProjectileDestroy(ProjectileDestroy.t)
  | PvpToggle(PvpToggle.t)
  | ChestOpen(ChestOpen.t)
  | ChestItem(ChestItem.t)
  | ActiveContainerSync(ActiveContainerSync.t)
  | ChestPlace(ChestPlace.t)
  | HealEffect(HealEffect.t)
  | Zones(Zones.t)
  | PasswordRequired(PasswordRequired.t)
  | PasswordSend(PasswordSend.t)
  | ItemOwnerRemove(ItemOwnerRemove.t)
  | NpcTalk(NpcTalk.t)
  | PlayerAnimation(PlayerAnimation.t)
  | PlayerMana(PlayerMana.t)
  | ManaEffect(ManaEffect.t)
  | PlayerTeam(PlayerTeam.t)
  | SignRead(SignRead.t)
  | SignNew(SignNew.t)
  | LiquidSet(LiquidSet.t)
  | PlayerSpawnSelf(PlayerSpawnSelf.t)
  | PlayerBuffsSet(PlayerBuffsSet.t)
  | NpcSpecialEffect(NpcSpecialEffect.t)
  | ChestOrTempleUnlock(ChestOrTempleUnlock.t)
  | NpcBuffAdd(NpcBuffAdd.t)
  | NpcBuffUpdate(NpcBuffUpdate.t)
  | PlayerBuffAdd(PlayerBuffAdd.t)
  | NpcNameUpdate(NpcNameUpdate.t)
  | GoodEvilUpdate(GoodEvilUpdate.t)
  | HarpPlay(HarpPlay.t)
  | SwitchHit(SwitchHit.t)
  | NpcHomeUpdate(NpcHomeUpdate.t)
  | BossOrInvasionSpawn(BossOrInvasionSpawn.t)
  | PlayerDodge(PlayerDodge.t)
  | TilePaint(TilePaint.t)
  | WallPaint(WallPaint.t)
  | Teleport(Teleport.t)
  | PlayerHealOther(PlayerHealOther.t)
  | DimensionsUpdate(DimensionsUpdate.t)
  | ClientUuid(ClientUuid.t)
  | ChestName(ChestName.t)
  | NpcCatch(NpcCatch.t)
  | NpcRelease(NpcRelease.t)
  | TravellingMerchantInventory(TravellingMerchantInventory.t)
  | TeleportationPotion(TeleportationPotion.t)
  | AnglerQuest(AnglerQuest.t)
  | AnglerQuestComplete(AnglerQuestComplete.t)
  | AnglerQuestsCompletedAmount(AnglerQuestsCompletedAmount.t)
  | TemporaryAnimationCreate(TemporaryAnimationCreate.t)
  | InvasionProgressReport(InvasionProgressReport.t)
  | ObjectPlace(ObjectPlace.t)
  | PlayerChestIndexSync(PlayerChestIndexSync.t)
  | CombatNumberCreate(CombatNumberCreate.t)
  | NetModuleLoad(NetModuleLoad.t)
  | NpcKillCount(NpcKillCount.t)
  | PlayerStealth(PlayerStealth.t)
  | ItemForceIntoNearestChest(ItemForceIntoNearestChest.t)
  | TileEntityUpdate(TileEntityUpdate.t)
  | TileEntityPlace(TileEntityPlace.t)
  | ItemDropModify(ItemDropModify.t)
  | ItemFramePlace(ItemFramePlace.t)
  | ItemDropInstancedUpdate(ItemDropInstancedUpdate.t)
  | EmoteBubble(EmoteBubble.t)
  | ExtraValueSync(ExtraValueSync.t)
  | SocialHandshake(SocialHandshake.t)
  | Unused(Unused.t)
  | PortalKill(PortalKill.t)
  | PlayerTeleportPortal(PlayerTeleportPortal.t)
  | NpcKilledNotification(NpcKilledNotification.t)
  | EventNotification(EventNotification.t)
  | MinionTargetUpdate(MinionTargetUpdate.t)
  | NpcTeleportPortal(NpcTeleportPortal.t)
  | ShieldStrengthsUpdate(ShieldStrengthsUpdate.t)
  | NebulaLevelUp(NebulaLevelUp.t)
  | MoonLordCountdown(MoonLordCountdown.t)
  | NpcShopItem(NpcShopItem.t)
  | GemLockToggle(GemLockToggle.t)
  | SmokePoof(SmokePoof.t)
  | ChatMessageSmart(ChatMessageSmart.t)
  | WiredCannonShot(WiredCannonShot.t)
  | MassWireOperation(MassWireOperation.t)
  | MassWireOperationPay(MassWireOperationPay.t)
  | PartyToggle(PartyToggle.t)
  | TreeGrowFx(TreeGrowFx.t)
  | CrystalInvasionStart(CrystalInvasionStart.t)
  | CrystalInvasionWipeAll(CrystalInvasionWipeAll.t)
  | MinionAttackTargetUpdate(MinionAttackTargetUpdate.t)
  | CrystalInvasionSendWaitTime(CrystalInvasionSendWaitTime.t)
  | PlayerDamage(PlayerDamage.t)
  | PlayerDeath(PlayerDeath.t)
  | CombatTextCreate(CombatTextCreate.t)
  | Emoji(Emoji.t)
  | TileEntityDisplayDollItemSync(TileEntityDisplayDollItemSync.t)
  | TileEntityInteractionRequest(TileEntityInteractionRequest.t)
  | WeaponsRackTryPlacing(WeaponsRackTryPlacing.t)
  | TileEntityHatRackItemSync(TileEntityHatRackItemSync.t)
  | TilePickingSync(TilePickingSync.t)
  | RevengeMarkerSync(RevengeMarkerSync.t)
  | RevengeMarkerRemove(RevengeMarkerRemove.t)
  | GolfBallLandInCup(GolfBallLandInCup.t)
  | ClientFinishConnectingToServer(ClientFinishConnectingToServer.t)
  | NpcFishOut(NpcFishOut.t)
  | NpcTamper(NpcTamper.t)
  | LegacySoundPlay(LegacySoundPlay.t)
  | FoodPlatterTryPlacing(FoodPlatterTryPlacing.t)
  | PlayerLuckFactorsUpdate(PlayerLuckFactorsUpdate.t)
  | PlayerDead(PlayerDead.t)
  | CavernMonsterTypeSync(CavernMonsterTypeSync.t)
  | NpcBuffRemovalRequest(NpcBuffRemovalRequest.t)
  | ClientSyncedInventory(ClientSyncedInventory.t)
  | CountsAsHostForGameplaySet(CountsAsHostForGameplaySet.t)
  | CreditsOrSlimeTransform(CreditsOrSlimeTransform.t)
  | LucyAxeMessage(LucyAxeMessage.t)
  | PiggyBankVoidLensUpdate(PiggyBankVoidLensUpdate.t)
  | DungeonDefendersEventAttemptSkipWait(DungeonDefendersEventAttemptSkipWait.t)
  | HaveDryadDoStardewAnimation(HaveDryadDoStardewAnimation.t)
  | ItemDropShimmeredUpdate(ItemDropShimmeredUpdate.t)
  | ShimmerEffectOrCoinLuck(ShimmerEffectOrCoinLuck.t)
  | LoadoutSwitch(LoadoutSwitch.t)
  | ItemDropProtectedUpdate(ItemDropProtectedUpdate.t)
  | DeadCellsDisplayJarTryPlacing(DeadCellsDisplayJarTryPlacing.t)
  | PlayerSpectate(PlayerSpectate.t)
  | ItemDropClear(ItemDropClear.t)
  | PlayerItemUseSound(PlayerItemUseSound.t)
  | NpcHurtByDebuff(NpcHurtByDebuff.t)
  | Ping(Ping.t)
  | ChestResize(ChestResize.t)
  | LeashedEntityAnchorInsertItem(LeashedEntityAnchorInsertItem.t)
  | PlayerTeamUpdate(PlayerTeamUpdate.t)
  | PlayerTeamSwapSpawn(PlayerTeamSwapSpawn.t)
  | SectionRequest(SectionRequest.t)
  | ItemDropPosition(ItemDropPosition.t)
  | HostToken(HostToken.t)
  | DamageNPCAck(DamageNPCAck.t)
  | ServerInfo(ServerInfo.t)
  | PlayerPlatformInfo(PlayerPlatformInfo.t)

module LazyPacket: {
  type lazyParsed<'a> = Lazy.t<result<'a, ErrorAwarePacketReader.readError>>
  type t =
    | ConnectRequest(lazyParsed<ConnectRequest.t>)
    | Disconnect(lazyParsed<Disconnect.t>)
    | PlayerSlotSet(lazyParsed<PlayerSlotSet.t>)
    | PlayerInfo(lazyParsed<PlayerInfo.t>)
    | PlayerInventorySlot(lazyParsed<PlayerInventorySlot.t>)
    | WorldDataRequest(lazyParsed<WorldDataRequest.t>)
    | WorldInfo(lazyParsed<WorldInfo.t>)
    | InitialTileSectionsRequest(lazyParsed<InitialTileSectionsRequest.t>)
    | Status(lazyParsed<Status.t>)
    | TileSectionSend(lazyParsed<TileSectionSend.t>)
    | TileSectionFrame(lazyParsed<TileSectionFrame.t>)
    | PlayerSpawn(lazyParsed<PlayerSpawn.t>)
    | PlayerUpdate(lazyParsed<PlayerUpdate.t>)
    | PlayerActive(lazyParsed<PlayerActive.t>)
    | PlayerHealth(lazyParsed<PlayerHealth.t>)
    | TileModify(lazyParsed<TileModify.t>)
    | TimeSet(lazyParsed<TimeSet.t>)
    | DoorUse(lazyParsed<DoorUse.t>)
    | TileSquareSend(lazyParsed<TileSquareSend.t>)
    | ItemDropUpdate(lazyParsed<ItemDropUpdate.t>)
    | ItemOwner(lazyParsed<ItemOwner.t>)
    | NpcUpdate(lazyParsed<NpcUpdate.t>)
    | NpcItemStrike(lazyParsed<NpcItemStrike.t>)
    | ProjectileSync(lazyParsed<ProjectileSync.t>)
    | NpcStrike(lazyParsed<NpcStrike.t>)
    | ProjectileDestroy(lazyParsed<ProjectileDestroy.t>)
    | PvpToggle(lazyParsed<PvpToggle.t>)
    | ChestOpen(lazyParsed<ChestOpen.t>)
    | ChestItem(lazyParsed<ChestItem.t>)
    | ActiveContainerSync(lazyParsed<ActiveContainerSync.t>)
    | ChestPlace(lazyParsed<ChestPlace.t>)
    | HealEffect(lazyParsed<HealEffect.t>)
    | Zones(lazyParsed<Zones.t>)
    | PasswordRequired(lazyParsed<PasswordRequired.t>)
    | PasswordSend(lazyParsed<PasswordSend.t>)
    | ItemOwnerRemove(lazyParsed<ItemOwnerRemove.t>)
    | NpcTalk(lazyParsed<NpcTalk.t>)
    | PlayerAnimation(lazyParsed<PlayerAnimation.t>)
    | PlayerMana(lazyParsed<PlayerMana.t>)
    | ManaEffect(lazyParsed<ManaEffect.t>)
    | PlayerTeam(lazyParsed<PlayerTeam.t>)
    | SignRead(lazyParsed<SignRead.t>)
    | SignNew(lazyParsed<SignNew.t>)
    | LiquidSet(lazyParsed<LiquidSet.t>)
    | PlayerSpawnSelf(lazyParsed<PlayerSpawnSelf.t>)
    | PlayerBuffsSet(lazyParsed<PlayerBuffsSet.t>)
    | NpcSpecialEffect(lazyParsed<NpcSpecialEffect.t>)
    | ChestOrTempleUnlock(lazyParsed<ChestOrTempleUnlock.t>)
    | NpcBuffAdd(lazyParsed<NpcBuffAdd.t>)
    | NpcBuffUpdate(lazyParsed<NpcBuffUpdate.t>)
    | PlayerBuffAdd(lazyParsed<PlayerBuffAdd.t>)
    | NpcNameUpdate(lazyParsed<NpcNameUpdate.t>)
    | GoodEvilUpdate(lazyParsed<GoodEvilUpdate.t>)
    | HarpPlay(lazyParsed<HarpPlay.t>)
    | SwitchHit(lazyParsed<SwitchHit.t>)
    | NpcHomeUpdate(lazyParsed<NpcHomeUpdate.t>)
    | BossOrInvasionSpawn(lazyParsed<BossOrInvasionSpawn.t>)
    | PlayerDodge(lazyParsed<PlayerDodge.t>)
    | TilePaint(lazyParsed<TilePaint.t>)
    | WallPaint(lazyParsed<WallPaint.t>)
    | Teleport(lazyParsed<Teleport.t>)
    | PlayerHealOther(lazyParsed<PlayerHealOther.t>)
    | DimensionsUpdate(lazyParsed<DimensionsUpdate.t>)
    | ClientUuid(lazyParsed<ClientUuid.t>)
    | ChestName(lazyParsed<ChestName.t>)
    | NpcCatch(lazyParsed<NpcCatch.t>)
    | NpcRelease(lazyParsed<NpcRelease.t>)
    | TravellingMerchantInventory(lazyParsed<TravellingMerchantInventory.t>)
    | TeleportationPotion(lazyParsed<TeleportationPotion.t>)
    | AnglerQuest(lazyParsed<AnglerQuest.t>)
    | AnglerQuestComplete(lazyParsed<AnglerQuestComplete.t>)
    | AnglerQuestsCompletedAmount(lazyParsed<AnglerQuestsCompletedAmount.t>)
    | TemporaryAnimationCreate(lazyParsed<TemporaryAnimationCreate.t>)
    | InvasionProgressReport(lazyParsed<InvasionProgressReport.t>)
    | ObjectPlace(lazyParsed<ObjectPlace.t>)
    | PlayerChestIndexSync(lazyParsed<PlayerChestIndexSync.t>)
    | CombatNumberCreate(lazyParsed<CombatNumberCreate.t>)
    | NetModuleLoad(lazyParsed<NetModuleLoad.t>)
    | NpcKillCount(lazyParsed<NpcKillCount.t>)
    | PlayerStealth(lazyParsed<PlayerStealth.t>)
    | ItemForceIntoNearestChest(lazyParsed<ItemForceIntoNearestChest.t>)
    | TileEntityUpdate(lazyParsed<TileEntityUpdate.t>)
    | TileEntityPlace(lazyParsed<TileEntityPlace.t>)
    | ItemDropModify(lazyParsed<ItemDropModify.t>)
    | ItemFramePlace(lazyParsed<ItemFramePlace.t>)
    | ItemDropInstancedUpdate(lazyParsed<ItemDropInstancedUpdate.t>)
    | EmoteBubble(lazyParsed<EmoteBubble.t>)
    | ExtraValueSync(lazyParsed<ExtraValueSync.t>)
    | SocialHandshake(lazyParsed<SocialHandshake.t>)
    | Unused(lazyParsed<Unused.t>)
    | PortalKill(lazyParsed<PortalKill.t>)
    | PlayerTeleportPortal(lazyParsed<PlayerTeleportPortal.t>)
    | NpcKilledNotification(lazyParsed<NpcKilledNotification.t>)
    | EventNotification(lazyParsed<EventNotification.t>)
    | MinionTargetUpdate(lazyParsed<MinionTargetUpdate.t>)
    | NpcTeleportPortal(lazyParsed<NpcTeleportPortal.t>)
    | ShieldStrengthsUpdate(lazyParsed<ShieldStrengthsUpdate.t>)
    | NebulaLevelUp(lazyParsed<NebulaLevelUp.t>)
    | MoonLordCountdown(lazyParsed<MoonLordCountdown.t>)
    | NpcShopItem(lazyParsed<NpcShopItem.t>)
    | GemLockToggle(lazyParsed<GemLockToggle.t>)
    | SmokePoof(lazyParsed<SmokePoof.t>)
    | ChatMessageSmart(lazyParsed<ChatMessageSmart.t>)
    | WiredCannonShot(lazyParsed<WiredCannonShot.t>)
    | MassWireOperation(lazyParsed<MassWireOperation.t>)
    | MassWireOperationPay(lazyParsed<MassWireOperationPay.t>)
    | PartyToggle(lazyParsed<PartyToggle.t>)
    | TreeGrowFx(lazyParsed<TreeGrowFx.t>)
    | CrystalInvasionStart(lazyParsed<CrystalInvasionStart.t>)
    | CrystalInvasionWipeAll(lazyParsed<CrystalInvasionWipeAll.t>)
    | MinionAttackTargetUpdate(lazyParsed<MinionAttackTargetUpdate.t>)
    | CrystalInvasionSendWaitTime(lazyParsed<CrystalInvasionSendWaitTime.t>)
    | PlayerDamage(lazyParsed<PlayerDamage.t>)
    | PlayerDeath(lazyParsed<PlayerDeath.t>)
    | CombatTextCreate(lazyParsed<CombatTextCreate.t>)
    | Emoji(lazyParsed<Emoji.t>)
    | TileEntityDisplayDollItemSync(lazyParsed<TileEntityDisplayDollItemSync.t>)
    | TileEntityInteractionRequest(lazyParsed<TileEntityInteractionRequest.t>)
    | WeaponsRackTryPlacing(lazyParsed<WeaponsRackTryPlacing.t>)
    | TileEntityHatRackItemSync(lazyParsed<TileEntityHatRackItemSync.t>)
    | TilePickingSync(lazyParsed<TilePickingSync.t>)
    | RevengeMarkerSync(lazyParsed<RevengeMarkerSync.t>)
    | RevengeMarkerRemove(lazyParsed<RevengeMarkerRemove.t>)
    | GolfBallLandInCup(lazyParsed<GolfBallLandInCup.t>)
    | ClientFinishConnectingToServer(lazyParsed<ClientFinishConnectingToServer.t>)
    | NpcFishOut(lazyParsed<NpcFishOut.t>)
    | NpcTamper(lazyParsed<NpcTamper.t>)
    | LegacySoundPlay(lazyParsed<LegacySoundPlay.t>)
    | FoodPlatterTryPlacing(lazyParsed<FoodPlatterTryPlacing.t>)
    | PlayerLuckFactorsUpdate(lazyParsed<PlayerLuckFactorsUpdate.t>)
    | PlayerDead(lazyParsed<PlayerDead.t>)
    | CavernMonsterTypeSync(lazyParsed<CavernMonsterTypeSync.t>)
    | NpcBuffRemovalRequest(lazyParsed<NpcBuffRemovalRequest.t>)
    | ClientSyncedInventory(lazyParsed<ClientSyncedInventory.t>)
    | CountsAsHostForGameplaySet(lazyParsed<CountsAsHostForGameplaySet.t>)
    | CreditsOrSlimeTransform(lazyParsed<CreditsOrSlimeTransform.t>)
    | LucyAxeMessage(lazyParsed<LucyAxeMessage.t>)
    | PiggyBankVoidLensUpdate(lazyParsed<PiggyBankVoidLensUpdate.t>)
    | DungeonDefendersEventAttemptSkipWait(lazyParsed<DungeonDefendersEventAttemptSkipWait.t>)
    | HaveDryadDoStardewAnimation(lazyParsed<HaveDryadDoStardewAnimation.t>)
    | ItemDropShimmeredUpdate(lazyParsed<ItemDropShimmeredUpdate.t>)
    | ShimmerEffectOrCoinLuck(lazyParsed<ShimmerEffectOrCoinLuck.t>)
    | LoadoutSwitch(lazyParsed<LoadoutSwitch.t>)
    | ItemDropProtectedUpdate(lazyParsed<ItemDropProtectedUpdate.t>)
    | DeadCellsDisplayJarTryPlacing(lazyParsed<DeadCellsDisplayJarTryPlacing.t>)
    | PlayerSpectate(lazyParsed<PlayerSpectate.t>)
    | ItemDropClear(lazyParsed<ItemDropClear.t>)
    | PlayerItemUseSound(lazyParsed<PlayerItemUseSound.t>)
    | NpcHurtByDebuff(lazyParsed<NpcHurtByDebuff.t>)
    | Ping(lazyParsed<Ping.t>)
    | ChestResize(lazyParsed<ChestResize.t>)
    | LeashedEntityAnchorInsertItem(lazyParsed<LeashedEntityAnchorInsertItem.t>)
    | PlayerTeamUpdate(lazyParsed<PlayerTeamUpdate.t>)
    | PlayerTeamSwapSpawn(lazyParsed<PlayerTeamSwapSpawn.t>)
    | SectionRequest(lazyParsed<SectionRequest.t>)
    | ItemDropPosition(lazyParsed<ItemDropPosition.t>)
    | HostToken(lazyParsed<HostToken.t>)
    | DamageNPCAck(lazyParsed<DamageNPCAck.t>)
    | ServerInfo(lazyParsed<ServerInfo.t>)
    | PlayerPlatformInfo(lazyParsed<PlayerPlatformInfo.t>)
  let toPacketName: t => string
}
let toBuffer: (t, bool) => ISerializer.toBufferResult
let toPacketName: t => string
