// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Lazy from "@rescript/runtime/lib/es6/Stdlib_Lazy.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";
import * as PacketType$TerrariaPacket from "./PacketType.js";
import * as PacketV1449_Emoji$TerrariaPacket from "./packetv1449/PacketV1449_Emoji.js";
import * as PacketV1449_Zones$TerrariaPacket from "./packetv1449/PacketV1449_Zones.js";
import * as PacketV1449_Status$TerrariaPacket from "./packetv1449/PacketV1449_Status.js";
import * as PacketV1449_Unused$TerrariaPacket from "./packetv1449/PacketV1449_Unused.js";
import * as PacketV1449_DoorUse$TerrariaPacket from "./packetv1449/PacketV1449_DoorUse.js";
import * as PacketV1449_NpcTalk$TerrariaPacket from "./packetv1449/PacketV1449_NpcTalk.js";
import * as PacketV1449_SignNew$TerrariaPacket from "./packetv1449/PacketV1449_SignNew.js";
import * as PacketV1449_TimeSet$TerrariaPacket from "./packetv1449/PacketV1449_TimeSet.js";
import * as PacketV1449_HarpPlay$TerrariaPacket from "./packetv1449/PacketV1449_HarpPlay.js";
import * as PacketV1449_NpcCatch$TerrariaPacket from "./packetv1449/PacketV1449_NpcCatch.js";
import * as PacketV1449_SignRead$TerrariaPacket from "./packetv1449/PacketV1449_SignRead.js";
import * as PacketV1449_Teleport$TerrariaPacket from "./packetv1449/PacketV1449_Teleport.js";
import * as PacketV1449_ChestItem$TerrariaPacket from "./packetv1449/PacketV1449_ChestItem.js";
import * as PacketV1449_ChestName$TerrariaPacket from "./packetv1449/PacketV1449_ChestName.js";
import * as PacketV1449_ChestOpen$TerrariaPacket from "./packetv1449/PacketV1449_ChestOpen.js";
import * as PacketV1449_ItemOwner$TerrariaPacket from "./packetv1449/PacketV1449_ItemOwner.js";
import * as PacketV1449_LiquidSet$TerrariaPacket from "./packetv1449/PacketV1449_LiquidSet.js";
import * as PacketV1449_NpcStrike$TerrariaPacket from "./packetv1449/PacketV1449_NpcStrike.js";
import * as PacketV1449_NpcTamper$TerrariaPacket from "./packetv1449/PacketV1449_NpcTamper.js";
import * as PacketV1449_NpcUpdate$TerrariaPacket from "./packetv1449/PacketV1449_NpcUpdate.js";
import * as PacketV1449_PvpToggle$TerrariaPacket from "./packetv1449/PacketV1449_PvpToggle.js";
import * as PacketV1449_SmokePoof$TerrariaPacket from "./packetv1449/PacketV1449_SmokePoof.js";
import * as PacketV1449_SwitchHit$TerrariaPacket from "./packetv1449/PacketV1449_SwitchHit.js";
import * as PacketV1449_TilePaint$TerrariaPacket from "./packetv1449/PacketV1449_TilePaint.js";
import * as PacketV1449_WallPaint$TerrariaPacket from "./packetv1449/PacketV1449_WallPaint.js";
import * as PacketV1449_WorldInfo$TerrariaPacket from "./packetv1449/PacketV1449_WorldInfo.js";
import * as PacketV1449_ChestPlace$TerrariaPacket from "./packetv1449/PacketV1449_ChestPlace.js";
import * as PacketV1449_ClientUuid$TerrariaPacket from "./packetv1449/PacketV1449_ClientUuid.js";
import * as PacketV1449_Disconnect$TerrariaPacket from "./packetv1449/PacketV1449_Disconnect.js";
import * as PacketV1449_HealEffect$TerrariaPacket from "./packetv1449/PacketV1449_HealEffect.js";
import * as PacketV1449_ManaEffect$TerrariaPacket from "./packetv1449/PacketV1449_ManaEffect.js";
import * as PacketV1449_NpcBuffAdd$TerrariaPacket from "./packetv1449/PacketV1449_NpcBuffAdd.js";
import * as PacketV1449_NpcFishOut$TerrariaPacket from "./packetv1449/PacketV1449_NpcFishOut.js";
import * as PacketV1449_NpcRelease$TerrariaPacket from "./packetv1449/PacketV1449_NpcRelease.js";
import * as PacketV1449_PlayerDead$TerrariaPacket from "./packetv1449/PacketV1449_PlayerDead.js";
import * as PacketV1449_PlayerInfo$TerrariaPacket from "./packetv1449/PacketV1449_PlayerInfo.js";
import * as PacketV1449_PlayerMana$TerrariaPacket from "./packetv1449/PacketV1449_PlayerMana.js";
import * as PacketV1449_PlayerTeam$TerrariaPacket from "./packetv1449/PacketV1449_PlayerTeam.js";
import * as PacketV1449_PortalKill$TerrariaPacket from "./packetv1449/PacketV1449_PortalKill.js";
import * as PacketV1449_TileModify$TerrariaPacket from "./packetv1449/PacketV1449_TileModify.js";
import * as PacketV1449_TreeGrowFx$TerrariaPacket from "./packetv1449/PacketV1449_TreeGrowFx.js";
import * as PacketV1449_AnglerQuest$TerrariaPacket from "./packetv1449/PacketV1449_AnglerQuest.js";
import * as PacketV1449_EmoteBubble$TerrariaPacket from "./packetv1449/PacketV1449_EmoteBubble.js";
import * as PacketV1449_NpcShopItem$TerrariaPacket from "./packetv1449/PacketV1449_NpcShopItem.js";
import * as PacketV1449_ObjectPlace$TerrariaPacket from "./packetv1449/PacketV1449_ObjectPlace.js";
import * as PacketV1449_PartyToggle$TerrariaPacket from "./packetv1449/PacketV1449_PartyToggle.js";
import * as PacketV1449_PlayerDeath$TerrariaPacket from "./packetv1449/PacketV1449_PlayerDeath.js";
import * as PacketV1449_PlayerDodge$TerrariaPacket from "./packetv1449/PacketV1449_PlayerDodge.js";
import * as PacketV1449_PlayerSpawn$TerrariaPacket from "./packetv1449/PacketV1449_PlayerSpawn.js";
import * as PacketV1449_NpcKillCount$TerrariaPacket from "./packetv1449/PacketV1449_NpcKillCount.js";
import * as PacketV1449_PasswordSend$TerrariaPacket from "./packetv1449/PacketV1449_PasswordSend.js";
import * as PacketV1449_PlayerActive$TerrariaPacket from "./packetv1449/PacketV1449_PlayerActive.js";
import * as PacketV1449_PlayerDamage$TerrariaPacket from "./packetv1449/PacketV1449_PlayerDamage.js";
import * as PacketV1449_PlayerHealth$TerrariaPacket from "./packetv1449/PacketV1449_PlayerHealth.js";
import * as PacketV1449_PlayerUpdate$TerrariaPacket from "./packetv1449/PacketV1449_PlayerUpdate.js";
import * as PacketV1449_GemLockToggle$TerrariaPacket from "./packetv1449/PacketV1449_GemLockToggle.js";
import * as PacketV1449_LoadoutSwitch$TerrariaPacket from "./packetv1449/PacketV1449_LoadoutSwitch.js";
import * as PacketV1449_NebulaLevelUp$TerrariaPacket from "./packetv1449/PacketV1449_NebulaLevelUp.js";
import * as PacketV1449_NetModuleLoad$TerrariaPacket from "./packetv1449/PacketV1449_NetModuleLoad.js";
import * as PacketV1449_NpcBuffUpdate$TerrariaPacket from "./packetv1449/PacketV1449_NpcBuffUpdate.js";
import * as PacketV1449_NpcHomeUpdate$TerrariaPacket from "./packetv1449/PacketV1449_NpcHomeUpdate.js";
import * as PacketV1449_NpcItemStrike$TerrariaPacket from "./packetv1449/PacketV1449_NpcItemStrike.js";
import * as PacketV1449_NpcNameUpdate$TerrariaPacket from "./packetv1449/PacketV1449_NpcNameUpdate.js";
import * as PacketV1449_PlayerBuffAdd$TerrariaPacket from "./packetv1449/PacketV1449_PlayerBuffAdd.js";
import * as PacketV1449_PlayerSlotSet$TerrariaPacket from "./packetv1449/PacketV1449_PlayerSlotSet.js";
import * as PacketV1449_PlayerStealth$TerrariaPacket from "./packetv1449/PacketV1449_PlayerStealth.js";
import * as PacketV1449_ConnectRequest$TerrariaPacket from "./packetv1449/PacketV1449_ConnectRequest.js";
import * as PacketV1449_ExtraValueSync$TerrariaPacket from "./packetv1449/PacketV1449_ExtraValueSync.js";
import * as PacketV1449_GoodEvilUpdate$TerrariaPacket from "./packetv1449/PacketV1449_GoodEvilUpdate.js";
import * as PacketV1449_ItemDropModify$TerrariaPacket from "./packetv1449/PacketV1449_ItemDropModify.js";
import * as PacketV1449_ItemDropUpdate$TerrariaPacket from "./packetv1449/PacketV1449_ItemDropUpdate.js";
import * as PacketV1449_ItemFramePlace$TerrariaPacket from "./packetv1449/PacketV1449_ItemFramePlace.js";
import * as PacketV1449_LucyAxeMessage$TerrariaPacket from "./packetv1449/PacketV1449_LucyAxeMessage.js";
import * as PacketV1449_PlayerBuffsSet$TerrariaPacket from "./packetv1449/PacketV1449_PlayerBuffsSet.js";
import * as PacketV1449_ProjectileSync$TerrariaPacket from "./packetv1449/PacketV1449_ProjectileSync.js";
import * as PacketV1449_TileSquareSend$TerrariaPacket from "./packetv1449/PacketV1449_TileSquareSend.js";
import * as PacketV1449_ItemOwnerRemove$TerrariaPacket from "./packetv1449/PacketV1449_ItemOwnerRemove.js";
import * as PacketV1449_LegacySoundPlay$TerrariaPacket from "./packetv1449/PacketV1449_LegacySoundPlay.js";
import * as PacketV1449_PlayerAnimation$TerrariaPacket from "./packetv1449/PacketV1449_PlayerAnimation.js";
import * as PacketV1449_PlayerHealOther$TerrariaPacket from "./packetv1449/PacketV1449_PlayerHealOther.js";
import * as PacketV1449_PlayerSpawnSelf$TerrariaPacket from "./packetv1449/PacketV1449_PlayerSpawnSelf.js";
import * as PacketV1449_SocialHandshake$TerrariaPacket from "./packetv1449/PacketV1449_SocialHandshake.js";
import * as PacketV1449_TileEntityPlace$TerrariaPacket from "./packetv1449/PacketV1449_TileEntityPlace.js";
import * as PacketV1449_TilePickingSync$TerrariaPacket from "./packetv1449/PacketV1449_TilePickingSync.js";
import * as PacketV1449_TileSectionSend$TerrariaPacket from "./packetv1449/PacketV1449_TileSectionSend.js";
import * as PacketV1449_WiredCannonShot$TerrariaPacket from "./packetv1449/PacketV1449_WiredCannonShot.js";
import * as PacketV1449_ChatMessageSmart$TerrariaPacket from "./packetv1449/PacketV1449_ChatMessageSmart.js";
import * as PacketV1449_CombatTextCreate$TerrariaPacket from "./packetv1449/PacketV1449_CombatTextCreate.js";
import * as PacketV1449_DimensionsUpdate$TerrariaPacket from "./packetv1449/PacketV1449_DimensionsUpdate.js";
import * as PacketV1449_NpcSpecialEffect$TerrariaPacket from "./packetv1449/PacketV1449_NpcSpecialEffect.js";
import * as PacketV1449_PasswordRequired$TerrariaPacket from "./packetv1449/PacketV1449_PasswordRequired.js";
import * as PacketV1449_TileEntityUpdate$TerrariaPacket from "./packetv1449/PacketV1449_TileEntityUpdate.js";
import * as PacketV1449_TileSectionFrame$TerrariaPacket from "./packetv1449/PacketV1449_TileSectionFrame.js";
import * as PacketV1449_WorldDataRequest$TerrariaPacket from "./packetv1449/PacketV1449_WorldDataRequest.js";
import * as PacketV1449_EventNotification$TerrariaPacket from "./packetv1449/PacketV1449_EventNotification.js";
import * as PacketV1449_GolfBallLandInCup$TerrariaPacket from "./packetv1449/PacketV1449_GolfBallLandInCup.js";
import * as PacketV1449_MassWireOperation$TerrariaPacket from "./packetv1449/PacketV1449_MassWireOperation.js";
import * as PacketV1449_MoonLordCountdown$TerrariaPacket from "./packetv1449/PacketV1449_MoonLordCountdown.js";
import * as PacketV1449_NpcTeleportPortal$TerrariaPacket from "./packetv1449/PacketV1449_NpcTeleportPortal.js";
import * as PacketV1449_ProjectileDestroy$TerrariaPacket from "./packetv1449/PacketV1449_ProjectileDestroy.js";
import * as PacketV1449_RevengeMarkerSync$TerrariaPacket from "./packetv1449/PacketV1449_RevengeMarkerSync.js";
import * as PacketV1449_CombatNumberCreate$TerrariaPacket from "./packetv1449/PacketV1449_CombatNumberCreate.js";
import * as PacketV1449_MinionTargetUpdate$TerrariaPacket from "./packetv1449/PacketV1449_MinionTargetUpdate.js";
import * as PacketV1449_ActiveContainerSync$TerrariaPacket from "./packetv1449/PacketV1449_ActiveContainerSync.js";
import * as PacketV1449_AnglerQuestComplete$TerrariaPacket from "./packetv1449/PacketV1449_AnglerQuestComplete.js";
import * as PacketV1449_BossOrInvasionSpawn$TerrariaPacket from "./packetv1449/PacketV1449_BossOrInvasionSpawn.js";
import * as PacketV1449_ChestOrTempleUnlock$TerrariaPacket from "./packetv1449/PacketV1449_ChestOrTempleUnlock.js";
import * as PacketV1449_PlayerInventorySlot$TerrariaPacket from "./packetv1449/PacketV1449_PlayerInventorySlot.js";
import * as PacketV1449_RevengeMarkerRemove$TerrariaPacket from "./packetv1449/PacketV1449_RevengeMarkerRemove.js";
import * as PacketV1449_TeleportationPotion$TerrariaPacket from "./packetv1449/PacketV1449_TeleportationPotion.js";
import * as PacketV1449_CrystalInvasionStart$TerrariaPacket from "./packetv1449/PacketV1449_CrystalInvasionStart.js";
import * as PacketV1449_MassWireOperationPay$TerrariaPacket from "./packetv1449/PacketV1449_MassWireOperationPay.js";
import * as PacketV1449_PlayerChestIndexSync$TerrariaPacket from "./packetv1449/PacketV1449_PlayerChestIndexSync.js";
import * as PacketV1449_PlayerTeleportPortal$TerrariaPacket from "./packetv1449/PacketV1449_PlayerTeleportPortal.js";
import * as PacketV1449_CavernMonsterTypeSync$TerrariaPacket from "./packetv1449/PacketV1449_CavernMonsterTypeSync.js";
import * as PacketV1449_ClientSyncedInventory$TerrariaPacket from "./packetv1449/PacketV1449_ClientSyncedInventory.js";
import * as PacketV1449_FoodPlatterTryPlacing$TerrariaPacket from "./packetv1449/PacketV1449_FoodPlatterTryPlacing.js";
import * as PacketV1449_NpcBuffRemovalRequest$TerrariaPacket from "./packetv1449/PacketV1449_NpcBuffRemovalRequest.js";
import * as PacketV1449_NpcKilledNotification$TerrariaPacket from "./packetv1449/PacketV1449_NpcKilledNotification.js";
import * as PacketV1449_ShieldStrengthsUpdate$TerrariaPacket from "./packetv1449/PacketV1449_ShieldStrengthsUpdate.js";
import * as PacketV1449_WeaponsRackTryPlacing$TerrariaPacket from "./packetv1449/PacketV1449_WeaponsRackTryPlacing.js";
import * as PacketV1449_CrystalInvasionWipeAll$TerrariaPacket from "./packetv1449/PacketV1449_CrystalInvasionWipeAll.js";
import * as PacketV1449_InvasionProgressReport$TerrariaPacket from "./packetv1449/PacketV1449_InvasionProgressReport.js";
import * as PacketV1449_CreditsOrSlimeTransform$TerrariaPacket from "./packetv1449/PacketV1449_CreditsOrSlimeTransform.js";
import * as PacketV1449_ItemDropInstancedUpdate$TerrariaPacket from "./packetv1449/PacketV1449_ItemDropInstancedUpdate.js";
import * as PacketV1449_ItemDropProtectedUpdate$TerrariaPacket from "./packetv1449/PacketV1449_ItemDropProtectedUpdate.js";
import * as PacketV1449_ItemDropShimmeredUpdate$TerrariaPacket from "./packetv1449/PacketV1449_ItemDropShimmeredUpdate.js";
import * as PacketV1449_PiggyBankVoidLensUpdate$TerrariaPacket from "./packetv1449/PacketV1449_PiggyBankVoidLensUpdate.js";
import * as PacketV1449_PlayerLuckFactorsUpdate$TerrariaPacket from "./packetv1449/PacketV1449_PlayerLuckFactorsUpdate.js";
import * as PacketV1449_ShimmerEffectOrCoinLuck$TerrariaPacket from "./packetv1449/PacketV1449_ShimmerEffectOrCoinLuck.js";
import * as PacketV1449_MinionAttackTargetUpdate$TerrariaPacket from "./packetv1449/PacketV1449_MinionAttackTargetUpdate.js";
import * as PacketV1449_TemporaryAnimationCreate$TerrariaPacket from "./packetv1449/PacketV1449_TemporaryAnimationCreate.js";
import * as PacketV1449_ItemForceIntoNearestChest$TerrariaPacket from "./packetv1449/PacketV1449_ItemForceIntoNearestChest.js";
import * as PacketV1449_TileEntityHatRackItemSync$TerrariaPacket from "./packetv1449/PacketV1449_TileEntityHatRackItemSync.js";
import * as PacketV1449_CountsAsHostForGameplaySet$TerrariaPacket from "./packetv1449/PacketV1449_CountsAsHostForGameplaySet.js";
import * as PacketV1449_InitialTileSectionsRequest$TerrariaPacket from "./packetv1449/PacketV1449_InitialTileSectionsRequest.js";
import * as PacketV1449_AnglerQuestsCompletedAmount$TerrariaPacket from "./packetv1449/PacketV1449_AnglerQuestsCompletedAmount.js";
import * as PacketV1449_CrystalInvasionSendWaitTime$TerrariaPacket from "./packetv1449/PacketV1449_CrystalInvasionSendWaitTime.js";
import * as PacketV1449_HaveDryadDoStardewAnimation$TerrariaPacket from "./packetv1449/PacketV1449_HaveDryadDoStardewAnimation.js";
import * as PacketV1449_TravellingMerchantInventory$TerrariaPacket from "./packetv1449/PacketV1449_TravellingMerchantInventory.js";
import * as PacketV1449_TileEntityInteractionRequest$TerrariaPacket from "./packetv1449/PacketV1449_TileEntityInteractionRequest.js";
import * as PacketV1449_TileEntityDisplayDollItemSync$TerrariaPacket from "./packetv1449/PacketV1449_TileEntityDisplayDollItemSync.js";
import * as PacketV1449_ClientFinishConnectingToServer$TerrariaPacket from "./packetv1449/PacketV1449_ClientFinishConnectingToServer.js";
import * as PacketV1449_DungeonDefendersEventAttemptSkipWait$TerrariaPacket from "./packetv1449/PacketV1449_DungeonDefendersEventAttemptSkipWait.js";

function packetTypeName(packetType) {
  switch (packetType) {
    case "ConnectRequest" :
      return "ConnectRequest";
    case "Disconnect" :
      return "Disconnect";
    case "PlayerSlotSet" :
      return "PlayerSlotSet";
    case "PlayerInfo" :
      return "PlayerInfo";
    case "PlayerInventorySlot" :
      return "PlayerInventorySlot";
    case "WorldDataRequest" :
      return "WorldDataRequest";
    case "WorldInfo" :
      return "WorldInfo";
    case "InitialTileSectionsRequest" :
      return "InitialTileSectionsRequest";
    case "Status" :
      return "Status";
    case "TileSectionSend" :
      return "TileSectionSend";
    case "TileSectionFrame" :
      return "TileSectionFrame";
    case "PlayerSpawn" :
      return "PlayerSpawn";
    case "PlayerUpdate" :
      return "PlayerUpdate";
    case "PlayerActive" :
      return "PlayerActive";
    case "PlayerHealth" :
      return "PlayerHealth";
    case "TileModify" :
      return "TileModify";
    case "TimeSet" :
      return "TimeSet";
    case "DoorUse" :
      return "DoorUse";
    case "TileSquareSend" :
      return "TileSquareSend";
    case "ItemDropUpdate" :
      return "ItemDropUpdate";
    case "ItemOwner" :
      return "ItemOwner";
    case "NpcUpdate" :
      return "NpcUpdate";
    case "NpcItemStrike" :
      return "NpcItemStrike";
    case "ProjectileSync" :
      return "ProjectileSync";
    case "NpcStrike" :
      return "NpcStrike";
    case "ProjectileDestroy" :
      return "ProjectileDestroy";
    case "PvpToggle" :
      return "PvpToggle";
    case "ChestOpen" :
      return "ChestOpen";
    case "ChestItem" :
      return "ChestItem";
    case "ActiveContainerSync" :
      return "ActiveContainerSync";
    case "ChestPlace" :
      return "ChestPlace";
    case "HealEffect" :
      return "HealEffect";
    case "Zones" :
      return "Zones";
    case "PasswordRequired" :
      return "PasswordRequired";
    case "PasswordSend" :
      return "PasswordSend";
    case "ItemOwnerRemove" :
      return "ItemOwnerRemove";
    case "NpcTalk" :
      return "NpcTalk";
    case "PlayerAnimation" :
      return "PlayerAnimation";
    case "PlayerMana" :
      return "PlayerMana";
    case "ManaEffect" :
      return "ManaEffect";
    case "PlayerTeam" :
      return "PlayerTeam";
    case "SignRead" :
      return "SignRead";
    case "SignNew" :
      return "SignNew";
    case "LiquidSet" :
      return "LiquidSet";
    case "PlayerSpawnSelf" :
      return "PlayerSpawnSelf";
    case "PlayerBuffsSet" :
      return "PlayerBuffsSet";
    case "NpcSpecialEffect" :
      return "NpcSpecialEffect";
    case "ChestOrTempleUnlock" :
      return "ChestOrTempleUnlock";
    case "NpcBuffAdd" :
      return "NpcBuffAdd";
    case "NpcBuffUpdate" :
      return "NpcBuffUpdate";
    case "PlayerBuffAdd" :
      return "PlayerBuffAdd";
    case "NpcNameUpdate" :
      return "NpcNameUpdate";
    case "GoodEvilUpdate" :
      return "GoodEvilUpdate";
    case "HarpPlay" :
      return "HarpPlay";
    case "SwitchHit" :
      return "SwitchHit";
    case "NpcHomeUpdate" :
      return "NpcHomeUpdate";
    case "BossOrInvasionSpawn" :
      return "BossOrInvasionSpawn";
    case "PlayerDodge" :
      return "PlayerDodge";
    case "TilePaint" :
      return "TilePaint";
    case "WallPaint" :
      return "WallPaint";
    case "Teleport" :
      return "Teleport";
    case "PlayerHealOther" :
      return "PlayerHealOther";
    case "DimensionsUpdate" :
      return "DimensionsUpdate";
    case "ClientUuid" :
      return "ClientUuid";
    case "ChestName" :
      return "ChestName";
    case "NpcCatch" :
      return "NpcCatch";
    case "NpcRelease" :
      return "NpcRelease";
    case "TravellingMerchantInventory" :
      return "TravellingMerchantInventory";
    case "TeleportationPotion" :
      return "TeleportationPotion";
    case "AnglerQuest" :
      return "AnglerQuest";
    case "AnglerQuestComplete" :
      return "AnglerQuestComplete";
    case "AnglerQuestsCompletedAmount" :
      return "AnglerQuestsCompletedAmount";
    case "TemporaryAnimationCreate" :
      return "TemporaryAnimationCreate";
    case "InvasionProgressReport" :
      return "InvasionProgressReport";
    case "ObjectPlace" :
      return "ObjectPlace";
    case "PlayerChestIndexSync" :
      return "PlayerChestIndexSync";
    case "CombatNumberCreate" :
      return "CombatNumberCreate";
    case "NetModuleLoad" :
      return "NetModuleLoad";
    case "NpcKillCount" :
      return "NpcKillCount";
    case "PlayerStealth" :
      return "PlayerStealth";
    case "ItemForceIntoNearestChest" :
      return "ItemForceIntoNearestChest";
    case "TileEntityUpdate" :
      return "TileEntityUpdate";
    case "TileEntityPlace" :
      return "TileEntityPlace";
    case "ItemDropModify" :
      return "ItemDropModify";
    case "ItemFramePlace" :
      return "ItemFramePlace";
    case "ItemDropInstancedUpdate" :
      return "ItemDropInstancedUpdate";
    case "EmoteBubble" :
      return "EmoteBubble";
    case "ExtraValueSync" :
      return "ExtraValueSync";
    case "SocialHandshake" :
      return "SocialHandshake";
    case "Unused" :
      return "Unused";
    case "PortalKill" :
      return "PortalKill";
    case "PlayerTeleportPortal" :
      return "PlayerTeleportPortal";
    case "NpcKilledNotification" :
      return "NpcKilledNotification";
    case "EventNotification" :
      return "EventNotification";
    case "MinionTargetUpdate" :
      return "MinionTargetUpdate";
    case "NpcTeleportPortal" :
      return "NpcTeleportPortal";
    case "ShieldStrengthsUpdate" :
      return "ShieldStrengthsUpdate";
    case "NebulaLevelUp" :
      return "NebulaLevelUp";
    case "MoonLordCountdown" :
      return "MoonLordCountdown";
    case "NpcShopItem" :
      return "NpcShopItem";
    case "GemLockToggle" :
      return "GemLockToggle";
    case "SmokePoof" :
      return "SmokePoof";
    case "ChatMessageSmart" :
      return "ChatMessageSmart";
    case "WiredCannonShot" :
      return "WiredCannonShot";
    case "MassWireOperation" :
      return "MassWireOperation";
    case "MassWireOperationPay" :
      return "MassWireOperationPay";
    case "PartyToggle" :
      return "PartyToggle";
    case "TreeGrowFx" :
      return "TreeGrowFx";
    case "CrystalInvasionStart" :
      return "CrystalInvasionStart";
    case "CrystalInvasionWipeAll" :
      return "CrystalInvasionWipeAll";
    case "MinionAttackTargetUpdate" :
      return "MinionAttackTargetUpdate";
    case "CrystalInvasionSendWaitTime" :
      return "CrystalInvasionSendWaitTime";
    case "PlayerDamage" :
      return "PlayerDamage";
    case "PlayerDeath" :
      return "PlayerDeath";
    case "CombatTextCreate" :
      return "CombatTextCreate";
    case "Emoji" :
      return "Emoji";
    case "TileEntityDisplayDollItemSync" :
      return "TileEntityDisplayDollItemSync";
    case "TileEntityInteractionRequest" :
      return "TileEntityInteractionRequest";
    case "WeaponsRackTryPlacing" :
      return "WeaponsRackTryPlacing";
    case "TileEntityHatRackItemSync" :
      return "TileEntityHatRackItemSync";
    case "TilePickingSync" :
      return "TilePickingSync";
    case "RevengeMarkerSync" :
      return "RevengeMarkerSync";
    case "RevengeMarkerRemove" :
      return "RevengeMarkerRemove";
    case "GolfBallLandInCup" :
      return "GolfBallLandInCup";
    case "ClientFinishConnectingToServer" :
      return "ClientFinishConnectingToServer";
    case "NpcFishOut" :
      return "NpcFishOut";
    case "NpcTamper" :
      return "NpcTamper";
    case "LegacySoundPlay" :
      return "LegacySoundPlay";
    case "FoodPlatterTryPlacing" :
      return "FoodPlatterTryPlacing";
    case "PlayerLuckFactorsUpdate" :
      return "PlayerLuckFactorsUpdate";
    case "PlayerDead" :
      return "PlayerDead";
    case "CavernMonsterTypeSync" :
      return "CavernMonsterTypeSync";
    case "NpcBuffRemovalRequest" :
      return "NpcBuffRemovalRequest";
    case "ClientSyncedInventory" :
      return "ClientSyncedInventory";
    case "CountsAsHostForGameplaySet" :
      return "CountsAsHostForGameplaySet";
    case "CreditsOrSlimeTransform" :
      return "CreditsOrSlimeTransform";
    case "LucyAxeMessage" :
      return "LucyAxeMessage";
    case "PiggyBankVoidLensUpdate" :
      return "PiggyBankVoidLensUpdate";
    case "DungeonDefendersEventAttemptSkipWait" :
      return "DungeonDefendersEventAttemptSkipWait";
    case "HaveDryadDoStardewAnimation" :
      return "HaveDryadDoStardewAnimation";
    case "ItemDropShimmeredUpdate" :
      return "ItemDropShimmeredUpdate";
    case "ShimmerEffectOrCoinLuck" :
      return "ShimmerEffectOrCoinLuck";
    case "LoadoutSwitch" :
      return "LoadoutSwitch";
    case "ItemDropProtectedUpdate" :
      return "ItemDropProtectedUpdate";
    case "DeadCellsDisplayJarTryPlacing" :
      return "DeadCellsDisplayJarTryPlacing";
    case "PlayerSpectate" :
      return "PlayerSpectate";
    case "ItemDropClear" :
      return "ItemDropClear";
    case "PlayerItemUseSound" :
      return "PlayerItemUseSound";
    case "NpcHurtByDebuff" :
      return "NpcHurtByDebuff";
    case "Ping" :
      return "Ping";
    case "ChestResize" :
      return "ChestResize";
    case "LeashedEntityAnchorInsertItem" :
      return "LeashedEntityAnchorInsertItem";
    case "PlayerTeamUpdate" :
      return "PlayerTeamUpdate";
    case "PlayerTeamSwapSpawn" :
      return "PlayerTeamSwapSpawn";
    case "SectionRequest" :
      return "SectionRequest";
    case "ItemDropPosition" :
      return "ItemDropPosition";
    case "HostToken" :
      return "HostToken";
  }
}

function addPacketContext(packetName, err) {
  return {
    context: "Packet " + packetName + ": " + err.context,
    error: err.error
  };
}

function mapPacket(result, packetName, fn) {
  return Stdlib_Result.mapError(Stdlib_Result.map(result, fn), e => ({
    TAG: "ReaderError",
    _0: addPacketContext(packetName, e)
  }));
}

function makeParsers(packetName, parse, toPacket, toLazyPacket) {
  let parseWrapped = (payload, _fromServer) => mapPacket(parse(payload), packetName, toPacket);
  let parseLazyWrapped = (payload, _fromServer) => ({
    TAG: "Ok",
    _0: toLazyPacket(Stdlib_Lazy.make(() => Stdlib_Result.mapError(parse(payload), e => addPacketContext(packetName, e))))
  });
  return {
    parse: parseWrapped,
    parseLazy: parseLazyWrapped
  };
}

function makeParsersWithFromServer(packetName, parse, toPacket, toLazyPacket) {
  let parseWrapped = (payload, fromServer) => mapPacket(parse(payload, fromServer), packetName, toPacket);
  let parseLazyWrapped = (payload, fromServer) => ({
    TAG: "Ok",
    _0: toLazyPacket(Stdlib_Lazy.make(() => Stdlib_Result.mapError(parse(payload, fromServer), e => addPacketContext(packetName, e))))
  });
  return {
    parse: parseWrapped,
    parseLazy: parseLazyWrapped
  };
}

function getParsers(packetType, fromServer) {
  let packetName = packetTypeName(packetType);
  switch (packetType) {
    case "ConnectRequest" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "ConnectRequestFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_ConnectRequest$TerrariaPacket.parse, a => ({
            TAG: "ConnectRequest",
            _0: a
          }), a => ({
            TAG: "ConnectRequest",
            _0: a
          }))
        };
      }
    case "Disconnect" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_Disconnect$TerrariaPacket.parse, a => ({
            TAG: "Disconnect",
            _0: a
          }), a => ({
            TAG: "Disconnect",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "DisconnectFromClient"
        };
      }
    case "PlayerSlotSet" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_PlayerSlotSet$TerrariaPacket.parse, a => ({
            TAG: "PlayerSlotSet",
            _0: a
          }), a => ({
            TAG: "PlayerSlotSet",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "PlayerSlotSetFromClient"
        };
      }
    case "PlayerInfo" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerInfo$TerrariaPacket.parse, a => ({
          TAG: "PlayerInfo",
          _0: a
        }), a => ({
          TAG: "PlayerInfo",
          _0: a
        }))
      };
    case "PlayerInventorySlot" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerInventorySlot$TerrariaPacket.parse, a => ({
          TAG: "PlayerInventorySlot",
          _0: a
        }), a => ({
          TAG: "PlayerInventorySlot",
          _0: a
        }))
      };
    case "WorldDataRequest" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "WorldDataRequestFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_WorldDataRequest$TerrariaPacket.parse, a => ({
            TAG: "WorldDataRequest",
            _0: a
          }), a => ({
            TAG: "WorldDataRequest",
            _0: a
          }))
        };
      }
    case "WorldInfo" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_WorldInfo$TerrariaPacket.parse, a => ({
            TAG: "WorldInfo",
            _0: a
          }), a => ({
            TAG: "WorldInfo",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "WorldInfoFromClient"
        };
      }
    case "InitialTileSectionsRequest" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "InitialTileSectionsRequestFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_InitialTileSectionsRequest$TerrariaPacket.parse, a => ({
            TAG: "InitialTileSectionsRequest",
            _0: a
          }), a => ({
            TAG: "InitialTileSectionsRequest",
            _0: a
          }))
        };
      }
    case "Status" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_Status$TerrariaPacket.parse, a => ({
            TAG: "Status",
            _0: a
          }), a => ({
            TAG: "Status",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "StatusFromClient"
        };
      }
    case "TileSectionSend" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_TileSectionSend$TerrariaPacket.parse, a => ({
            TAG: "TileSectionSend",
            _0: a
          }), a => ({
            TAG: "TileSectionSend",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "TileSectionSendFromClient"
        };
      }
    case "TileSectionFrame" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_TileSectionFrame$TerrariaPacket.parse, a => ({
            TAG: "TileSectionFrame",
            _0: a
          }), a => ({
            TAG: "TileSectionFrame",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "TileSectionFrameFromClient"
        };
      }
    case "PlayerSpawn" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerSpawn$TerrariaPacket.parse, a => ({
          TAG: "PlayerSpawn",
          _0: a
        }), a => ({
          TAG: "PlayerSpawn",
          _0: a
        }))
      };
    case "PlayerUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerUpdate$TerrariaPacket.parse, a => ({
          TAG: "PlayerUpdate",
          _0: a
        }), a => ({
          TAG: "PlayerUpdate",
          _0: a
        }))
      };
    case "PlayerActive" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_PlayerActive$TerrariaPacket.parse, a => ({
            TAG: "PlayerActive",
            _0: a
          }), a => ({
            TAG: "PlayerActive",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "PlayerActiveFromClient"
        };
      }
    case "PlayerHealth" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerHealth$TerrariaPacket.parse, a => ({
          TAG: "PlayerHealth",
          _0: a
        }), a => ({
          TAG: "PlayerHealth",
          _0: a
        }))
      };
    case "TileModify" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_TileModify$TerrariaPacket.parse, a => ({
          TAG: "TileModify",
          _0: a
        }), a => ({
          TAG: "TileModify",
          _0: a
        }))
      };
    case "TimeSet" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_TimeSet$TerrariaPacket.parse, a => ({
            TAG: "TimeSet",
            _0: a
          }), a => ({
            TAG: "TimeSet",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "TimeSetFromClient"
        };
      }
    case "DoorUse" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_DoorUse$TerrariaPacket.parse, a => ({
          TAG: "DoorUse",
          _0: a
        }), a => ({
          TAG: "DoorUse",
          _0: a
        }))
      };
    case "TileSquareSend" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_TileSquareSend$TerrariaPacket.parse, a => ({
          TAG: "TileSquareSend",
          _0: a
        }), a => ({
          TAG: "TileSquareSend",
          _0: a
        }))
      };
    case "ItemDropUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ItemDropUpdate$TerrariaPacket.parse, a => ({
          TAG: "ItemDropUpdate",
          _0: a
        }), a => ({
          TAG: "ItemDropUpdate",
          _0: a
        }))
      };
    case "ItemOwner" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ItemOwner$TerrariaPacket.parse, a => ({
          TAG: "ItemOwner",
          _0: a
        }), a => ({
          TAG: "ItemOwner",
          _0: a
        }))
      };
    case "NpcUpdate" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_NpcUpdate$TerrariaPacket.parse, a => ({
            TAG: "NpcUpdate",
            _0: a
          }), a => ({
            TAG: "NpcUpdate",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "NpcUpdateFromClient"
        };
      }
    case "NpcItemStrike" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_NpcItemStrike$TerrariaPacket.parse, a => ({
          TAG: "NpcItemStrike",
          _0: a
        }), a => ({
          TAG: "NpcItemStrike",
          _0: a
        }))
      };
    case "ProjectileSync" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ProjectileSync$TerrariaPacket.parse, a => ({
          TAG: "ProjectileSync",
          _0: a
        }), a => ({
          TAG: "ProjectileSync",
          _0: a
        }))
      };
    case "NpcStrike" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_NpcStrike$TerrariaPacket.parse, a => ({
          TAG: "NpcStrike",
          _0: a
        }), a => ({
          TAG: "NpcStrike",
          _0: a
        }))
      };
    case "ProjectileDestroy" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ProjectileDestroy$TerrariaPacket.parse, a => ({
          TAG: "ProjectileDestroy",
          _0: a
        }), a => ({
          TAG: "ProjectileDestroy",
          _0: a
        }))
      };
    case "PvpToggle" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PvpToggle$TerrariaPacket.parse, a => ({
          TAG: "PvpToggle",
          _0: a
        }), a => ({
          TAG: "PvpToggle",
          _0: a
        }))
      };
    case "ChestOpen" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "ChestOpenFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_ChestOpen$TerrariaPacket.parse, a => ({
            TAG: "ChestOpen",
            _0: a
          }), a => ({
            TAG: "ChestOpen",
            _0: a
          }))
        };
      }
    case "ChestItem" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ChestItem$TerrariaPacket.parse, a => ({
          TAG: "ChestItem",
          _0: a
        }), a => ({
          TAG: "ChestItem",
          _0: a
        }))
      };
    case "ActiveContainerSync" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ActiveContainerSync$TerrariaPacket.parse, a => ({
          TAG: "ActiveContainerSync",
          _0: a
        }), a => ({
          TAG: "ActiveContainerSync",
          _0: a
        }))
      };
    case "ChestPlace" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ChestPlace$TerrariaPacket.parse, a => ({
          TAG: "ChestPlace",
          _0: a
        }), a => ({
          TAG: "ChestPlace",
          _0: a
        }))
      };
    case "HealEffect" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_HealEffect$TerrariaPacket.parse, a => ({
          TAG: "HealEffect",
          _0: a
        }), a => ({
          TAG: "HealEffect",
          _0: a
        }))
      };
    case "Zones" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_Zones$TerrariaPacket.parse, a => ({
          TAG: "Zones",
          _0: a
        }), a => ({
          TAG: "Zones",
          _0: a
        }))
      };
    case "PasswordRequired" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_PasswordRequired$TerrariaPacket.parse, a => ({
            TAG: "PasswordRequired",
            _0: a
          }), a => ({
            TAG: "PasswordRequired",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "PasswordRequiredFromClient"
        };
      }
    case "PasswordSend" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "PasswordSendFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_PasswordSend$TerrariaPacket.parse, a => ({
            TAG: "PasswordSend",
            _0: a
          }), a => ({
            TAG: "PasswordSend",
            _0: a
          }))
        };
      }
    case "ItemOwnerRemove" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_ItemOwnerRemove$TerrariaPacket.parse, a => ({
            TAG: "ItemOwnerRemove",
            _0: a
          }), a => ({
            TAG: "ItemOwnerRemove",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "ItemOwnerRemoveFromClient"
        };
      }
    case "NpcTalk" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_NpcTalk$TerrariaPacket.parse, a => ({
          TAG: "NpcTalk",
          _0: a
        }), a => ({
          TAG: "NpcTalk",
          _0: a
        }))
      };
    case "PlayerAnimation" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerAnimation$TerrariaPacket.parse, a => ({
          TAG: "PlayerAnimation",
          _0: a
        }), a => ({
          TAG: "PlayerAnimation",
          _0: a
        }))
      };
    case "PlayerMana" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerMana$TerrariaPacket.parse, a => ({
          TAG: "PlayerMana",
          _0: a
        }), a => ({
          TAG: "PlayerMana",
          _0: a
        }))
      };
    case "ManaEffect" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ManaEffect$TerrariaPacket.parse, a => ({
          TAG: "ManaEffect",
          _0: a
        }), a => ({
          TAG: "ManaEffect",
          _0: a
        }))
      };
    case "PlayerTeam" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerTeam$TerrariaPacket.parse, a => ({
          TAG: "PlayerTeam",
          _0: a
        }), a => ({
          TAG: "PlayerTeam",
          _0: a
        }))
      };
    case "SignRead" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "SignReadFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_SignRead$TerrariaPacket.parse, a => ({
            TAG: "SignRead",
            _0: a
          }), a => ({
            TAG: "SignRead",
            _0: a
          }))
        };
      }
    case "SignNew" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_SignNew$TerrariaPacket.parse, a => ({
          TAG: "SignNew",
          _0: a
        }), a => ({
          TAG: "SignNew",
          _0: a
        }))
      };
    case "LiquidSet" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_LiquidSet$TerrariaPacket.parse, a => ({
          TAG: "LiquidSet",
          _0: a
        }), a => ({
          TAG: "LiquidSet",
          _0: a
        }))
      };
    case "PlayerSpawnSelf" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_PlayerSpawnSelf$TerrariaPacket.parse, a => ({
            TAG: "PlayerSpawnSelf",
            _0: a
          }), a => ({
            TAG: "PlayerSpawnSelf",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "PlayerSpawnSelfFromClient"
        };
      }
    case "PlayerBuffsSet" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerBuffsSet$TerrariaPacket.parse, a => ({
          TAG: "PlayerBuffsSet",
          _0: a
        }), a => ({
          TAG: "PlayerBuffsSet",
          _0: a
        }))
      };
    case "NpcSpecialEffect" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_NpcSpecialEffect$TerrariaPacket.parse, a => ({
          TAG: "NpcSpecialEffect",
          _0: a
        }), a => ({
          TAG: "NpcSpecialEffect",
          _0: a
        }))
      };
    case "ChestOrTempleUnlock" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ChestOrTempleUnlock$TerrariaPacket.parse, a => ({
          TAG: "ChestOrTempleUnlock",
          _0: a
        }), a => ({
          TAG: "ChestOrTempleUnlock",
          _0: a
        }))
      };
    case "NpcBuffAdd" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_NpcBuffAdd$TerrariaPacket.parse, a => ({
          TAG: "NpcBuffAdd",
          _0: a
        }), a => ({
          TAG: "NpcBuffAdd",
          _0: a
        }))
      };
    case "NpcBuffUpdate" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_NpcBuffUpdate$TerrariaPacket.parse, a => ({
            TAG: "NpcBuffUpdate",
            _0: a
          }), a => ({
            TAG: "NpcBuffUpdate",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "NpcBuffUpdateFromClient"
        };
      }
    case "PlayerBuffAdd" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerBuffAdd$TerrariaPacket.parse, a => ({
          TAG: "PlayerBuffAdd",
          _0: a
        }), a => ({
          TAG: "PlayerBuffAdd",
          _0: a
        }))
      };
    case "NpcNameUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, __x => PacketV1449_NpcNameUpdate$TerrariaPacket.parse(__x, fromServer), a => ({
          TAG: "NpcNameUpdate",
          _0: a
        }), a => ({
          TAG: "NpcNameUpdate",
          _0: a
        }))
      };
    case "GoodEvilUpdate" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_GoodEvilUpdate$TerrariaPacket.parse, a => ({
            TAG: "GoodEvilUpdate",
            _0: a
          }), a => ({
            TAG: "GoodEvilUpdate",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "GoodEvilUpdateFromClient"
        };
      }
    case "HarpPlay" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_HarpPlay$TerrariaPacket.parse, a => ({
          TAG: "HarpPlay",
          _0: a
        }), a => ({
          TAG: "HarpPlay",
          _0: a
        }))
      };
    case "SwitchHit" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_SwitchHit$TerrariaPacket.parse, a => ({
          TAG: "SwitchHit",
          _0: a
        }), a => ({
          TAG: "SwitchHit",
          _0: a
        }))
      };
    case "NpcHomeUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_NpcHomeUpdate$TerrariaPacket.parse, a => ({
          TAG: "NpcHomeUpdate",
          _0: a
        }), a => ({
          TAG: "NpcHomeUpdate",
          _0: a
        }))
      };
    case "BossOrInvasionSpawn" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "BossOrInvasionSpawnFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_BossOrInvasionSpawn$TerrariaPacket.parse, a => ({
            TAG: "BossOrInvasionSpawn",
            _0: a
          }), a => ({
            TAG: "BossOrInvasionSpawn",
            _0: a
          }))
        };
      }
    case "PlayerDodge" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerDodge$TerrariaPacket.parse, a => ({
          TAG: "PlayerDodge",
          _0: a
        }), a => ({
          TAG: "PlayerDodge",
          _0: a
        }))
      };
    case "TilePaint" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_TilePaint$TerrariaPacket.parse, a => ({
          TAG: "TilePaint",
          _0: a
        }), a => ({
          TAG: "TilePaint",
          _0: a
        }))
      };
    case "WallPaint" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_WallPaint$TerrariaPacket.parse, a => ({
          TAG: "WallPaint",
          _0: a
        }), a => ({
          TAG: "WallPaint",
          _0: a
        }))
      };
    case "Teleport" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_Teleport$TerrariaPacket.parse, a => ({
          TAG: "Teleport",
          _0: a
        }), a => ({
          TAG: "Teleport",
          _0: a
        }))
      };
    case "PlayerHealOther" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerHealOther$TerrariaPacket.parse, a => ({
          TAG: "PlayerHealOther",
          _0: a
        }), a => ({
          TAG: "PlayerHealOther",
          _0: a
        }))
      };
    case "DimensionsUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_DimensionsUpdate$TerrariaPacket.parse, a => ({
          TAG: "DimensionsUpdate",
          _0: a
        }), a => ({
          TAG: "DimensionsUpdate",
          _0: a
        }))
      };
    case "ClientUuid" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "ClientUuidFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_ClientUuid$TerrariaPacket.parse, a => ({
            TAG: "ClientUuid",
            _0: a
          }), a => ({
            TAG: "ClientUuid",
            _0: a
          }))
        };
      }
    case "ChestName" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ChestName$TerrariaPacket.parse, a => ({
          TAG: "ChestName",
          _0: a
        }), a => ({
          TAG: "ChestName",
          _0: a
        }))
      };
    case "NpcCatch" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "NpcCatchFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_NpcCatch$TerrariaPacket.parse, a => ({
            TAG: "NpcCatch",
            _0: a
          }), a => ({
            TAG: "NpcCatch",
            _0: a
          }))
        };
      }
    case "NpcRelease" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "NpcReleaseFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_NpcRelease$TerrariaPacket.parse, a => ({
            TAG: "NpcRelease",
            _0: a
          }), a => ({
            TAG: "NpcRelease",
            _0: a
          }))
        };
      }
    case "TravellingMerchantInventory" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_TravellingMerchantInventory$TerrariaPacket.parse, a => ({
            TAG: "TravellingMerchantInventory",
            _0: a
          }), a => ({
            TAG: "TravellingMerchantInventory",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "TravellingMerchantInventoryFromClient"
        };
      }
    case "TeleportationPotion" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_TeleportationPotion$TerrariaPacket.parse, a => ({
          TAG: "TeleportationPotion",
          _0: a
        }), a => ({
          TAG: "TeleportationPotion",
          _0: a
        }))
      };
    case "AnglerQuest" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_AnglerQuest$TerrariaPacket.parse, a => ({
            TAG: "AnglerQuest",
            _0: a
          }), a => ({
            TAG: "AnglerQuest",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "AnglerQuestFromClient"
        };
      }
    case "AnglerQuestComplete" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "AnglerQuestCompleteFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_AnglerQuestComplete$TerrariaPacket.parse, a => ({
            TAG: "AnglerQuestComplete",
            _0: a
          }), a => ({
            TAG: "AnglerQuestComplete",
            _0: a
          }))
        };
      }
    case "AnglerQuestsCompletedAmount" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_AnglerQuestsCompletedAmount$TerrariaPacket.parse, a => ({
          TAG: "AnglerQuestsCompletedAmount",
          _0: a
        }), a => ({
          TAG: "AnglerQuestsCompletedAmount",
          _0: a
        }))
      };
    case "TemporaryAnimationCreate" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_TemporaryAnimationCreate$TerrariaPacket.parse, a => ({
            TAG: "TemporaryAnimationCreate",
            _0: a
          }), a => ({
            TAG: "TemporaryAnimationCreate",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "TemporaryAnimationCreateFromClient"
        };
      }
    case "InvasionProgressReport" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_InvasionProgressReport$TerrariaPacket.parse, a => ({
            TAG: "InvasionProgressReport",
            _0: a
          }), a => ({
            TAG: "InvasionProgressReport",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "InvasionProgressReportFromClient"
        };
      }
    case "ObjectPlace" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ObjectPlace$TerrariaPacket.parse, a => ({
          TAG: "ObjectPlace",
          _0: a
        }), a => ({
          TAG: "ObjectPlace",
          _0: a
        }))
      };
    case "PlayerChestIndexSync" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_PlayerChestIndexSync$TerrariaPacket.parse, a => ({
            TAG: "PlayerChestIndexSync",
            _0: a
          }), a => ({
            TAG: "PlayerChestIndexSync",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "PlayerChestIndexSyncFromClient"
        };
      }
    case "CombatNumberCreate" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_CombatNumberCreate$TerrariaPacket.parse, a => ({
            TAG: "CombatNumberCreate",
            _0: a
          }), a => ({
            TAG: "CombatNumberCreate",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "CombatNumberCreateFromClient"
        };
      }
    case "NetModuleLoad" :
      return {
        TAG: "Ok",
        _0: makeParsersWithFromServer(packetName, PacketV1449_NetModuleLoad$TerrariaPacket.parse, a => ({
          TAG: "NetModuleLoad",
          _0: a
        }), a => ({
          TAG: "NetModuleLoad",
          _0: a
        }))
      };
    case "NpcKillCount" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_NpcKillCount$TerrariaPacket.parse, a => ({
            TAG: "NpcKillCount",
            _0: a
          }), a => ({
            TAG: "NpcKillCount",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "NpcKillCountFromClient"
        };
      }
    case "PlayerStealth" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerStealth$TerrariaPacket.parse, a => ({
          TAG: "PlayerStealth",
          _0: a
        }), a => ({
          TAG: "PlayerStealth",
          _0: a
        }))
      };
    case "ItemForceIntoNearestChest" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "ItemForceIntoNearestChestFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_ItemForceIntoNearestChest$TerrariaPacket.parse, a => ({
            TAG: "ItemForceIntoNearestChest",
            _0: a
          }), a => ({
            TAG: "ItemForceIntoNearestChest",
            _0: a
          }))
        };
      }
    case "TileEntityUpdate" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_TileEntityUpdate$TerrariaPacket.parse, a => ({
            TAG: "TileEntityUpdate",
            _0: a
          }), a => ({
            TAG: "TileEntityUpdate",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "TileEntityUpdateFromClient"
        };
      }
    case "TileEntityPlace" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "TileEntityPlaceFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_TileEntityPlace$TerrariaPacket.parse, a => ({
            TAG: "TileEntityPlace",
            _0: a
          }), a => ({
            TAG: "TileEntityPlace",
            _0: a
          }))
        };
      }
    case "ItemDropModify" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_ItemDropModify$TerrariaPacket.parse, a => ({
            TAG: "ItemDropModify",
            _0: a
          }), a => ({
            TAG: "ItemDropModify",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "ItemDropModifyFromClient"
        };
      }
    case "ItemFramePlace" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "ItemFramePlaceFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_ItemFramePlace$TerrariaPacket.parse, a => ({
            TAG: "ItemFramePlace",
            _0: a
          }), a => ({
            TAG: "ItemFramePlace",
            _0: a
          }))
        };
      }
    case "ItemDropInstancedUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ItemDropInstancedUpdate$TerrariaPacket.parse, a => ({
          TAG: "ItemDropInstancedUpdate",
          _0: a
        }), a => ({
          TAG: "ItemDropInstancedUpdate",
          _0: a
        }))
      };
    case "EmoteBubble" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_EmoteBubble$TerrariaPacket.parse, a => ({
            TAG: "EmoteBubble",
            _0: a
          }), a => ({
            TAG: "EmoteBubble",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "EmoteBubbleFromClient"
        };
      }
    case "ExtraValueSync" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ExtraValueSync$TerrariaPacket.parse, a => ({
          TAG: "ExtraValueSync",
          _0: a
        }), a => ({
          TAG: "ExtraValueSync",
          _0: a
        }))
      };
    case "SocialHandshake" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_SocialHandshake$TerrariaPacket.parse, a => ({
          TAG: "SocialHandshake",
          _0: a
        }), a => ({
          TAG: "SocialHandshake",
          _0: a
        }))
      };
    case "Unused" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_Unused$TerrariaPacket.parse, a => ({
          TAG: "Unused",
          _0: a
        }), a => ({
          TAG: "Unused",
          _0: a
        }))
      };
    case "PortalKill" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "PortalKillFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_PortalKill$TerrariaPacket.parse, a => ({
            TAG: "PortalKill",
            _0: a
          }), a => ({
            TAG: "PortalKill",
            _0: a
          }))
        };
      }
    case "PlayerTeleportPortal" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerTeleportPortal$TerrariaPacket.parse, a => ({
          TAG: "PlayerTeleportPortal",
          _0: a
        }), a => ({
          TAG: "PlayerTeleportPortal",
          _0: a
        }))
      };
    case "NpcKilledNotification" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_NpcKilledNotification$TerrariaPacket.parse, a => ({
            TAG: "NpcKilledNotification",
            _0: a
          }), a => ({
            TAG: "NpcKilledNotification",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "NpcKilledNotificationFromClient"
        };
      }
    case "EventNotification" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_EventNotification$TerrariaPacket.parse, a => ({
            TAG: "EventNotification",
            _0: a
          }), a => ({
            TAG: "EventNotification",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "EventNotificationFromClient"
        };
      }
    case "MinionTargetUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_MinionTargetUpdate$TerrariaPacket.parse, a => ({
          TAG: "MinionTargetUpdate",
          _0: a
        }), a => ({
          TAG: "MinionTargetUpdate",
          _0: a
        }))
      };
    case "NpcTeleportPortal" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_NpcTeleportPortal$TerrariaPacket.parse, a => ({
          TAG: "NpcTeleportPortal",
          _0: a
        }), a => ({
          TAG: "NpcTeleportPortal",
          _0: a
        }))
      };
    case "ShieldStrengthsUpdate" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_ShieldStrengthsUpdate$TerrariaPacket.parse, a => ({
            TAG: "ShieldStrengthsUpdate",
            _0: a
          }), a => ({
            TAG: "ShieldStrengthsUpdate",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "ShieldStrengthsUpdateFromClient"
        };
      }
    case "NebulaLevelUp" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_NebulaLevelUp$TerrariaPacket.parse, a => ({
          TAG: "NebulaLevelUp",
          _0: a
        }), a => ({
          TAG: "NebulaLevelUp",
          _0: a
        }))
      };
    case "MoonLordCountdown" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_MoonLordCountdown$TerrariaPacket.parse, a => ({
            TAG: "MoonLordCountdown",
            _0: a
          }), a => ({
            TAG: "MoonLordCountdown",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "MoonLordCountdownFromClient"
        };
      }
    case "NpcShopItem" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_NpcShopItem$TerrariaPacket.parse, a => ({
            TAG: "NpcShopItem",
            _0: a
          }), a => ({
            TAG: "NpcShopItem",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "NpcShopItemFromClient"
        };
      }
    case "GemLockToggle" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "GemLockToggleFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_GemLockToggle$TerrariaPacket.parse, a => ({
            TAG: "GemLockToggle",
            _0: a
          }), a => ({
            TAG: "GemLockToggle",
            _0: a
          }))
        };
      }
    case "SmokePoof" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_SmokePoof$TerrariaPacket.parse, a => ({
            TAG: "SmokePoof",
            _0: a
          }), a => ({
            TAG: "SmokePoof",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "SmokePoofFromClient"
        };
      }
    case "ChatMessageSmart" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_ChatMessageSmart$TerrariaPacket.parse, a => ({
            TAG: "ChatMessageSmart",
            _0: a
          }), a => ({
            TAG: "ChatMessageSmart",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "ChatMessageSmartFromClient"
        };
      }
    case "WiredCannonShot" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_WiredCannonShot$TerrariaPacket.parse, a => ({
            TAG: "WiredCannonShot",
            _0: a
          }), a => ({
            TAG: "WiredCannonShot",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "WiredCannonShotFromClient"
        };
      }
    case "MassWireOperation" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "MassWireOperationFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_MassWireOperation$TerrariaPacket.parse, a => ({
            TAG: "MassWireOperation",
            _0: a
          }), a => ({
            TAG: "MassWireOperation",
            _0: a
          }))
        };
      }
    case "MassWireOperationPay" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_MassWireOperationPay$TerrariaPacket.parse, a => ({
            TAG: "MassWireOperationPay",
            _0: a
          }), a => ({
            TAG: "MassWireOperationPay",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "MassWireOperationPayFromClient"
        };
      }
    case "PartyToggle" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "PartyToggleFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_PartyToggle$TerrariaPacket.parse, a => ({
            TAG: "PartyToggle",
            _0: a
          }), a => ({
            TAG: "PartyToggle",
            _0: a
          }))
        };
      }
    case "TreeGrowFx" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_TreeGrowFx$TerrariaPacket.parse, a => ({
          TAG: "TreeGrowFx",
          _0: a
        }), a => ({
          TAG: "TreeGrowFx",
          _0: a
        }))
      };
    case "CrystalInvasionStart" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "CrystalInvasionStartFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_CrystalInvasionStart$TerrariaPacket.parse, a => ({
            TAG: "CrystalInvasionStart",
            _0: a
          }), a => ({
            TAG: "CrystalInvasionStart",
            _0: a
          }))
        };
      }
    case "CrystalInvasionWipeAll" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_CrystalInvasionWipeAll$TerrariaPacket.parse, a => ({
            TAG: "CrystalInvasionWipeAll",
            _0: a
          }), a => ({
            TAG: "CrystalInvasionWipeAll",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "CrystalInvasionWipeAllFromClient"
        };
      }
    case "MinionAttackTargetUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_MinionAttackTargetUpdate$TerrariaPacket.parse, a => ({
          TAG: "MinionAttackTargetUpdate",
          _0: a
        }), a => ({
          TAG: "MinionAttackTargetUpdate",
          _0: a
        }))
      };
    case "CrystalInvasionSendWaitTime" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_CrystalInvasionSendWaitTime$TerrariaPacket.parse, a => ({
            TAG: "CrystalInvasionSendWaitTime",
            _0: a
          }), a => ({
            TAG: "CrystalInvasionSendWaitTime",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "CrystalInvasionSendWaitTimeFromClient"
        };
      }
    case "PlayerDamage" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerDamage$TerrariaPacket.parse, a => ({
          TAG: "PlayerDamage",
          _0: a
        }), a => ({
          TAG: "PlayerDamage",
          _0: a
        }))
      };
    case "PlayerDeath" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerDeath$TerrariaPacket.parse, a => ({
          TAG: "PlayerDeath",
          _0: a
        }), a => ({
          TAG: "PlayerDeath",
          _0: a
        }))
      };
    case "CombatTextCreate" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_CombatTextCreate$TerrariaPacket.parse, a => ({
            TAG: "CombatTextCreate",
            _0: a
          }), a => ({
            TAG: "CombatTextCreate",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "CombatTextCreateFromClient"
        };
      }
    case "Emoji" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "EmojiFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_Emoji$TerrariaPacket.parse, a => ({
            TAG: "Emoji",
            _0: a
          }), a => ({
            TAG: "Emoji",
            _0: a
          }))
        };
      }
    case "TileEntityDisplayDollItemSync" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_TileEntityDisplayDollItemSync$TerrariaPacket.parse, a => ({
          TAG: "TileEntityDisplayDollItemSync",
          _0: a
        }), a => ({
          TAG: "TileEntityDisplayDollItemSync",
          _0: a
        }))
      };
    case "TileEntityInteractionRequest" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_TileEntityInteractionRequest$TerrariaPacket.parse, a => ({
          TAG: "TileEntityInteractionRequest",
          _0: a
        }), a => ({
          TAG: "TileEntityInteractionRequest",
          _0: a
        }))
      };
    case "WeaponsRackTryPlacing" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "WeaponsRackTryPlacingFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_WeaponsRackTryPlacing$TerrariaPacket.parse, a => ({
            TAG: "WeaponsRackTryPlacing",
            _0: a
          }), a => ({
            TAG: "WeaponsRackTryPlacing",
            _0: a
          }))
        };
      }
    case "TileEntityHatRackItemSync" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_TileEntityHatRackItemSync$TerrariaPacket.parse, a => ({
          TAG: "TileEntityHatRackItemSync",
          _0: a
        }), a => ({
          TAG: "TileEntityHatRackItemSync",
          _0: a
        }))
      };
    case "TilePickingSync" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_TilePickingSync$TerrariaPacket.parse, a => ({
          TAG: "TilePickingSync",
          _0: a
        }), a => ({
          TAG: "TilePickingSync",
          _0: a
        }))
      };
    case "RevengeMarkerSync" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_RevengeMarkerSync$TerrariaPacket.parse, a => ({
            TAG: "RevengeMarkerSync",
            _0: a
          }), a => ({
            TAG: "RevengeMarkerSync",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "RevengeMarkerSyncFromClient"
        };
      }
    case "RevengeMarkerRemove" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_RevengeMarkerRemove$TerrariaPacket.parse, a => ({
            TAG: "RevengeMarkerRemove",
            _0: a
          }), a => ({
            TAG: "RevengeMarkerRemove",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "RevengeMarkerRemoveFromClient"
        };
      }
    case "GolfBallLandInCup" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_GolfBallLandInCup$TerrariaPacket.parse, a => ({
          TAG: "GolfBallLandInCup",
          _0: a
        }), a => ({
          TAG: "GolfBallLandInCup",
          _0: a
        }))
      };
    case "ClientFinishConnectingToServer" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_ClientFinishConnectingToServer$TerrariaPacket.parse, a => ({
            TAG: "ClientFinishConnectingToServer",
            _0: a
          }), a => ({
            TAG: "ClientFinishConnectingToServer",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "ClientFinishConnectingToServerFromClient"
        };
      }
    case "NpcFishOut" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "NpcFishOutFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_NpcFishOut$TerrariaPacket.parse, a => ({
            TAG: "NpcFishOut",
            _0: a
          }), a => ({
            TAG: "NpcFishOut",
            _0: a
          }))
        };
      }
    case "NpcTamper" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_NpcTamper$TerrariaPacket.parse, a => ({
            TAG: "NpcTamper",
            _0: a
          }), a => ({
            TAG: "NpcTamper",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "NpcTamperFromClient"
        };
      }
    case "LegacySoundPlay" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_LegacySoundPlay$TerrariaPacket.parse, a => ({
            TAG: "LegacySoundPlay",
            _0: a
          }), a => ({
            TAG: "LegacySoundPlay",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "LegacySoundPlayFromClient"
        };
      }
    case "FoodPlatterTryPlacing" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "FoodPlatterTryPlacingFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_FoodPlatterTryPlacing$TerrariaPacket.parse, a => ({
            TAG: "FoodPlatterTryPlacing",
            _0: a
          }), a => ({
            TAG: "FoodPlatterTryPlacing",
            _0: a
          }))
        };
      }
    case "PlayerLuckFactorsUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PlayerLuckFactorsUpdate$TerrariaPacket.parse, a => ({
          TAG: "PlayerLuckFactorsUpdate",
          _0: a
        }), a => ({
          TAG: "PlayerLuckFactorsUpdate",
          _0: a
        }))
      };
    case "PlayerDead" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_PlayerDead$TerrariaPacket.parse, a => ({
            TAG: "PlayerDead",
            _0: a
          }), a => ({
            TAG: "PlayerDead",
            _0: a
          }))
        };
      } else {
        return {
          TAG: "Error",
          _0: "PlayerDeadFromClient"
        };
      }
    case "CavernMonsterTypeSync" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_CavernMonsterTypeSync$TerrariaPacket.parse, a => ({
          TAG: "CavernMonsterTypeSync",
          _0: a
        }), a => ({
          TAG: "CavernMonsterTypeSync",
          _0: a
        }))
      };
    case "NpcBuffRemovalRequest" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "NpcBuffRemovalRequestFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_NpcBuffRemovalRequest$TerrariaPacket.parse, a => ({
            TAG: "NpcBuffRemovalRequest",
            _0: a
          }), a => ({
            TAG: "NpcBuffRemovalRequest",
            _0: a
          }))
        };
      }
    case "ClientSyncedInventory" :
      if (fromServer) {
        return {
          TAG: "Error",
          _0: "ClientSyncedInventoryFromServer"
        };
      } else {
        return {
          TAG: "Ok",
          _0: makeParsers(packetName, PacketV1449_ClientSyncedInventory$TerrariaPacket.parse, a => ({
            TAG: "ClientSyncedInventory",
            _0: a
          }), a => ({
            TAG: "ClientSyncedInventory",
            _0: a
          }))
        };
      }
    case "CountsAsHostForGameplaySet" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_CountsAsHostForGameplaySet$TerrariaPacket.parse, a => ({
          TAG: "CountsAsHostForGameplaySet",
          _0: a
        }), a => ({
          TAG: "CountsAsHostForGameplaySet",
          _0: a
        }))
      };
    case "CreditsOrSlimeTransform" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_CreditsOrSlimeTransform$TerrariaPacket.parse, a => ({
          TAG: "CreditsOrSlimeTransform",
          _0: a
        }), a => ({
          TAG: "CreditsOrSlimeTransform",
          _0: a
        }))
      };
    case "LucyAxeMessage" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_LucyAxeMessage$TerrariaPacket.parse, a => ({
          TAG: "LucyAxeMessage",
          _0: a
        }), a => ({
          TAG: "LucyAxeMessage",
          _0: a
        }))
      };
    case "PiggyBankVoidLensUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_PiggyBankVoidLensUpdate$TerrariaPacket.parse, a => ({
          TAG: "PiggyBankVoidLensUpdate",
          _0: a
        }), a => ({
          TAG: "PiggyBankVoidLensUpdate",
          _0: a
        }))
      };
    case "DungeonDefendersEventAttemptSkipWait" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_DungeonDefendersEventAttemptSkipWait$TerrariaPacket.parse, a => ({
          TAG: "DungeonDefendersEventAttemptSkipWait",
          _0: a
        }), a => ({
          TAG: "DungeonDefendersEventAttemptSkipWait",
          _0: a
        }))
      };
    case "HaveDryadDoStardewAnimation" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_HaveDryadDoStardewAnimation$TerrariaPacket.parse, a => ({
          TAG: "HaveDryadDoStardewAnimation",
          _0: a
        }), a => ({
          TAG: "HaveDryadDoStardewAnimation",
          _0: a
        }))
      };
    case "ItemDropShimmeredUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ItemDropShimmeredUpdate$TerrariaPacket.parse, a => ({
          TAG: "ItemDropShimmeredUpdate",
          _0: a
        }), a => ({
          TAG: "ItemDropShimmeredUpdate",
          _0: a
        }))
      };
    case "ShimmerEffectOrCoinLuck" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ShimmerEffectOrCoinLuck$TerrariaPacket.parse, a => ({
          TAG: "ShimmerEffectOrCoinLuck",
          _0: a
        }), a => ({
          TAG: "ShimmerEffectOrCoinLuck",
          _0: a
        }))
      };
    case "LoadoutSwitch" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_LoadoutSwitch$TerrariaPacket.parse, a => ({
          TAG: "LoadoutSwitch",
          _0: a
        }), a => ({
          TAG: "LoadoutSwitch",
          _0: a
        }))
      };
    case "ItemDropProtectedUpdate" :
      return {
        TAG: "Ok",
        _0: makeParsers(packetName, PacketV1449_ItemDropProtectedUpdate$TerrariaPacket.parse, a => ({
          TAG: "ItemDropProtectedUpdate",
          _0: a
        }), a => ({
          TAG: "ItemDropProtectedUpdate",
          _0: a
        }))
      };
    default:
      return {
        TAG: "Error",
        _0: {
          TAG: "InvalidPacketType",
          _0: PacketType$TerrariaPacket.toInt(packetType)
        }
      };
  }
}

function parse(buffer, fromServer, ignoreOpt) {
  let ignore = ignoreOpt !== undefined ? ignoreOpt : [];
  let match = buffer.length;
  if (!(match > 2 || match < 0)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidPacketLength",
        _0: buffer.length
      }
    };
  }
  let packetType = PacketType$TerrariaPacket.fromInt(buffer[2]);
  if (packetType === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidPacketType",
        _0: buffer[2]
      }
    };
  }
  if (ignore.includes(packetType)) {
    return {
      TAG: "Error",
      _0: "IgnoredPacket"
    };
  }
  try {
    let parsers = getParsers(packetType, fromServer);
    if (parsers.TAG === "Ok") {
      return parsers._0.parse(buffer, fromServer);
    } else {
      return {
        TAG: "Error",
        _0: parsers._0
      };
    }
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "ReaderError",
          _0: {
            context: "Parser.parse",
            error: obj._1
          }
        }
      };
    }
    throw obj;
  }
}

function parseLazy(buffer, fromServer) {
  let match = buffer.length;
  if (!(match > 2 || match < 0)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidPacketLength",
        _0: buffer.length
      }
    };
  }
  let packetType = PacketType$TerrariaPacket.fromInt(buffer[2]);
  if (packetType === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidPacketType",
        _0: buffer[2]
      }
    };
  }
  try {
    let parsers = getParsers(packetType, fromServer);
    if (parsers.TAG === "Ok") {
      return parsers._0.parseLazy(buffer, fromServer);
    } else {
      return {
        TAG: "Error",
        _0: parsers._0
      };
    }
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "ReaderError",
          _0: {
            context: "Parser.parseLazy",
            error: obj._1
          }
        }
      };
    }
    throw obj;
  }
}

export {
  parse,
  parseLazy,
}
/* PacketV1449_Emoji-TerrariaPacket Not a pure module */
