// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";
import * as Parser$TerrariaPacket from "./Parser.js";
import * as PacketType$TerrariaPacket from "./PacketType.js";
import * as Parserv1449$TerrariaPacket from "./Parserv1449.js";

function worldEventInfoFromV1449(eventInfo) {
  return {
    shadowOrbSmashed: eventInfo.shadowOrbSmashed,
    killedBoss1: eventInfo.killedBoss1,
    killedBoss2: eventInfo.killedBoss2,
    killedBoss3: eventInfo.killedBoss3,
    hardMode: eventInfo.hardMode,
    killedClown: eventInfo.killedClown,
    serverSidedCharacters: eventInfo.serverSidedCharacters,
    killedPlantBoss: eventInfo.killedPlantBoss,
    killedMechBoss: eventInfo.killedMechBoss,
    killedMechBoss2: eventInfo.killedMechBoss2,
    killedMechBoss3: eventInfo.killedMechBoss3,
    killedAnyMechBoss: eventInfo.killedAnyMechBoss,
    cloudBg: eventInfo.cloudBg,
    crimson: eventInfo.crimson,
    pumpkinMoon: eventInfo.pumpkinMoon,
    snowMoon: eventInfo.snowMoon,
    expertMode: eventInfo.expertMode,
    fastForwardTime: eventInfo.fastForwardTime,
    slimeRain: eventInfo.slimeRain,
    killedKingSlime: eventInfo.killedKingSlime,
    killedQueenBee: eventInfo.killedQueenBee,
    killedFishron: eventInfo.killedFishron,
    killedMartians: eventInfo.killedMartians,
    killedAncientCultist: eventInfo.killedAncientCultist,
    killedMoonLord: eventInfo.killedMoonLord,
    killedPumpking: eventInfo.killedPumpking,
    killedMourningWood: eventInfo.killedMourningWood,
    killedIceQueen: eventInfo.killedIceQueen,
    killedSantank: eventInfo.killedSantank,
    killedEverscream: eventInfo.killedEverscream,
    killedGolem: eventInfo.killedGolem,
    birthdayParty: eventInfo.birthdayParty,
    killedPirates: eventInfo.killedPirates,
    killedFrostLegion: eventInfo.killedFrostLegion,
    killedGoblins: eventInfo.killedGoblins,
    sandstorm: eventInfo.sandstorm,
    dungeonDefendersEvent: eventInfo.dungeonDefendersEvent,
    killedDungeonDefendersTier1: eventInfo.killedDungeonDefendersTier1,
    killedDungeonDefendersTier2: eventInfo.killedDungeonDefendersTier2,
    killedDungeonDefendersTier3: eventInfo.killedDungeonDefendersTier3,
    combatBookUsed: eventInfo.combatBookUsed,
    manualLanterns: eventInfo.manualLanterns,
    killedSolarTower: eventInfo.killedSolarTower,
    killedVortexTower: eventInfo.killedVortexTower,
    killedNebulaTower: eventInfo.killedNebulaTower,
    killedStardustTower: eventInfo.killedStardustTower,
    forceHalloween: eventInfo.forceHalloween,
    forceChristmas: eventInfo.forceChristmas,
    boughtCat: eventInfo.boughtCat,
    boughtDog: eventInfo.boughtDog,
    boughtBunny: eventInfo.boughtBunny,
    freeCake: eventInfo.freeCake,
    drunkWorld: eventInfo.drunkWorld,
    killedEmpressOfLight: eventInfo.killedEmpressOfLight,
    killedQueenSlime: eventInfo.killedQueenSlime,
    getGoodWorld: eventInfo.getGoodWorld,
    tenthAnniversaryWorld: eventInfo.tenthAnniversaryWorld,
    dontStarveWorld: eventInfo.dontStarveWorld,
    downedDeerClops: eventInfo.downedDeerClops,
    notTheBeesWorld: eventInfo.notTheBeesWorld,
    remixWorld: eventInfo.remixWorld,
    unlockedSlimeBlueSpawn: eventInfo.unlockedSlimeBlueSpawn,
    combatBookVolumeTwoWasUsed: eventInfo.combatBookVolumeTwoWasUsed,
    peddlersSatchelWasUsed: eventInfo.peddlersSatchelWasUsed,
    unlockedSlimeGreenSpawn: eventInfo.unlockedSlimeGreenSpawn,
    unlockedSlimeOldSpawn: eventInfo.unlockedSlimeOldSpawn,
    unlockedSlimePurpleSpawn: eventInfo.unlockedSlimePurpleSpawn,
    unlockedSlimeRainbowSpawn: eventInfo.unlockedSlimeRainbowSpawn,
    unlockedSlimeRedSpawn: eventInfo.unlockedSlimeRedSpawn,
    unlockedSlimeYellowSpawn: eventInfo.unlockedSlimeYellowSpawn,
    unlockedSlimeCopperSpawn: eventInfo.unlockedSlimeCopperSpawn,
    fastForwardTimeToDusk: eventInfo.fastForwardTimeToDusk,
    noTrapsWorld: eventInfo.noTrapsWorld,
    zenithWorld: eventInfo.zenithWorld,
    unlockedTruffleSpawn: eventInfo.unlockedTruffleSpawn,
    vampireSeed: false,
    infectedSeed: false,
    teamBasedSpawnsSeed: false,
    skyblockWorld: false,
    dualDungeonsSeed: false
  };
}

function worldEventInfoToV1449(eventInfo) {
  return {
    shadowOrbSmashed: eventInfo.shadowOrbSmashed,
    killedBoss1: eventInfo.killedBoss1,
    killedBoss2: eventInfo.killedBoss2,
    killedBoss3: eventInfo.killedBoss3,
    hardMode: eventInfo.hardMode,
    killedClown: eventInfo.killedClown,
    serverSidedCharacters: eventInfo.serverSidedCharacters,
    killedPlantBoss: eventInfo.killedPlantBoss,
    killedMechBoss: eventInfo.killedMechBoss,
    killedMechBoss2: eventInfo.killedMechBoss2,
    killedMechBoss3: eventInfo.killedMechBoss3,
    killedAnyMechBoss: eventInfo.killedAnyMechBoss,
    cloudBg: eventInfo.cloudBg,
    crimson: eventInfo.crimson,
    pumpkinMoon: eventInfo.pumpkinMoon,
    snowMoon: eventInfo.snowMoon,
    expertMode: eventInfo.expertMode,
    fastForwardTime: eventInfo.fastForwardTime,
    slimeRain: eventInfo.slimeRain,
    killedKingSlime: eventInfo.killedKingSlime,
    killedQueenBee: eventInfo.killedQueenBee,
    killedFishron: eventInfo.killedFishron,
    killedMartians: eventInfo.killedMartians,
    killedAncientCultist: eventInfo.killedAncientCultist,
    killedMoonLord: eventInfo.killedMoonLord,
    killedPumpking: eventInfo.killedPumpking,
    killedMourningWood: eventInfo.killedMourningWood,
    killedIceQueen: eventInfo.killedIceQueen,
    killedSantank: eventInfo.killedSantank,
    killedEverscream: eventInfo.killedEverscream,
    killedGolem: eventInfo.killedGolem,
    birthdayParty: eventInfo.birthdayParty,
    killedPirates: eventInfo.killedPirates,
    killedFrostLegion: eventInfo.killedFrostLegion,
    killedGoblins: eventInfo.killedGoblins,
    sandstorm: eventInfo.sandstorm,
    dungeonDefendersEvent: eventInfo.dungeonDefendersEvent,
    killedDungeonDefendersTier1: eventInfo.killedDungeonDefendersTier1,
    killedDungeonDefendersTier2: eventInfo.killedDungeonDefendersTier2,
    killedDungeonDefendersTier3: eventInfo.killedDungeonDefendersTier3,
    combatBookUsed: eventInfo.combatBookUsed,
    manualLanterns: eventInfo.manualLanterns,
    killedSolarTower: eventInfo.killedSolarTower,
    killedVortexTower: eventInfo.killedVortexTower,
    killedNebulaTower: eventInfo.killedNebulaTower,
    killedStardustTower: eventInfo.killedStardustTower,
    forceHalloween: eventInfo.forceHalloween,
    forceChristmas: eventInfo.forceChristmas,
    boughtCat: eventInfo.boughtCat,
    boughtDog: eventInfo.boughtDog,
    boughtBunny: eventInfo.boughtBunny,
    freeCake: eventInfo.freeCake,
    drunkWorld: eventInfo.drunkWorld,
    killedEmpressOfLight: eventInfo.killedEmpressOfLight,
    killedQueenSlime: eventInfo.killedQueenSlime,
    getGoodWorld: eventInfo.getGoodWorld,
    tenthAnniversaryWorld: eventInfo.tenthAnniversaryWorld,
    dontStarveWorld: eventInfo.dontStarveWorld,
    downedDeerClops: eventInfo.downedDeerClops,
    notTheBeesWorld: eventInfo.notTheBeesWorld,
    remixWorld: eventInfo.remixWorld,
    unlockedSlimeBlueSpawn: eventInfo.unlockedSlimeBlueSpawn,
    combatBookVolumeTwoWasUsed: eventInfo.combatBookVolumeTwoWasUsed,
    peddlersSatchelWasUsed: eventInfo.peddlersSatchelWasUsed,
    unlockedSlimeGreenSpawn: eventInfo.unlockedSlimeGreenSpawn,
    unlockedSlimeOldSpawn: eventInfo.unlockedSlimeOldSpawn,
    unlockedSlimePurpleSpawn: eventInfo.unlockedSlimePurpleSpawn,
    unlockedSlimeRainbowSpawn: eventInfo.unlockedSlimeRainbowSpawn,
    unlockedSlimeRedSpawn: eventInfo.unlockedSlimeRedSpawn,
    unlockedSlimeYellowSpawn: eventInfo.unlockedSlimeYellowSpawn,
    unlockedSlimeCopperSpawn: eventInfo.unlockedSlimeCopperSpawn,
    fastForwardTimeToDusk: eventInfo.fastForwardTimeToDusk,
    noTrapsWorld: eventInfo.noTrapsWorld,
    zenithWorld: eventInfo.zenithWorld,
    unlockedTruffleSpawn: eventInfo.unlockedTruffleSpawn
  };
}

function worldInfoFromV1449(worldInfo) {
  return {
    time: worldInfo.time,
    dayAndMoonInfo: worldInfo.dayAndMoonInfo,
    moonPhase: worldInfo.moonPhase,
    maxTilesX: worldInfo.maxTilesX,
    maxTilesY: worldInfo.maxTilesY,
    spawnX: worldInfo.spawnX,
    spawnY: worldInfo.spawnY,
    worldSurface: worldInfo.worldSurface,
    rockLayer: worldInfo.rockLayer,
    worldId: worldInfo.worldId,
    worldName: worldInfo.worldName,
    gameMode: worldInfo.gameMode,
    worldUniqueId: worldInfo.worldUniqueId,
    worldGeneratorVersion: worldInfo.worldGeneratorVersion,
    moonType: worldInfo.moonType,
    treeBackground: worldInfo.treeBackground,
    treeBackground2: worldInfo.treeBackground2,
    treeBackground3: worldInfo.treeBackground3,
    treeBackground4: worldInfo.treeBackground4,
    corruptionBackground: worldInfo.corruptionBackground,
    jungleBackground: worldInfo.jungleBackground,
    snowBackground: worldInfo.snowBackground,
    hallowBackground: worldInfo.hallowBackground,
    crimsonBackground: worldInfo.crimsonBackground,
    desertBackground: worldInfo.desertBackground,
    oceanBackground: worldInfo.oceanBackground,
    mushroomBackground: worldInfo.mushroomBackground,
    underworldBackground: worldInfo.underworldBackground,
    iceBackStyle: worldInfo.iceBackStyle,
    jungleBackStyle: worldInfo.jungleBackStyle,
    hellBackStyle: worldInfo.hellBackStyle,
    windSpeedSet: worldInfo.windSpeedSet,
    cloudNumber: worldInfo.cloudNumber,
    tree1: worldInfo.tree1,
    tree2: worldInfo.tree2,
    tree3: worldInfo.tree3,
    treeStyle1: worldInfo.treeStyle1,
    treeStyle2: worldInfo.treeStyle2,
    treeStyle3: worldInfo.treeStyle3,
    treeStyle4: worldInfo.treeStyle4,
    caveBack1: worldInfo.caveBack1,
    caveBack2: worldInfo.caveBack2,
    caveBack3: worldInfo.caveBack3,
    caveBackStyle1: worldInfo.caveBackStyle1,
    caveBackStyle2: worldInfo.caveBackStyle2,
    caveBackStyle3: worldInfo.caveBackStyle3,
    caveBackStyle4: worldInfo.caveBackStyle4,
    forest1TreeTopStyle: worldInfo.forest1TreeTopStyle,
    forest2TreeTopStyle: worldInfo.forest2TreeTopStyle,
    forest3TreeTopStyle: worldInfo.forest3TreeTopStyle,
    forest4TreeTopStyle: worldInfo.forest4TreeTopStyle,
    corruptionTreeTopStyle: worldInfo.corruptionTreeTopStyle,
    jungleTreeTopStyle: worldInfo.jungleTreeTopStyle,
    snowTreeTopStyle: worldInfo.snowTreeTopStyle,
    hallowTreeTopStyle: worldInfo.hallowTreeTopStyle,
    crimsonTreeTopStyle: worldInfo.crimsonTreeTopStyle,
    desertTreeTopStyle: worldInfo.desertTreeTopStyle,
    oceanTreeTopStyle: worldInfo.oceanTreeTopStyle,
    glowingMushroomTreeTopStyle: worldInfo.glowingMushroomTreeTopStyle,
    underworldTreeTopStyle: worldInfo.underworldTreeTopStyle,
    rain: worldInfo.rain,
    eventInfo: worldEventInfoFromV1449(worldInfo.eventInfo),
    lowTiles: false,
    forceHalloweenForever: false,
    forceChristmasForever: false,
    moreLightningSeed: false,
    noLightningSeed: false,
    sundialCooldown: worldInfo.sundialCooldown,
    moondialCooldown: worldInfo.moondialCooldown,
    copperOreTier: worldInfo.copperOreTier,
    ironOreTier: worldInfo.ironOreTier,
    silverOreTier: worldInfo.silverOreTier,
    goldOreTier: worldInfo.goldOreTier,
    cobaltOreTier: worldInfo.cobaltOreTier,
    mythrilOreTier: worldInfo.mythrilOreTier,
    adamantiteOreTier: worldInfo.adamantiteOreTier,
    invasionType: worldInfo.invasionType,
    lobbyId: worldInfo.lobbyId,
    sandstormSeverity: worldInfo.sandstormSeverity,
    extraSpawnPoints: [],
    dungeonX: 0,
    dungeonY: 0
  };
}

function worldInfoToV1449(worldInfo) {
  return {
    time: worldInfo.time,
    dayAndMoonInfo: worldInfo.dayAndMoonInfo,
    moonPhase: worldInfo.moonPhase,
    maxTilesX: worldInfo.maxTilesX,
    maxTilesY: worldInfo.maxTilesY,
    spawnX: worldInfo.spawnX,
    spawnY: worldInfo.spawnY,
    worldSurface: worldInfo.worldSurface,
    rockLayer: worldInfo.rockLayer,
    worldId: worldInfo.worldId,
    worldName: worldInfo.worldName,
    gameMode: worldInfo.gameMode,
    worldUniqueId: worldInfo.worldUniqueId,
    worldGeneratorVersion: worldInfo.worldGeneratorVersion,
    moonType: worldInfo.moonType,
    treeBackground: worldInfo.treeBackground,
    treeBackground2: worldInfo.treeBackground2,
    treeBackground3: worldInfo.treeBackground3,
    treeBackground4: worldInfo.treeBackground4,
    corruptionBackground: worldInfo.corruptionBackground,
    jungleBackground: worldInfo.jungleBackground,
    snowBackground: worldInfo.snowBackground,
    hallowBackground: worldInfo.hallowBackground,
    crimsonBackground: worldInfo.crimsonBackground,
    desertBackground: worldInfo.desertBackground,
    oceanBackground: worldInfo.oceanBackground,
    mushroomBackground: worldInfo.mushroomBackground,
    underworldBackground: worldInfo.underworldBackground,
    iceBackStyle: worldInfo.iceBackStyle,
    jungleBackStyle: worldInfo.jungleBackStyle,
    hellBackStyle: worldInfo.hellBackStyle,
    windSpeedSet: worldInfo.windSpeedSet,
    cloudNumber: worldInfo.cloudNumber,
    tree1: worldInfo.tree1,
    tree2: worldInfo.tree2,
    tree3: worldInfo.tree3,
    treeStyle1: worldInfo.treeStyle1,
    treeStyle2: worldInfo.treeStyle2,
    treeStyle3: worldInfo.treeStyle3,
    treeStyle4: worldInfo.treeStyle4,
    caveBack1: worldInfo.caveBack1,
    caveBack2: worldInfo.caveBack2,
    caveBack3: worldInfo.caveBack3,
    caveBackStyle1: worldInfo.caveBackStyle1,
    caveBackStyle2: worldInfo.caveBackStyle2,
    caveBackStyle3: worldInfo.caveBackStyle3,
    caveBackStyle4: worldInfo.caveBackStyle4,
    forest1TreeTopStyle: worldInfo.forest1TreeTopStyle,
    forest2TreeTopStyle: worldInfo.forest2TreeTopStyle,
    forest3TreeTopStyle: worldInfo.forest3TreeTopStyle,
    forest4TreeTopStyle: worldInfo.forest4TreeTopStyle,
    corruptionTreeTopStyle: worldInfo.corruptionTreeTopStyle,
    jungleTreeTopStyle: worldInfo.jungleTreeTopStyle,
    snowTreeTopStyle: worldInfo.snowTreeTopStyle,
    hallowTreeTopStyle: worldInfo.hallowTreeTopStyle,
    crimsonTreeTopStyle: worldInfo.crimsonTreeTopStyle,
    desertTreeTopStyle: worldInfo.desertTreeTopStyle,
    oceanTreeTopStyle: worldInfo.oceanTreeTopStyle,
    glowingMushroomTreeTopStyle: worldInfo.glowingMushroomTreeTopStyle,
    underworldTreeTopStyle: worldInfo.underworldTreeTopStyle,
    rain: worldInfo.rain,
    eventInfo: worldEventInfoToV1449(worldInfo.eventInfo),
    sundialCooldown: worldInfo.sundialCooldown,
    moondialCooldown: worldInfo.moondialCooldown,
    copperOreTier: worldInfo.copperOreTier,
    ironOreTier: worldInfo.ironOreTier,
    silverOreTier: worldInfo.silverOreTier,
    goldOreTier: worldInfo.goldOreTier,
    cobaltOreTier: worldInfo.cobaltOreTier,
    mythrilOreTier: worldInfo.mythrilOreTier,
    adamantiteOreTier: worldInfo.adamantiteOreTier,
    invasionType: worldInfo.invasionType,
    lobbyId: worldInfo.lobbyId,
    sandstormSeverity: worldInfo.sandstormSeverity
  };
}

function playerSpawnContextFromV1449(context) {
  switch (context) {
    case "ReviveFromDeath" :
      return "ReviveFromDeath";
    case "SpawningIntoWorld" :
      return "SpawningIntoWorld";
    case "RecallFromItem" :
      return "RecallFromItem";
  }
}

function playerSpawnContextToV1449(context) {
  if (typeof context === "object") {
    return "SpawningIntoWorld";
  }
  switch (context) {
    case "ReviveFromDeath" :
      return "ReviveFromDeath";
    case "RecallFromItem" :
      return "RecallFromItem";
    default:
      return "SpawningIntoWorld";
  }
}

function playerUpdateControlFromV1449(control) {
  return {
    isHoldingUp: control.isHoldingUp,
    isHoldingDown: control.isHoldingDown,
    isHoldingLeft: control.isHoldingLeft,
    isHoldingRight: control.isHoldingRight,
    isHoldingJump: control.isHoldingJump,
    isHoldingItemUse: control.isHoldingItemUse,
    isHoldingDash: false
  };
}

function playerUpdateControlToV1449(control) {
  return {
    isHoldingUp: control.isHoldingUp,
    isHoldingDown: control.isHoldingDown,
    isHoldingLeft: control.isHoldingLeft,
    isHoldingRight: control.isHoldingRight,
    isHoldingJump: control.isHoldingJump,
    isHoldingItemUse: control.isHoldingItemUse
  };
}

function playerUpdateDirectionFromV1449(direction) {
  if (direction === "Left") {
    return "Left";
  } else {
    return "Right";
  }
}

function playerUpdateDirectionToV1449(direction) {
  if (direction === "Left") {
    return "Left";
  } else {
    return "Right";
  }
}

function playerUpdatePulleyDirectionFromV1449(pulleyDirection) {
  if (pulleyDirection !== undefined) {
    if (pulleyDirection === "One") {
      return "One";
    } else {
      return "Two";
    }
  }
}

function playerUpdatePulleyDirectionToV1449(pulleyDirection) {
  if (pulleyDirection !== undefined) {
    if (pulleyDirection === "One") {
      return "One";
    } else {
      return "Two";
    }
  }
}

function playerUpdateGravityDirectionFromV1449(gravityDirection) {
  if (gravityDirection === "Normal") {
    return "Normal";
  } else {
    return "Inverted";
  }
}

function playerUpdateGravityDirectionToV1449(gravityDirection) {
  if (gravityDirection === "Normal") {
    return "Normal";
  } else {
    return "Inverted";
  }
}

function playerUpdatePotionOfReturnFromV1449(potionOfReturn) {
  if (potionOfReturn !== undefined) {
    return {
      originalUsePosition: potionOfReturn.originalUsePosition,
      homePosition: potionOfReturn.homePosition
    };
  }
}

function playerUpdatePotionOfReturnToV1449(potionOfReturn) {
  if (potionOfReturn !== undefined) {
    return {
      originalUsePosition: potionOfReturn.originalUsePosition,
      homePosition: potionOfReturn.homePosition
    };
  }
}

function npcUpdateLifeFromV1449(life) {
  if (typeof life !== "object") {
    return "Max";
  }
  switch (life.TAG) {
    case "Byte" :
      return {
        TAG: "Byte",
        _0: life._0
      };
    case "Int16" :
      return {
        TAG: "Int16",
        _0: life._0
      };
    case "Int32" :
      return {
        TAG: "Int32",
        _0: life._0
      };
  }
}

function npcUpdateLifeToV1449(life) {
  if (typeof life !== "object") {
    return "Max";
  }
  switch (life.TAG) {
    case "Byte" :
      return {
        TAG: "Byte",
        _0: life._0
      };
    case "Int16" :
      return {
        TAG: "Int16",
        _0: life._0
      };
    case "Int32" :
      return {
        TAG: "Int32",
        _0: life._0
      };
  }
}

function shimmerCoinLuckFromV1449(coinLuck) {
  return {
    position: coinLuck.position,
    amount: coinLuck.amount
  };
}

function shimmerCoinLuckToV1449(coinLuck) {
  return {
    position: coinLuck.position,
    amount: coinLuck.amount
  };
}

function netModuleLoadLiquidChangeFromV1449(change) {
  return {
    x: change.x,
    y: change.y,
    amount: change.amount,
    liquidType: change.liquidType
  };
}

function netModuleLoadLiquidFromV1449(liquid) {
  return {
    changes: liquid.changes.map(netModuleLoadLiquidChangeFromV1449)
  };
}

function netModuleLoadPositionFromV1449(position) {
  return {
    x: position.x,
    y: position.y
  };
}

function netModuleLoadAmbienceFromV1449(ambience) {
  return {
    playerId: ambience.playerId,
    seed: ambience.seed,
    skyEntityType: ambience.skyEntityType
  };
}

function netModuleLoadBestiaryUnlockTypeFromV1449(unlockType) {
  if (typeof unlockType !== "object") {
    if (unlockType === "Sight") {
      return "Sight";
    } else {
      return "Chat";
    }
  } else {
    return {
      TAG: "Kill",
      _0: unlockType._0
    };
  }
}

function netModuleLoadBestiaryFromV1449(bestiary) {
  return {
    unlockType: netModuleLoadBestiaryUnlockTypeFromV1449(bestiary.unlockType),
    npcId: bestiary.npcId
  };
}

function netModuleLoadPylonActionFromV1449(action) {
  switch (action) {
    case "Added" :
      return "Added";
    case "Removed" :
      return "Removed";
    case "RequestTeleport" :
      return "RequestTeleport";
  }
}

function netModuleLoadTeleportPylonFromV1449(teleportPylon) {
  return {
    pylonAction: netModuleLoadPylonActionFromV1449(teleportPylon.pylonAction),
    x: teleportPylon.x,
    y: teleportPylon.y,
    pylonType: teleportPylon.pylonType
  };
}

function netModuleLoadParticleFromV1449(particle) {
  return {
    particleType: particle.particleType,
    x: particle.x,
    y: particle.y,
    vx: particle.vx,
    vy: particle.vy,
    shaderIndex: particle.shaderIndex,
    invokedByPlayer: particle.invokedByPlayer
  };
}

function netModuleLoadPowerLevelFromV1449(powerLevel) {
  switch (powerLevel) {
    case "LockedForEveryone" :
      return "LockedForEveryone";
    case "CanBeChangedByHostAlone" :
      return "CanBeChangedByHostAlone";
    case "CanBeChangedByEveryone" :
      return "CanBeChangedByEveryone";
  }
}

function netModuleLoadCreativePowerPermissionFromV1449(permission) {
  return {
    powerType: permission.powerType,
    powerLevel: netModuleLoadPowerLevelFromV1449(permission.powerLevel)
  };
}

function netModuleLoadLiquidChangeToV1449(change) {
  return {
    x: change.x,
    y: change.y,
    amount: change.amount,
    liquidType: change.liquidType
  };
}

function netModuleLoadLiquidToV1449(liquid) {
  return {
    changes: liquid.changes.map(netModuleLoadLiquidChangeToV1449)
  };
}

function netModuleLoadPositionToV1449(position) {
  return {
    x: position.x,
    y: position.y
  };
}

function netModuleLoadAmbienceToV1449(ambience) {
  return {
    playerId: ambience.playerId,
    seed: ambience.seed,
    skyEntityType: ambience.skyEntityType
  };
}

function netModuleLoadBestiaryUnlockTypeToV1449(unlockType) {
  if (typeof unlockType !== "object") {
    if (unlockType === "Sight") {
      return "Sight";
    } else {
      return "Chat";
    }
  } else {
    return {
      TAG: "Kill",
      _0: unlockType._0
    };
  }
}

function netModuleLoadBestiaryToV1449(bestiary) {
  return {
    unlockType: netModuleLoadBestiaryUnlockTypeToV1449(bestiary.unlockType),
    npcId: bestiary.npcId
  };
}

function netModuleLoadPylonActionToV1449(action) {
  switch (action) {
    case "Added" :
      return "Added";
    case "Removed" :
      return "Removed";
    case "RequestTeleport" :
      return "RequestTeleport";
  }
}

function netModuleLoadTeleportPylonToV1449(teleportPylon) {
  return {
    pylonAction: netModuleLoadPylonActionToV1449(teleportPylon.pylonAction),
    x: teleportPylon.x,
    y: teleportPylon.y,
    pylonType: teleportPylon.pylonType
  };
}

function netModuleLoadParticleToV1449(particle) {
  return {
    particleType: particle.particleType,
    x: particle.x,
    y: particle.y,
    vx: particle.vx,
    vy: particle.vy,
    shaderIndex: particle.shaderIndex,
    invokedByPlayer: particle.invokedByPlayer
  };
}

function netModuleLoadPowerLevelToV1449(powerLevel) {
  switch (powerLevel) {
    case "LockedForEveryone" :
      return "LockedForEveryone";
    case "CanBeChangedByHostAlone" :
      return "CanBeChangedByHostAlone";
    case "CanBeChangedByEveryone" :
      return "CanBeChangedByEveryone";
  }
}

function netModuleLoadCreativePowerPermissionToV1449(permission) {
  return {
    powerType: permission.powerType,
    powerLevel: netModuleLoadPowerLevelToV1449(permission.powerLevel)
  };
}

function netModuleLoadFromV1449(netModuleLoad) {
  switch (netModuleLoad.TAG) {
    case "Liquid" :
      return {
        TAG: "Liquid",
        _0: netModuleLoadLiquidFromV1449(netModuleLoad._0)
      };
    case "ClientText" :
      return {
        TAG: "ClientText",
        _0: netModuleLoad._0,
        _1: netModuleLoad._1
      };
    case "ServerText" :
      return {
        TAG: "ServerText",
        _0: netModuleLoad._0,
        _1: netModuleLoad._1,
        _2: netModuleLoad._2
      };
    case "Ping" :
      return {
        TAG: "Ping",
        _0: netModuleLoadPositionFromV1449(netModuleLoad._0)
      };
    case "Ambience" :
      return {
        TAG: "Ambience",
        _0: netModuleLoadAmbienceFromV1449(netModuleLoad._0)
      };
    case "Bestiary" :
      return {
        TAG: "Bestiary",
        _0: netModuleLoadBestiaryFromV1449(netModuleLoad._0)
      };
    case "CreativeUnlocks" :
      let creativeUnlock = netModuleLoad._0;
      return {
        TAG: "CreativeUnlocks",
        _0: {
          itemId: creativeUnlock.itemId,
          sacrificeCount: creativeUnlock.researchedCount
        }
      };
    case "CreativePower" :
      return {
        TAG: "CreativePower",
        _0: netModuleLoad._0
      };
    case "CreativeUnlocksPlayerReport" :
      let unlockReport = netModuleLoad._0;
      return {
        TAG: "CreativeUnlocksPlayerReport",
        _0: {
          userId: 0,
          itemId: unlockReport.itemId,
          researchedCount: unlockReport.researchedCount
        }
      };
    case "TeleportPylon" :
      return {
        TAG: "TeleportPylon",
        _0: netModuleLoadTeleportPylonFromV1449(netModuleLoad._0)
      };
    case "Particles" :
      return {
        TAG: "Particles",
        _0: netModuleLoadParticleFromV1449(netModuleLoad._0)
      };
    case "CreativePowerPermissions" :
      return {
        TAG: "CreativePowerPermissions",
        _0: netModuleLoadCreativePowerPermissionFromV1449(netModuleLoad._0)
      };
  }
}

function netModuleLoadToV1449(netModuleLoad) {
  switch (netModuleLoad.TAG) {
    case "Liquid" :
      return {
        TAG: "Liquid",
        _0: netModuleLoadLiquidToV1449(netModuleLoad._0)
      };
    case "ClientText" :
      return {
        TAG: "ClientText",
        _0: netModuleLoad._0,
        _1: netModuleLoad._1
      };
    case "ServerText" :
      return {
        TAG: "ServerText",
        _0: netModuleLoad._0,
        _1: netModuleLoad._1,
        _2: netModuleLoad._2
      };
    case "Ping" :
      return {
        TAG: "Ping",
        _0: netModuleLoadPositionToV1449(netModuleLoad._0)
      };
    case "Ambience" :
      return {
        TAG: "Ambience",
        _0: netModuleLoadAmbienceToV1449(netModuleLoad._0)
      };
    case "Bestiary" :
      return {
        TAG: "Bestiary",
        _0: netModuleLoadBestiaryToV1449(netModuleLoad._0)
      };
    case "CreativeUnlocks" :
      let creativeUnlock = netModuleLoad._0;
      return {
        TAG: "CreativeUnlocks",
        _0: {
          itemId: creativeUnlock.itemId,
          researchedCount: creativeUnlock.sacrificeCount
        }
      };
    case "CreativePower" :
      return {
        TAG: "CreativePower",
        _0: netModuleLoad._0
      };
    case "CreativeUnlocksPlayerReport" :
      let unlockReport = netModuleLoad._0;
      return {
        TAG: "CreativeUnlocksPlayerReport",
        _0: {
          itemId: unlockReport.itemId,
          researchedCount: unlockReport.researchedCount
        }
      };
    case "TeleportPylon" :
      return {
        TAG: "TeleportPylon",
        _0: netModuleLoadTeleportPylonToV1449(netModuleLoad._0)
      };
    case "Particles" :
      return {
        TAG: "Particles",
        _0: netModuleLoadParticleToV1449(netModuleLoad._0)
      };
    case "CreativePowerPermissions" :
      return {
        TAG: "CreativePowerPermissions",
        _0: netModuleLoadCreativePowerPermissionToV1449(netModuleLoad._0)
      };
    default:
      return;
  }
}

function playerInventorySlotIdFromV1449(slot) {
  if (slot <= 98 || slot <= 138) {
    return slot;
  } else if (slot <= 178) {
    return slot + 160 | 0;
  } else if (slot === 179 || slot <= 219) {
    return slot + 320 | 0;
  } else if (slot <= 259) {
    return slot + 480 | 0;
  } else if (slot <= 349) {
    return slot + 640 | 0;
  } else {
    return slot;
  }
}

function playerInventorySlotIdToV1449(slot) {
  if (slot <= 98) {
    return slot;
  }
  if (slot <= 298) {
    let index = slot - 99 | 0;
    if (index < 40) {
      return slot;
    } else {
      return;
    }
  }
  if (slot <= 498) {
    let index$1 = slot - 299 | 0;
    if (index$1 < 40) {
      return 139 + index$1 | 0;
    } else {
      return;
    }
  }
  if (slot === 499) {
    return 179;
  }
  if (slot <= 699) {
    let index$2 = slot - 500 | 0;
    if (index$2 < 40) {
      return 180 + index$2 | 0;
    } else {
      return;
    }
  }
  if (slot > 899) {
    if (slot <= 989) {
      return slot - 640 | 0;
    } else {
      return;
    }
  }
  let index$3 = slot - 700 | 0;
  if (index$3 < 40) {
    return 220 + index$3 | 0;
  }
}

function displayItemFromV1449(item) {
  return {
    netId: item.netId,
    prefix: item.prefix,
    stack: item.stack
  };
}

function displayItemOptionFromV1449(item) {
  return Stdlib_Option.map(item, displayItemFromV1449);
}

function displayDollFromV1449(displayDoll) {
  return {
    items: displayDoll.items.map(displayItemOptionFromV1449).concat([undefined]),
    dyes: displayDoll.dyes.map(displayItemOptionFromV1449).concat([undefined]),
    misc: [undefined],
    pose: 0
  };
}

function hatRackFromV1449(hatRack) {
  return {
    items: hatRack.items.map(displayItemOptionFromV1449),
    dyes: hatRack.dyes.map(displayItemOptionFromV1449)
  };
}

function entityKindFromV1449(_entityType, entityKind) {
  switch (entityKind.TAG) {
    case "DisplayDoll" :
      return {
        TAG: "DisplayDoll",
        _0: displayDollFromV1449(entityKind._0)
      };
    case "FoodPlatter" :
      return {
        TAG: "FoodPlatter",
        _0: displayItemFromV1449(entityKind._0)
      };
    case "HatRack" :
      return {
        TAG: "HatRack",
        _0: hatRackFromV1449(entityKind._0)
      };
    case "ItemFrame" :
      return {
        TAG: "ItemFrame",
        _0: displayItemFromV1449(entityKind._0)
      };
    case "LogicSensor" :
      let sensor = entityKind._0;
      return {
        TAG: "LogicSensor",
        _0: {
          checkType: sensor.checkType,
          on: sensor.on
        }
      };
    case "TeleportationPylon" :
      return {
        TAG: "TeleportationPylon",
        _0: undefined
      };
    case "TrainingDummy" :
      return {
        TAG: "TrainingDummy",
        _0: {
          npcSlotId: entityKind._0.npcSlotId
        }
      };
    case "WeaponsRack" :
      return {
        TAG: "WeaponsRack",
        _0: displayItemFromV1449(entityKind._0)
      };
    case "DeadCellsDisplayJar" :
      return {
        TAG: "DeadCellsDisplayJar",
        _0: displayItemFromV1449(entityKind._0)
      };
    case "KiteAnchor" :
      return {
        TAG: "KiteAnchor",
        _0: {
          itemType: entityKind._0.itemType
        }
      };
    case "CritterAnchor" :
      return {
        TAG: "CritterAnchor",
        _0: {
          itemType: entityKind._0.itemType
        }
      };
  }
}

function entitiesFromV1449(entities) {
  return entities.map(entity => ({
    entityType: entity.entityType,
    id: entity.id,
    x: entity.x,
    y: entity.y,
    entityKind: entityKindFromV1449(entity.entityType, entity.entityKind)
  }));
}

function displayItemToV1449(item) {
  return {
    netId: item.netId,
    prefix: item.prefix,
    stack: item.stack
  };
}

function displayItemOptionToV1449(item) {
  return Stdlib_Option.map(item, displayItemToV1449);
}

function displayDollToV1449(displayDoll) {
  return {
    items: displayDoll.items.slice(0, 8).map(displayItemOptionToV1449),
    dyes: displayDoll.dyes.slice(0, 8).map(displayItemOptionToV1449)
  };
}

function hatRackToV1449(hatRack) {
  return {
    items: hatRack.items.map(displayItemOptionToV1449),
    dyes: hatRack.dyes.map(displayItemOptionToV1449)
  };
}

function entityKindToV1449(_entityType, entityKind) {
  switch (entityKind.TAG) {
    case "DisplayDoll" :
      return {
        TAG: "DisplayDoll",
        _0: displayDollToV1449(entityKind._0)
      };
    case "FoodPlatter" :
      return {
        TAG: "FoodPlatter",
        _0: displayItemToV1449(entityKind._0)
      };
    case "HatRack" :
      return {
        TAG: "HatRack",
        _0: hatRackToV1449(entityKind._0)
      };
    case "ItemFrame" :
      return {
        TAG: "ItemFrame",
        _0: displayItemToV1449(entityKind._0)
      };
    case "LogicSensor" :
      let sensor = entityKind._0;
      return {
        TAG: "LogicSensor",
        _0: {
          checkType: sensor.checkType,
          on: sensor.on
        }
      };
    case "TeleportationPylon" :
      return {
        TAG: "TeleportationPylon",
        _0: undefined
      };
    case "TrainingDummy" :
      return {
        TAG: "TrainingDummy",
        _0: {
          npcSlotId: entityKind._0.npcSlotId
        }
      };
    case "WeaponsRack" :
      return {
        TAG: "WeaponsRack",
        _0: displayItemToV1449(entityKind._0)
      };
    case "DeadCellsDisplayJar" :
      return {
        TAG: "DeadCellsDisplayJar",
        _0: displayItemToV1449(entityKind._0)
      };
    case "KiteAnchor" :
      return {
        TAG: "KiteAnchor",
        _0: {
          itemType: entityKind._0.itemType
        }
      };
    case "CritterAnchor" :
      return {
        TAG: "CritterAnchor",
        _0: {
          itemType: entityKind._0.itemType
        }
      };
  }
}

function entitiesToV1449(entities) {
  return entities.map(entity => ({
    entityType: entity.entityType,
    id: entity.id,
    x: entity.x,
    y: entity.y,
    entityKind: entityKindToV1449(entity.entityType, entity.entityKind)
  }));
}

function itemDropOwnershipFromV1449(value) {
  let match = value & 3;
  switch (match) {
    case 0 :
      return "None";
    case 1 :
      return "ReserveForLocalPlayer";
    case 2 :
      return "GrabDelayForLocalPlayer";
    default:
      return "GrabDelayForAllPlayers";
  }
}

function itemDropOwnershipToV1449(ownership) {
  switch (ownership) {
    case "None" :
      return 0;
    case "ReserveForLocalPlayer" :
      return 1;
    case "GrabDelayForLocalPlayer" :
      return 2;
    case "GrabDelayForAllPlayers" :
      return 3;
  }
}

function itemDropFromV1449(item, shimmer, enemyGrabDelayTime) {
  return {
    itemDropId: item.itemDropId,
    position: {
      x: item.x,
      y: item.y
    },
    velocity: {
      x: item.vx,
      y: item.vy
    },
    stack: item.stack,
    prefix: item.prefix,
    ownership: itemDropOwnershipFromV1449(item.noDelay),
    itemId: item.itemId,
    shimmer: shimmer,
    enemyGrabDelayTime: enemyGrabDelayTime
  };
}

function itemDropToV1449(item) {
  return {
    itemDropId: item.itemDropId,
    x: item.position.x,
    y: item.position.y,
    vx: item.velocity.x,
    vy: item.velocity.y,
    stack: item.stack,
    prefix: item.prefix,
    noDelay: itemDropOwnershipToV1449(item.ownership),
    itemId: item.itemId
  };
}

function fromV1449(packet) {
  switch (packet.TAG) {
    case "PlayerInfo" :
      let playerInfo = packet._0;
      return {
        TAG: "PlayerInfo",
        _0: {
          playerId: playerInfo.playerId,
          skinVariant: playerInfo.skinVariant,
          voiceVariant: 1,
          voicePitchOffset: 0.0,
          hair: playerInfo.hair,
          name: playerInfo.name,
          hairDye: playerInfo.hairDye,
          hideVisuals: playerInfo.hideVisuals,
          hideVisuals2: playerInfo.hideVisuals2,
          hideMisc: playerInfo.hideMisc,
          hairColor: playerInfo.hairColor,
          skinColor: playerInfo.skinColor,
          eyeColor: playerInfo.eyeColor,
          shirtColor: playerInfo.shirtColor,
          underShirtColor: playerInfo.underShirtColor,
          pantsColor: playerInfo.pantsColor,
          shoeColor: playerInfo.shoeColor,
          difficulty: playerInfo.difficulty,
          mode: playerInfo.mode,
          extraAccessory: playerInfo.extraAccessory,
          usingBiomeTorches: playerInfo.usingBiomeTorches,
          unlockedBiomeTorches: playerInfo.unlockedBiomeTorches,
          happyFunTorchTime: playerInfo.happyFunTorchTime,
          unlockedSuperCart: playerInfo.unlockedSuperCart,
          enabledSuperCart: playerInfo.enabledSuperCart,
          usedAegisCrystal: playerInfo.usedAegisCrystal,
          usedAegisFruit: playerInfo.usedAegisFruit,
          usedArcaneCrystal: playerInfo.usedArcaneCrystal,
          usedGalaxyPearl: playerInfo.usedGalaxyPearl,
          usedGummyWorm: playerInfo.usedGummyWorm,
          usedAmbrosia: playerInfo.usedAmbrosia,
          ateArtisanBread: playerInfo.ateArtisanBread
        }
      };
    case "PlayerInventorySlot" :
      let playerInventorySlot = packet._0;
      return {
        TAG: "PlayerInventorySlot",
        _0: {
          playerId: playerInventorySlot.playerId,
          slot: playerInventorySlotIdFromV1449(playerInventorySlot.slot),
          stack: playerInventorySlot.stack,
          prefix: playerInventorySlot.prefix,
          itemType: playerInventorySlot.itemId,
          favorited: false,
          blocked: false
        }
      };
    case "WorldInfo" :
      return {
        TAG: "WorldInfo",
        _0: worldInfoFromV1449(packet._0)
      };
    case "InitialTileSectionsRequest" :
      let req = packet._0;
      return {
        TAG: "InitialTileSectionsRequest",
        _0: {
          x: req.x,
          y: req.y,
          team: 0
        }
      };
    case "TileSectionSend" :
      let tileSectionSend = packet._0;
      return {
        TAG: "TileSectionSend",
        _0: {
          height: tileSectionSend.height,
          width: tileSectionSend.width,
          tileX: tileSectionSend.tileX,
          tileY: tileSectionSend.tileY,
          tiles: tileSectionSend.tiles,
          chests: tileSectionSend.chests,
          signs: tileSectionSend.signs,
          entities: entitiesFromV1449(tileSectionSend.entities)
        }
      };
    case "PlayerSpawn" :
      let playerSpawn = packet._0;
      return {
        TAG: "PlayerSpawn",
        _0: {
          playerId: playerSpawn.playerId,
          x: playerSpawn.x,
          y: playerSpawn.y,
          timeRemaining: playerSpawn.timeRemaining,
          numberOfDeathsPve: playerSpawn.numberOfDeathsPve,
          numberOfDeathsPvp: playerSpawn.numberOfDeathsPvp,
          team: 0,
          context: playerSpawnContextFromV1449(playerSpawn.context)
        }
      };
    case "PlayerUpdate" :
      let playerUpdate = packet._0;
      return {
        TAG: "PlayerUpdate",
        _0: {
          playerId: playerUpdate.playerId,
          control: playerUpdateControlFromV1449(playerUpdate.control),
          direction: playerUpdateDirectionFromV1449(playerUpdate.direction),
          pulleyDirection: playerUpdatePulleyDirectionFromV1449(playerUpdate.pulleyDirection),
          vortexStealthActive: playerUpdate.vortexStealthActive,
          gravityDirection: playerUpdateGravityDirectionFromV1449(playerUpdate.gravityDirection),
          shieldRaised: playerUpdate.shouldGuard,
          ghost: playerUpdate.ghost,
          selectedItem: playerUpdate.selectedItem,
          position: playerUpdate.position,
          velocity: playerUpdate.velocity,
          mountType: undefined,
          potionOfReturn: playerUpdatePotionOfReturnFromV1449(playerUpdate.potionOfReturn),
          tryKeepingHoveringUp: playerUpdate.tryKeepingHoveringUp,
          isVoidVaultEnabled: playerUpdate.isVoidVaultEnabled,
          isSitting: playerUpdate.isSitting,
          hasFinishedAnyDd2Event: playerUpdate.hasFinishedAnyDd2Event,
          isPettingAnimal: playerUpdate.isPettingAnimal,
          isTheAnimalBeingPetSmall: playerUpdate.isTheAnimalBeingPetSmall,
          tryKeepingHoveringDown: playerUpdate.tryKeepingHoveringDown,
          isSleeping: playerUpdate.isSleeping,
          autoReuseAllWeapons: false,
          controlDownHold: false,
          isOperatingAnotherEntity: false,
          controlUseTile: false,
          netCameraTarget: undefined,
          lastItemUseAttemptSuccess: false,
          snappingStoneLightUp: false
        }
      };
    case "TileSquareSend" :
      return {
        TAG: "TileSquareSend",
        _0: packet._0
      };
    case "ItemDropUpdate" :
      return {
        TAG: "ItemDropUpdate",
        _0: itemDropFromV1449(packet._0, undefined, undefined)
      };
    case "ItemOwner" :
      let itemOwner = packet._0;
      return {
        TAG: "ItemOwner",
        _0: {
          itemDropId: itemOwner.itemDropId,
          owner: itemOwner.owner,
          timeToKeepReservation: 0,
          grabDelayPlayer: 0,
          grabDelayTime: 0,
          position: {
            x: 0.0,
            y: 0.0
          }
        }
      };
    case "NpcUpdate" :
      let npcUpdate = packet._0;
      return {
        TAG: "NpcUpdate",
        _0: {
          npcSlotId: npcUpdate.npcSlotId,
          generation: 0,
          npcTypeId: npcUpdate.npcTypeId,
          x: npcUpdate.x,
          y: npcUpdate.y,
          vx: npcUpdate.vx,
          vy: npcUpdate.vy,
          target: npcUpdate.target,
          directionX: npcUpdate.directionX,
          directionY: npcUpdate.directionY,
          ai: npcUpdate.ai,
          spriteDirection: npcUpdate.spriteDirection,
          life: npcUpdateLifeFromV1449(npcUpdate.life),
          releaseOwner: npcUpdate.releaseOwner,
          playerCountScale: npcUpdate.playerCountScale,
          difficulty: npcUpdate.strengthMultiplier,
          spawnedFromStatue: npcUpdate.spawnedFromStatue,
          spawnNeedsSyncing: false,
          shimmerTransparency: false
        }
      };
    case "ProjectileSync" :
      let value = packet._0;
      return {
        TAG: "ProjectileSync",
        _0: {
          projectileKey: {
            spawner: value.owner,
            index: value.projectileId,
            generation: Stdlib_Option.getOr(value.projectileUuid, 0)
          },
          position: {
            x: value.x,
            y: value.y
          },
          velocity: {
            x: value.vx,
            y: value.vy
          },
          projectileType: value.projectileType,
          ai: value.ai,
          bannerIdToRespondTo: value.bannerIdToRespondTo,
          damage: value.damage,
          knockback: value.knockback,
          originalDamage: value.originalDamage
        }
      };
    case "NpcStrike" :
      let value$1 = packet._0;
      return {
        TAG: "NpcStrike",
        _0: {
          npcSlotId: value$1.npcId,
          generation: 0,
          damage: value$1.damage,
          knockback: value$1.knockback,
          direction: value$1.direction,
          critical: value$1.critical
        }
      };
    case "ProjectileDestroy" :
      let value$2 = packet._0;
      return {
        TAG: "ProjectileDestroy",
        _0: {
          projectileKey: {
            spawner: value$2.owner,
            index: value$2.projectileId,
            generation: 0
          },
          position: {
            x: 0.0,
            y: 0.0
          }
        }
      };
    case "Zones" :
      let zones = packet._0;
      return {
        TAG: "Zones",
        _0: {
          playerId: zones.playerId,
          zone1: zones.zone1,
          zone2: zones.zone2,
          zone3: zones.zone3,
          zone4: zones.zone4,
          zone5: zones.zone5,
          townNPCs: 0
        }
      };
    case "ItemOwnerRemove" :
      return {
        TAG: "ItemOwnerRemove",
        _0: {
          itemDropId: packet._0.itemDropId,
          forceAssignToServer: false
        }
      };
    case "PlayerBuffsSet" :
      let playerBuffsSet = packet._0;
      return {
        TAG: "PlayerBuffsSet",
        _0: {
          playerId: playerBuffsSet.playerId,
          buffs: playerBuffsSet.buffs.filter(buff => buff !== 0)
        }
      };
    case "NpcBuffUpdate" :
      let npcBuffUpdate = packet._0;
      let buffs = [];
      let buffTimes = [];
      for (let i = 0, i_finish = npcBuffUpdate.buffs.length; i < i_finish; ++i) {
        let buff = npcBuffUpdate.buffs[i];
        let buffTime = npcBuffUpdate.buffTimes[i];
        if (buff > 0 && buffTime > 0) {
          buffs.push(buff);
          buffTimes.push(buffTime);
        }
      }
      return {
        TAG: "NpcBuffUpdate",
        _0: {
          npcId: npcBuffUpdate.npcId,
          buffs: buffs,
          buffTimes: buffTimes
        }
      };
    case "PlayerDodge" :
      let value$3 = packet._0;
      let match = value$3.dodge;
      let tmp;
      switch (match) {
        case "Ninja" :
          tmp = "Ninja";
          break;
        case "Shadow" :
          tmp = "Shadow";
          break;
        case "BrainOfConfusion" :
          tmp = "BrainOfConfusion";
          break;
      }
      return {
        TAG: "PlayerDodge",
        _0: {
          playerId: value$3.playerId,
          dodge: tmp
        }
      };
    case "Teleport" :
      let teleport = packet._0;
      let match$1 = teleport.teleportType;
      let tmp$1;
      switch (match$1) {
        case "Player" :
          tmp$1 = "Player";
          break;
        case "Npc" :
          tmp$1 = "Npc";
          break;
        case "PlayerToPlayer" :
          tmp$1 = "PlayerToPlayer";
          break;
      }
      return {
        TAG: "Teleport",
        _0: {
          teleportType: tmp$1,
          getPositionFromTarget: teleport.getPositionFromTarget,
          targetId: teleport.targetId,
          x: teleport.x,
          y: teleport.y,
          style: teleport.style,
          extraInfo: teleport.extraInfo
        }
      };
    case "NpcCatch" :
      return {
        TAG: "NpcCatch",
        _0: {
          npcId: packet._0.npcId
        }
      };
    case "TravellingMerchantInventory" :
      return {
        TAG: "TravellingMerchantInventory",
        _0: {
          items: packet._0.items
        }
      };
    case "TeleportationPotion" :
      let match$2 = packet._0.teleportType;
      let tmp$2;
      switch (match$2) {
        case "TeleportationPotion" :
          tmp$2 = "TeleportationPotion";
          break;
        case "MagicConch" :
          tmp$2 = "MagicConch";
          break;
        case "DemonConch" :
          tmp$2 = "DemonConch";
          break;
        case "ShellphoneSpawn" :
          tmp$2 = "ShellphoneSpawn";
          break;
      }
      return {
        TAG: "TeleportationPotion",
        _0: {
          teleportType: tmp$2
        }
      };
    case "NetModuleLoad" :
      return {
        TAG: "NetModuleLoad",
        _0: netModuleLoadFromV1449(packet._0)
      };
    case "ItemForceIntoNearestChest" :
      return {
        TAG: "ItemForceIntoNearestChest",
        _0: {
          TAG: "ClientRequest",
          _0: {
            slotIds: [packet._0.slot],
            smartStack: false
          }
        }
      };
    case "ItemDropInstancedUpdate" :
      return {
        TAG: "ItemDropInstancedUpdate",
        _0: itemDropFromV1449(packet._0, undefined, undefined)
      };
    case "TileEntityDisplayDollItemSync" :
      let tileEntityDisplayDollItemSync = packet._0;
      return {
        TAG: "TileEntityDisplayDollItemSync",
        _0: {
          playerId: tileEntityDisplayDollItemSync.playerId,
          tileEntityId: tileEntityDisplayDollItemSync.tileEntityId,
          itemIndex: tileEntityDisplayDollItemSync.itemIndex,
          command: "Equip",
          data: {
            TAG: "Item",
            _0: {
              itemId: tileEntityDisplayDollItemSync.itemId,
              stack: tileEntityDisplayDollItemSync.stack,
              prefix: tileEntityDisplayDollItemSync.prefix
            }
          }
        }
      };
    case "PlayerLuckFactorsUpdate" :
      let playerLuckFactorsUpdate = packet._0;
      return {
        TAG: "PlayerLuckFactorsUpdate",
        _0: {
          playerId: playerLuckFactorsUpdate.playerId,
          ladyBugLuckTimeLeft: playerLuckFactorsUpdate.ladyBugLuckTimeLeft,
          torchLuck: playerLuckFactorsUpdate.torchLuck,
          luckPotion: playerLuckFactorsUpdate.luckPotion,
          hasGardenGnomeNearby: playerLuckFactorsUpdate.hasGardenGnomeNearby,
          brokenMirrorBadLuck: false,
          equipmentBasedLuckBonus: playerLuckFactorsUpdate.equipmentBasedLuckBonus,
          coinLuck: playerLuckFactorsUpdate.coinLuck,
          kiteLuckLevel: 0
        }
      };
    case "ItemDropShimmeredUpdate" :
      let item = packet._0;
      return {
        TAG: "ItemDropUpdate",
        _0: itemDropFromV1449(item, {
          shimmered: item.shimmered,
          shimmerTime: item.shimmeredTime
        }, undefined)
      };
    case "ShimmerEffectOrCoinLuck" :
      let shimmerEffectOrCoinLuck = packet._0;
      switch (shimmerEffectOrCoinLuck.TAG) {
        case "ShimmerEffect" :
          return {
            TAG: "ShimmerEffectOrCoinLuck",
            _0: {
              TAG: "ShimmerEffect",
              _0: shimmerEffectOrCoinLuck._0,
              _1: shimmerEffectOrCoinLuck._1
            }
          };
        case "CoinLuck" :
          return {
            TAG: "ShimmerEffectOrCoinLuck",
            _0: {
              TAG: "CoinLuck",
              _0: shimmerCoinLuckFromV1449(shimmerEffectOrCoinLuck._0)
            }
          };
        case "NewShimmerEffect" :
          return {
            TAG: "ShimmerEffectOrCoinLuck",
            _0: {
              TAG: "ShimmerEffect",
              _0: 0.0,
              _1: 0.0
            }
          };
      }
    case "ItemDropProtectedUpdate" :
      let item$1 = packet._0;
      return {
        TAG: "ItemDropUpdate",
        _0: itemDropFromV1449(item$1, undefined, item$1.timeLeftInWhichTheItemCannotBeTakenByEnemies)
      };
    default:
      return packet;
  }
}

function latestToV1449(packet) {
  switch (packet.TAG) {
    case "PlayerInfo" :
      let playerInfo = packet._0;
      return {
        TAG: "PlayerInfo",
        _0: {
          playerId: playerInfo.playerId,
          skinVariant: playerInfo.skinVariant,
          hair: playerInfo.hair,
          name: playerInfo.name,
          hairDye: playerInfo.hairDye,
          hideVisuals: playerInfo.hideVisuals,
          hideVisuals2: playerInfo.hideVisuals2,
          hideMisc: playerInfo.hideMisc,
          hairColor: playerInfo.hairColor,
          skinColor: playerInfo.skinColor,
          eyeColor: playerInfo.eyeColor,
          shirtColor: playerInfo.shirtColor,
          underShirtColor: playerInfo.underShirtColor,
          pantsColor: playerInfo.pantsColor,
          shoeColor: playerInfo.shoeColor,
          difficulty: playerInfo.difficulty,
          mode: playerInfo.mode,
          extraAccessory: playerInfo.extraAccessory,
          usingBiomeTorches: playerInfo.usingBiomeTorches,
          unlockedBiomeTorches: playerInfo.unlockedBiomeTorches,
          happyFunTorchTime: playerInfo.happyFunTorchTime,
          unlockedSuperCart: playerInfo.unlockedSuperCart,
          enabledSuperCart: playerInfo.enabledSuperCart,
          usedAegisCrystal: playerInfo.usedAegisCrystal,
          usedAegisFruit: playerInfo.usedAegisFruit,
          usedArcaneCrystal: playerInfo.usedArcaneCrystal,
          usedGalaxyPearl: playerInfo.usedGalaxyPearl,
          usedGummyWorm: playerInfo.usedGummyWorm,
          usedAmbrosia: playerInfo.usedAmbrosia,
          ateArtisanBread: playerInfo.ateArtisanBread
        }
      };
    case "PlayerInventorySlot" :
      let playerInventorySlot = packet._0;
      return {
        TAG: "PlayerInventorySlot",
        _0: {
          playerId: playerInventorySlot.playerId,
          slot: playerInventorySlot.slot,
          stack: playerInventorySlot.stack,
          prefix: playerInventorySlot.prefix,
          itemId: playerInventorySlot.itemType
        }
      };
    case "WorldInfo" :
      return {
        TAG: "WorldInfo",
        _0: worldInfoToV1449(packet._0)
      };
    case "InitialTileSectionsRequest" :
      let req = packet._0;
      return {
        TAG: "InitialTileSectionsRequest",
        _0: {
          x: req.x,
          y: req.y
        }
      };
    case "TileSectionSend" :
      let tileSectionSend = packet._0;
      return {
        TAG: "TileSectionSend",
        _0: {
          height: tileSectionSend.height,
          width: tileSectionSend.width,
          tileX: tileSectionSend.tileX,
          tileY: tileSectionSend.tileY,
          tiles: tileSectionSend.tiles,
          chests: tileSectionSend.chests,
          signs: tileSectionSend.signs,
          entities: entitiesToV1449(tileSectionSend.entities)
        }
      };
    case "PlayerSpawn" :
      let playerSpawn = packet._0;
      return {
        TAG: "PlayerSpawn",
        _0: {
          playerId: playerSpawn.playerId,
          x: playerSpawn.x,
          y: playerSpawn.y,
          timeRemaining: playerSpawn.timeRemaining,
          numberOfDeathsPve: playerSpawn.numberOfDeathsPve,
          numberOfDeathsPvp: playerSpawn.numberOfDeathsPvp,
          context: playerSpawnContextToV1449(playerSpawn.context)
        }
      };
    case "PlayerUpdate" :
      let playerUpdate = packet._0;
      return {
        TAG: "PlayerUpdate",
        _0: {
          playerId: playerUpdate.playerId,
          control: playerUpdateControlToV1449(playerUpdate.control),
          direction: playerUpdateDirectionToV1449(playerUpdate.direction),
          pulleyDirection: playerUpdatePulleyDirectionToV1449(playerUpdate.pulleyDirection),
          vortexStealthActive: playerUpdate.vortexStealthActive,
          gravityDirection: playerUpdateGravityDirectionToV1449(playerUpdate.gravityDirection),
          shouldGuard: playerUpdate.shieldRaised,
          ghost: playerUpdate.ghost,
          selectedItem: playerUpdate.selectedItem,
          position: playerUpdate.position,
          velocity: playerUpdate.velocity,
          potionOfReturn: playerUpdatePotionOfReturnToV1449(playerUpdate.potionOfReturn),
          tryKeepingHoveringUp: playerUpdate.tryKeepingHoveringUp,
          isVoidVaultEnabled: playerUpdate.isVoidVaultEnabled,
          isSitting: playerUpdate.isSitting,
          hasFinishedAnyDd2Event: playerUpdate.hasFinishedAnyDd2Event,
          isPettingAnimal: playerUpdate.isPettingAnimal,
          isTheAnimalBeingPetSmall: playerUpdate.isTheAnimalBeingPetSmall,
          tryKeepingHoveringDown: playerUpdate.tryKeepingHoveringDown,
          isSleeping: playerUpdate.isSleeping
        }
      };
    case "ItemDropUpdate" :
      let item = packet._0;
      let match = item.shimmer;
      let match$1 = item.enemyGrabDelayTime;
      if (match !== undefined) {
        let base = itemDropToV1449(item);
        return {
          TAG: "ItemDropShimmeredUpdate",
          _0: {
            itemDropId: base.itemDropId,
            x: base.x,
            y: base.y,
            vx: base.vx,
            vy: base.vy,
            stack: base.stack,
            prefix: base.prefix,
            noDelay: base.noDelay,
            itemId: base.itemId,
            shimmered: match.shimmered,
            shimmeredTime: match.shimmerTime
          }
        };
      }
      if (match$1 === undefined) {
        return {
          TAG: "ItemDropUpdate",
          _0: itemDropToV1449(item)
        };
      }
      let base$1 = itemDropToV1449(item);
      return {
        TAG: "ItemDropProtectedUpdate",
        _0: {
          itemDropId: base$1.itemDropId,
          x: base$1.x,
          y: base$1.y,
          vx: base$1.vx,
          vy: base$1.vy,
          stack: base$1.stack,
          prefix: base$1.prefix,
          noDelay: base$1.noDelay,
          itemId: base$1.itemId,
          timeLeftInWhichTheItemCannotBeTakenByEnemies: match$1
        }
      };
    case "ItemOwner" :
      let itemOwner = packet._0;
      return {
        TAG: "ItemOwner",
        _0: {
          itemDropId: itemOwner.itemDropId,
          owner: itemOwner.owner
        }
      };
    case "NpcUpdate" :
      let npcUpdate = packet._0;
      return {
        TAG: "NpcUpdate",
        _0: {
          npcSlotId: npcUpdate.npcSlotId,
          npcTypeId: npcUpdate.npcTypeId,
          x: npcUpdate.x,
          y: npcUpdate.y,
          vx: npcUpdate.vx,
          vy: npcUpdate.vy,
          target: npcUpdate.target,
          directionX: npcUpdate.directionX,
          directionY: npcUpdate.directionY,
          ai: npcUpdate.ai,
          spriteDirection: npcUpdate.spriteDirection,
          life: npcUpdateLifeToV1449(npcUpdate.life),
          releaseOwner: npcUpdate.releaseOwner,
          playerCountScale: npcUpdate.playerCountScale,
          strengthMultiplier: npcUpdate.difficulty,
          spawnedFromStatue: npcUpdate.spawnedFromStatue
        }
      };
    case "ProjectileSync" :
      let value = packet._0;
      return {
        TAG: "ProjectileSync",
        _0: {
          projectileId: value.projectileKey.index,
          x: value.position.x,
          y: value.position.y,
          vx: value.velocity.x,
          vy: value.velocity.y,
          owner: value.projectileKey.spawner,
          projectileType: value.projectileType,
          ai: value.ai,
          bannerIdToRespondTo: value.bannerIdToRespondTo,
          damage: value.damage,
          knockback: value.knockback,
          originalDamage: value.originalDamage,
          projectileUuid: value.projectileKey.generation === 0 ? undefined : value.projectileKey.generation
        }
      };
    case "NpcStrike" :
      let value$1 = packet._0;
      return {
        TAG: "NpcStrike",
        _0: {
          npcId: value$1.npcSlotId,
          damage: value$1.damage,
          knockback: value$1.knockback,
          direction: value$1.direction,
          critical: value$1.critical
        }
      };
    case "ProjectileDestroy" :
      let value$2 = packet._0;
      return {
        TAG: "ProjectileDestroy",
        _0: {
          projectileId: value$2.projectileKey.index,
          owner: value$2.projectileKey.spawner
        }
      };
    case "Zones" :
      let zones = packet._0;
      return {
        TAG: "Zones",
        _0: {
          playerId: zones.playerId,
          zone1: zones.zone1,
          zone2: zones.zone2,
          zone3: zones.zone3,
          zone4: zones.zone4,
          zone5: zones.zone5
        }
      };
    case "ItemOwnerRemove" :
      return {
        TAG: "ItemOwnerRemove",
        _0: {
          itemDropId: packet._0.itemDropId
        }
      };
    case "PlayerBuffsSet" :
      let playerBuffsSet = packet._0;
      let buffs = Stdlib_Array.make(44, 0);
      let max = Primitive_int.min(44, playerBuffsSet.buffs.length);
      for (let i = 0; i < max; ++i) {
        buffs[i] = playerBuffsSet.buffs[i];
      }
      return {
        TAG: "PlayerBuffsSet",
        _0: {
          playerId: playerBuffsSet.playerId,
          buffs: buffs
        }
      };
    case "NpcBuffUpdate" :
      let npcBuffUpdate = packet._0;
      let buffs$1 = Stdlib_Array.make(20, 0);
      let buffTimes = Stdlib_Array.make(20, 0);
      let max$1 = Primitive_int.min(20, npcBuffUpdate.buffs.length);
      for (let i$1 = 0; i$1 < max$1; ++i$1) {
        buffs$1[i$1] = npcBuffUpdate.buffs[i$1];
        buffTimes[i$1] = npcBuffUpdate.buffTimes[i$1];
      }
      return {
        TAG: "NpcBuffUpdate",
        _0: {
          npcId: npcBuffUpdate.npcId,
          buffs: buffs$1,
          buffTimes: buffTimes
        }
      };
    case "PlayerDodge" :
      let value$3 = packet._0;
      let match$2 = value$3.dodge;
      let tmp;
      switch (match$2) {
        case "Ninja" :
          tmp = "Ninja";
          break;
        case "Shadow" :
          tmp = "Shadow";
          break;
        case "BrainOfConfusion" :
        case "MysticSash" :
          tmp = "BrainOfConfusion";
          break;
      }
      return {
        TAG: "PlayerDodge",
        _0: {
          playerId: value$3.playerId,
          dodge: tmp
        }
      };
    case "Teleport" :
      let teleport = packet._0;
      let match$3 = teleport.teleportType;
      let tmp$1;
      switch (match$3) {
        case "Npc" :
          tmp$1 = "Npc";
          break;
        case "PlayerToPlayer" :
          tmp$1 = "PlayerToPlayer";
          break;
        case "Player" :
        case "TeleportAck" :
          tmp$1 = "Player";
          break;
      }
      return {
        TAG: "Teleport",
        _0: {
          teleportType: tmp$1,
          getPositionFromTarget: teleport.getPositionFromTarget,
          targetId: teleport.targetId,
          x: teleport.x,
          y: teleport.y,
          style: teleport.style,
          extraInfo: teleport.extraInfo
        }
      };
    case "NpcCatch" :
      return {
        TAG: "NpcCatch",
        _0: {
          npcId: packet._0.npcId,
          playerId: 0
        }
      };
    case "TravellingMerchantInventory" :
      let inv = packet._0;
      let items = Stdlib_Array.make(40, 0);
      let max$2 = Primitive_int.min(40, inv.items.length);
      for (let i$2 = 0; i$2 < max$2; ++i$2) {
        items[i$2] = inv.items[i$2];
      }
      return {
        TAG: "TravellingMerchantInventory",
        _0: {
          items: items
        }
      };
    case "TeleportationPotion" :
      let match$4 = packet._0.teleportType;
      let tmp$2;
      switch (match$4) {
        case "MagicConch" :
          tmp$2 = "MagicConch";
          break;
        case "DemonConch" :
          tmp$2 = "DemonConch";
          break;
        case "ShellphoneSpawn" :
          tmp$2 = "ShellphoneSpawn";
          break;
        case "TeleportationPotion" :
        case "PlayerNoSpaceTeleport" :
          tmp$2 = "TeleportationPotion";
          break;
      }
      return {
        TAG: "TeleportationPotion",
        _0: {
          teleportType: tmp$2
        }
      };
    case "NetModuleLoad" :
      let converted = netModuleLoadToV1449(packet._0);
      if (converted !== undefined) {
        return {
          TAG: "NetModuleLoad",
          _0: converted
        };
      } else {
        return {
          TAG: "NetModuleLoad",
          _0: {
            TAG: "Ping",
            _0: {
              x: 0.0,
              y: 0.0
            }
          }
        };
      }
    case "ItemForceIntoNearestChest" :
      let itemForce = packet._0;
      if (itemForce.TAG === "ClientRequest") {
        return {
          TAG: "ItemForceIntoNearestChest",
          _0: {
            slot: Stdlib_Option.getOr(itemForce._0.slotIds[0], 0)
          }
        };
      } else {
        return {
          TAG: "ItemForceIntoNearestChest",
          _0: {
            slot: 0
          }
        };
      }
    case "ItemDropInstancedUpdate" :
      return {
        TAG: "ItemDropInstancedUpdate",
        _0: itemDropToV1449(packet._0)
      };
    case "TileEntityDisplayDollItemSync" :
      let tileEntityDisplayDollItemSync = packet._0;
      let item$1 = tileEntityDisplayDollItemSync.data;
      if (item$1.TAG !== "Item") {
        return {
          TAG: "TileEntityDisplayDollItemSync",
          _0: {
            playerId: tileEntityDisplayDollItemSync.playerId,
            tileEntityId: tileEntityDisplayDollItemSync.tileEntityId,
            itemIndex: tileEntityDisplayDollItemSync.itemIndex,
            itemId: 0,
            stack: 0,
            prefix: 0
          }
        };
      }
      let item$2 = item$1._0;
      return {
        TAG: "TileEntityDisplayDollItemSync",
        _0: {
          playerId: tileEntityDisplayDollItemSync.playerId,
          tileEntityId: tileEntityDisplayDollItemSync.tileEntityId,
          itemIndex: tileEntityDisplayDollItemSync.itemIndex,
          itemId: item$2.itemId,
          stack: item$2.stack,
          prefix: item$2.prefix
        }
      };
    case "PlayerLuckFactorsUpdate" :
      let playerLuckFactorsUpdate = packet._0;
      return {
        TAG: "PlayerLuckFactorsUpdate",
        _0: {
          playerId: playerLuckFactorsUpdate.playerId,
          ladyBugLuckTimeLeft: playerLuckFactorsUpdate.ladyBugLuckTimeLeft,
          torchLuck: playerLuckFactorsUpdate.torchLuck,
          luckPotion: playerLuckFactorsUpdate.luckPotion,
          hasGardenGnomeNearby: playerLuckFactorsUpdate.hasGardenGnomeNearby,
          equipmentBasedLuckBonus: playerLuckFactorsUpdate.equipmentBasedLuckBonus,
          coinLuck: playerLuckFactorsUpdate.coinLuck
        }
      };
    case "ShimmerEffectOrCoinLuck" :
      let shimmerEffectOrCoinLuck = packet._0;
      if (shimmerEffectOrCoinLuck.TAG === "ShimmerEffect") {
        return {
          TAG: "ShimmerEffectOrCoinLuck",
          _0: {
            TAG: "ShimmerEffect",
            _0: shimmerEffectOrCoinLuck._0,
            _1: shimmerEffectOrCoinLuck._1
          }
        };
      } else {
        return {
          TAG: "ShimmerEffectOrCoinLuck",
          _0: {
            TAG: "CoinLuck",
            _0: shimmerCoinLuckToV1449(shimmerEffectOrCoinLuck._0)
          }
        };
      }
    case "ItemDropClear" :
      return {
        TAG: "ItemDropUpdate",
        _0: {
          itemDropId: packet._0.itemDropId,
          x: 0.0,
          y: 0.0,
          vx: 0.0,
          vy: 0.0,
          stack: 0,
          prefix: 0,
          noDelay: 0,
          itemId: 0
        }
      };
    default:
      return packet;
  }
}

function convertFromV1449IfNeeded(buffer, fromServer) {
  let match = buffer.length;
  if (!(match > 2 || match < 0)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidPacketLength",
        _0: buffer.length
      }
    };
  }
  let match$1 = PacketType$TerrariaPacket.fromInt(buffer[2]);
  if (match$1 === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidPacketType",
        _0: buffer[2]
      }
    };
  }
  switch (match$1) {
    case "NpcItemStrike" :
      return {
        TAG: "Ok",
        _0: "DiscardAsNotExists"
      };
    case "CavernMonsterTypeSync" :
      if (fromServer) {
        return {
          TAG: "Ok",
          _0: "PacketStructureIsSame"
        };
      } else {
        return {
          TAG: "Ok",
          _0: "DiscardAsNotExists"
        };
      }
    case "ShimmerEffectOrCoinLuck" :
      if (!fromServer) {
        return {
          TAG: "Ok",
          _0: "DiscardAsNotExists"
        };
      }
      break;
    case "PlayerInfo" :
    case "PlayerInventorySlot" :
    case "WorldInfo" :
    case "InitialTileSectionsRequest" :
    case "TileSectionSend" :
    case "PlayerSpawn" :
    case "PlayerUpdate" :
    case "TileSquareSend" :
    case "ItemDropUpdate" :
    case "ItemOwner" :
    case "NpcUpdate" :
    case "ProjectileSync" :
    case "NpcStrike" :
    case "ProjectileDestroy" :
    case "Zones" :
    case "ItemOwnerRemove" :
    case "PlayerBuffsSet" :
    case "NpcBuffUpdate" :
    case "PlayerDodge" :
    case "Teleport" :
    case "NpcCatch" :
    case "TravellingMerchantInventory" :
    case "TeleportationPotion" :
    case "NetModuleLoad" :
    case "ItemForceIntoNearestChest" :
    case "ItemDropInstancedUpdate" :
    case "TileEntityDisplayDollItemSync" :
    case "PlayerLuckFactorsUpdate" :
    case "ItemDropShimmeredUpdate" :
    case "ItemDropProtectedUpdate" :
      break;
    default:
      return {
        TAG: "Ok",
        _0: "PacketStructureIsSame"
      };
  }
  try {
    return Stdlib_Result.map(Stdlib_Result.map(Parserv1449$TerrariaPacket.parse(buffer, fromServer, undefined), fromV1449), p => ({
      TAG: "ConvertedToLatestVersion",
      _0: p
    }));
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "ReaderError",
          _0: {
            context: "Parser.parseLazy",
            error: obj._1
          }
        }
      };
    }
    throw obj;
  }
}

function convertToV1449IfNeeded(buffer, fromServer) {
  let match = buffer.length;
  if (!(match > 2 || match < 0)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidPacketLength",
        _0: buffer.length
      }
    };
  }
  let match$1 = PacketType$TerrariaPacket.fromInt(buffer[2]);
  if (match$1 === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidPacketType",
        _0: buffer[2]
      }
    };
  }
  switch (match$1) {
    case "PlayerInfo" :
    case "PlayerInventorySlot" :
    case "WorldInfo" :
    case "InitialTileSectionsRequest" :
    case "PlayerSpawn" :
    case "PlayerUpdate" :
    case "ItemDropUpdate" :
    case "ItemOwner" :
    case "NpcUpdate" :
    case "ProjectileSync" :
    case "NpcStrike" :
    case "ProjectileDestroy" :
    case "Zones" :
    case "ItemOwnerRemove" :
    case "PlayerBuffsSet" :
    case "NpcBuffUpdate" :
    case "PlayerDodge" :
    case "Teleport" :
    case "NpcCatch" :
    case "TravellingMerchantInventory" :
    case "TeleportationPotion" :
    case "NetModuleLoad" :
    case "ItemForceIntoNearestChest" :
    case "ItemDropInstancedUpdate" :
    case "TileEntityDisplayDollItemSync" :
    case "PlayerLuckFactorsUpdate" :
    case "ShimmerEffectOrCoinLuck" :
    case "ItemDropClear" :
      break;
    case "NpcItemStrike" :
    case "ItemDropShimmeredUpdate" :
    case "ItemDropProtectedUpdate" :
    case "DeadCellsDisplayJarTryPlacing" :
    case "PlayerSpectate" :
    case "PlayerItemUseSound" :
    case "NpcHurtByDebuff" :
    case "Ping" :
    case "ChestResize" :
    case "LeashedEntityAnchorInsertItem" :
    case "PlayerTeamUpdate" :
    case "PlayerTeamSwapSpawn" :
    case "SectionRequest" :
    case "ItemDropPosition" :
    case "HostToken" :
    case "DamageNPCAck" :
    case "ServerInfo" :
    case "PlayerPlatformInfo" :
      return {
        TAG: "Ok",
        _0: "DiscardAsNotExists"
      };
    default:
      return {
        TAG: "Ok",
        _0: "PacketStructureIsSame"
      };
  }
  try {
    return Stdlib_Result.map(Parser$TerrariaPacket.parse(buffer, fromServer, undefined), packet => {
      switch (packet.TAG) {
        case "PlayerInventorySlot" :
          let playerInventorySlot = packet._0;
          let slot = playerInventorySlotIdToV1449(playerInventorySlot.slot);
          if (slot !== undefined) {
            return {
              TAG: "ConvertedToV1449",
              _0: {
                TAG: "PlayerInventorySlot",
                _0: {
                  playerId: playerInventorySlot.playerId,
                  slot: slot,
                  stack: playerInventorySlot.stack,
                  prefix: playerInventorySlot.prefix,
                  itemId: playerInventorySlot.itemType
                }
              }
            };
          } else {
            return "DiscardAsNotExists";
          }
        case "Teleport" :
          if (packet._0.teleportType === "TeleportAck") {
            return "DiscardAsNotExists";
          } else {
            return {
              TAG: "ConvertedToV1449",
              _0: latestToV1449(packet)
            };
          }
        case "NetModuleLoad" :
          let converted = netModuleLoadToV1449(packet._0);
          if (converted !== undefined) {
            return {
              TAG: "ConvertedToV1449",
              _0: {
                TAG: "NetModuleLoad",
                _0: converted
              }
            };
          } else {
            return "DiscardAsNotExists";
          }
        default:
          return {
            TAG: "ConvertedToV1449",
            _0: latestToV1449(packet)
          };
      }
    });
  } catch (raw_obj) {
    let obj = Primitive_exceptions.internalToException(raw_obj);
    if (obj.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: {
          TAG: "ReaderError",
          _0: {
            context: "Parser.parseLazy",
            error: obj._1
          }
        }
      };
    }
    throw obj;
  }
}

export {
  convertFromV1449IfNeeded,
  convertToV1449IfNeeded,
}
/* Parser-TerrariaPacket Not a pure module */
