// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(self) {
  return `{ x: ` + String(self.x) + `, y: ` + String(self.y) + ` }`;
}

let Int = {
  toString: toString
};

function toString$1(self) {
  return `{ x: ` + String(self.x) + `, y: ` + String(self.y) + ` }`;
}

let Float = {
  toString: toString$1
};

exports.Int = Int;
exports.Float = Float;
/* No side effect */
